const WORDS10 = [
  {"no":901,"word":"gap","star":false,"pos":"名","meaning":"すき間、へだたり","example":"Be careful!  There is a gap.","circle":true},
  {"no":902,"word":"garage","star":false,"pos":"名","meaning":"ガレージ、車庫","example":"He is cleaning his car in the garage.","circle":true},
  {"no":903,"word":"garbage","star":true,"pos":"名","meaning":"生ごみ、くず","example":"We should try to reduce garbage.","circle":false},
  {"no":904,"word":"garden","star":false,"pos":"名","meaning":"畑、庭","example":"You have a beautiful garden.","circle":false},
  {"no":905,"word":"garlic","star":false,"pos":"名","meaning":"ニンニク","example":"A lot of garlic is used in Italian food.","circle":true},
  {"no":906,"word":"gas","star":false,"pos":"名","meaning":"（燃料用の）ガス、ガソリン","example":"Now we can't live without electricity or gas.","circle":false},
  {"no":907,"word":"gas station","star":true,"pos":"名","meaning":"ガソリンスタンド","example":"The nearest gas station is 10 minutes away from here.","circle":true},
  {"no":908,"word":"gate","star":false,"pos":"名","meaning":"門","example":"You can enter the building through the front gate.","circle":false},
  {"no":909,"word":"gather","star":false,"pos":"動","meaning":"集まる、集める","example":"We gather around a kotatsu in winter.","circle":false},
  {"no":910,"word":"gender","star":false,"pos":"名","meaning":"性、性別","example":"It is important to discuss gender issues.","circle":true},
  {"no":911,"word":"generally","star":false,"pos":"副","meaning":"一般に","example":"Himeji Castle is generally known as Shirasagi Castle.","circle":true},
  {"no":912,"word":"generation","star":false,"pos":"名","meaning":"世代","example":"We must teach the next generation about the earthquake.","circle":true},
  {"no":913,"word":"gentle","star":true,"pos":"形","meaning":"思いやりのある、優しい","example":"My grandfather is very gentle.","circle":false},
  {"no":914,"word":"gentleman","star":false,"pos":"名","meaning":"紳士、男性     【複数】 gentlemen","example":"Ladies and gentlemen, welcome to Hyogo.","circle":false},
  {"no":915,"word":"German","star":false,"pos":"名・形","meaning":"ドイツの、ドイツ人（の）、ドイツ語（の）","example":"German is the language used in Germany.","circle":false},
  {"no":916,"word":"Germany","star":false,"pos":"名","meaning":"ドイツ","example":"I came to Japan from Germany last month.","circle":false},
  {"no":917,"word":"gesture","star":false,"pos":"名","meaning":"身ぶり、ジェスチャー","example":"I learned the Japanese gesture for “Come here”.","circle":false},
  {"no":918,"word":"get","star":true,"pos":"動","meaning":"①手に入れる\n②（～に）なる\n※get back 戻る、取り返す    get on 乗る　get off　降りる\nget to ～　～に着く    get up  起きる    get well よくなる\n【活用】 get - got - got/gotten","example":"①I want to get something to drink.\n②It is getting warmer.","circle":false},
  {"no":919,"word":"giant","star":false,"pos":"形","meaning":"巨大な、飛躍的な","example":"My dog was afraid of the giant dog at the park.","circle":true},
  {"no":920,"word":"gift","star":false,"pos":"名","meaning":"贈り物","example":"This is a gift for you.","circle":false},
  {"no":921,"word":"ginger","star":false,"pos":"名","meaning":"ショウガ","example":"I usually use some ginger when I cook fish.","circle":true},
  {"no":922,"word":"giraffe","star":false,"pos":"名","meaning":"キリン","example":"There are three giraffes at the zoo.","circle":true},
  {"no":923,"word":"girl","star":true,"pos":"名","meaning":"女の子、少女","example":"The girl plays the piano every day.","circle":false},
  {"no":924,"word":"girlfriend","star":false,"pos":"名","meaning":"ガールフレンド","example":"I like my brother's girlfriend.","circle":true},
  {"no":925,"word":"give","star":false,"pos":"動","meaning":"与える、あげる　※give up　あきらめる\n【活用】 give - gave - given","example":"Please give me some water.","circle":false},
  {"no":926,"word":"glad","star":false,"pos":"形","meaning":"（人が）うれしい、喜んで　　※be glad to ～　～してうれしい","example":"I'm glad you like it.","circle":false},
  {"no":927,"word":"glass","star":false,"pos":"名","meaning":"（ガラスの）コップ    ※a glass of ～　コップ一杯の～","example":"Can I have a glass of water?","circle":false},
  {"no":928,"word":"glasses","star":false,"pos":"名","meaning":"眼鏡（複数形で使う）","example":"I bought new glasses yesterday.","circle":false},
  {"no":929,"word":"global","star":false,"pos":"形","meaning":"地球の、地球規模の","example":"We should talk about global problems.","circle":false},
  {"no":930,"word":"global warming","star":false,"pos":"名","meaning":"地球温暖化","example":"I studied about global warming.","circle":false},
  {"no":931,"word":"globe","star":false,"pos":"名","meaning":"地球、球体","example":"She has travelled all around the globe.","circle":true},
  {"no":932,"word":"glove","star":true,"pos":"名","meaning":"手袋","example":"I wear a coat and gloves in winter.","circle":false},
  {"no":933,"word":"glue","star":true,"pos":"名","meaning":"のり、接着剤","example":"Put some glue on the paper.","circle":true},
  {"no":934,"word":"go","star":true,"pos":"動","meaning":"行く　　※be going to do  ～しようとしている、～するつもりである\ngo into ～　～に入って行く　　go out  外出する\n【活用】 go - went - gone","example":"I went to Sannomiya on Sunday.","circle":false},
  {"no":935,"word":"goal","star":false,"pos":"名","meaning":"目標、（サッカーなどの）ゴール","example":"My goal is to be a great baseball player.","circle":false},
  {"no":936,"word":"God","star":false,"pos":"名","meaning":"神","example":"Your voice is a gift from God.","circle":false},
  {"no":937,"word":"gold","star":false,"pos":"名・形","meaning":"金（の）","example":"They found much gold in Africa.","circle":false},
  {"no":938,"word":"goldfish","star":false,"pos":"名","meaning":"金魚","example":"Goldfish are sold at Japanese summer festivals.","circle":true},
  {"no":939,"word":"golf","star":false,"pos":"名","meaning":"ゴルフ","example":"My father likes playing golf.","circle":false},
  {"no":940,"word":"good","star":true,"pos":"形","meaning":"よい、上手な　【活用】 good - better - best\n※be good at ～ ～が得意な","example":"She is a good table tennis player.","circle":false},
  {"no":941,"word":"goodbye","star":false,"pos":"名・間","meaning":"さようなら","example":"Goodbye, Mary.","circle":false},
  {"no":942,"word":"goods","star":false,"pos":"名","meaning":"商品、品物","example":"You can find many useful goods at this shop.","circle":false},
  {"no":943,"word":"gorilla","star":true,"pos":"名","meaning":"ゴリラ","example":"Gorillas live in African jungles.","circle":true},
  {"no":944,"word":"government","star":false,"pos":"名","meaning":"政府","example":"The Japanese government created a new program.","circle":false},
  {"no":945,"word":"grade","star":false,"pos":"名","meaning":"学年","example":"Now I am in the ninth grade.","circle":false},
  {"no":946,"word":"grader","star":false,"pos":"名","meaning":"～年生","example":"I am a second grader at junior high school.","circle":true},
  {"no":947,"word":"gradually","star":false,"pos":"副","meaning":"だんだんと、徐々に","example":"It is gradually getting warmer.","circle":true},
  {"no":948,"word":"graduate","star":false,"pos":"動","meaning":"卒業する","example":"We graduated from elementary school two years ago.","circle":false},
  {"no":949,"word":"graduation","star":true,"pos":"名","meaning":"卒業","example":"I want to go to university after graduation.","circle":true},
  {"no":950,"word":"gram","star":false,"pos":"名","meaning":"グラム","example":"The price of gold is about five thousand yen for one gram.","circle":false},
  {"no":951,"word":"grandchild","star":false,"pos":"名","meaning":"孫　【複数】 grandchildren","example":"She likes playing with her grandchildren.","circle":true},
  {"no":952,"word":"granddaughter","star":false,"pos":"名","meaning":"孫娘、女の孫","example":"She visited her granddaughter last week.","circle":false},
  {"no":953,"word":"grandfather","star":true,"pos":"名","meaning":"祖父、おじいさん　　※grandpa   おじいちゃん","example":"My grandfather lives in Sasayama.","circle":false},
  {"no":954,"word":"grandmother","star":true,"pos":"名","meaning":"祖母、おばあさん　　※grandma  おばあちゃん","example":"I live with my grandmother.","circle":false},
  {"no":955,"word":"grandparent","star":false,"pos":"名","meaning":"祖父、祖母、（grandparentsで）祖父母","example":"I'm going to visit my grandparents on weekend.","circle":true},
  {"no":956,"word":"grandson","star":false,"pos":"名","meaning":"孫息子、男の孫","example":"She has two grandsons.","circle":false},
  {"no":957,"word":"grape","star":true,"pos":"名","meaning":"ブドウ","example":"Grapes from Kasai taste very good.","circle":false},
  {"no":958,"word":"graph","star":false,"pos":"名","meaning":"グラフ","example":"Look at the graph on the right.","circle":false},
  {"no":959,"word":"grass","star":false,"pos":"名","meaning":"草、芝生","example":"The grass in my garden is getting greener.","circle":true},
  {"no":960,"word":"gray","star":false,"pos":"名・形","meaning":"灰色（の）","example":"My grandfather has gray hair.","circle":false},
  {"no":961,"word":"great","star":true,"pos":"形","meaning":"すてきな、すばらしい","example":"The event was great.","circle":false},
  {"no":962,"word":"greatly","star":false,"pos":"副","meaning":"大いに","example":"The world has already changed greatly.","circle":false},
  {"no":963,"word":"green","star":true,"pos":"名・形","meaning":"緑（の）","example":"How about this green cap?","circle":false},
  {"no":964,"word":"green onion","star":false,"pos":"名","meaning":"ネギ","example":"We eat noodles with green onions.","circle":true},
  {"no":965,"word":"green pepper","star":true,"pos":"名","meaning":"ピーマン","example":"I didn't like green peppers when I was a kid.","circle":true},
  {"no":966,"word":"greet","star":false,"pos":"動","meaning":"あいさつをする","example":"I try to greet everyone I meet.","circle":false},
  {"no":967,"word":"greeting","star":false,"pos":"名","meaning":"あいさつ","example":"It is important to start the day with greetings.","circle":false},
  {"no":968,"word":"grill","star":false,"pos":"動","meaning":"（網で）焼く　※grilled fish  焼き魚","example":"A Japanese breakfast usually includes a grilled fish.","circle":true},
  {"no":969,"word":"ground","star":false,"pos":"名","meaning":"地面、地上、運動場","example":"They found a big hole in the ground.","circle":false},
  {"no":970,"word":"group","star":true,"pos":"名","meaning":"グループ、集団","example":"Let's make ten groups of four people.","circle":false},
  {"no":971,"word":"grow","star":false,"pos":"動","meaning":"成長する、～を栽培する\n※grow up 成長する　　【活用】 grow - grew - grown","example":"We grow special rice for Japanese sake in Hyogo.","circle":false},
  {"no":972,"word":"guess","star":true,"pos":"動","meaning":"推測する　 　※Guess what!　何だと思う","example":"Can you guess what it is?","circle":false},
  {"no":973,"word":"guest","star":false,"pos":"名","meaning":"客、ゲスト","example":"They are guests from America.","circle":false},
  {"no":974,"word":"guide","star":false,"pos":"動・名","meaning":"（動）案内する、導く　　（名）案内人、ガイド","example":"The guide told us the history of the castle.","circle":false},
  {"no":975,"word":"guidebook","star":false,"pos":"名","meaning":"ガイドブック、案内書","example":"The guidebook says the building is over 120 years old.","circle":false},
  {"no":976,"word":"guitar","star":true,"pos":"名","meaning":"ギター","example":"I have played the guitar since I was eight.","circle":false},
  {"no":977,"word":"gum","star":false,"pos":"名","meaning":"ガム","example":"You should not chew gum in school.","circle":true},
  {"no":978,"word":"gun","star":false,"pos":"名","meaning":"銃、鉄砲","example":"When I was a child, I liked playing with a toy gun.","circle":true},
  {"no":979,"word":"gym","star":true,"pos":"名","meaning":"体育館、ジム（gymnasium の略）","example":"We will have the PE class in the gym today.","circle":false},
  {"no":980,"word":"gymnastics","star":true,"pos":"名","meaning":"体操","example":"I like watching gymnastics at the Olympics.","circle":true},
  {"no":981,"word":"habit","star":false,"pos":"名","meaning":"習慣、くせ","example":"Eating between meals is a bad habit.","circle":false},
  {"no":982,"word":"hair","star":false,"pos":"名","meaning":"髪の毛","example":"Do you know that woman with short hair?","circle":false},
  {"no":983,"word":"haircut","star":false,"pos":"名","meaning":"散髪","example":"I have a haircut once a month.","circle":true},
  {"no":984,"word":"hairstyle","star":false,"pos":"名","meaning":"髪型、ヘアスタイル","example":"That hairstyle looks good on you.","circle":true},
  {"no":985,"word":"half","star":false,"pos":"名・形","meaning":"半分（の）","example":"A half of the students in my class come to school by bike.","circle":false},
  {"no":986,"word":"hall","star":false,"pos":"名","meaning":"ホール、会館       ※city hall 市役所","example":"We went to the Akashi City Hall last week.","circle":false},
  {"no":987,"word":"Halloween","star":false,"pos":"名","meaning":"ハロウィーン","example":"Children like Halloween very much.","circle":false},
  {"no":988,"word":"hallway","star":false,"pos":"名","meaning":"廊下","example":"Go down this hallway to the gym.","circle":true},
  {"no":989,"word":"ham","star":false,"pos":"名","meaning":"ハム","example":"I usually eat ham and eggs for breakfast.","circle":false},
  {"no":990,"word":"hamburger","star":true,"pos":"名","meaning":"ハンバーガー、ハンバーグステーキ","example":"Can I have a hamburger and a cup of coffee?","circle":false},
  {"no":991,"word":"hand","star":true,"pos":"名","meaning":"手（手首から先の部分）\n※shake hands 握手をする　　on the other hand  一方では","example":"If you have questions, please raise your hand.","circle":false},
  {"no":992,"word":"handball","star":false,"pos":"名","meaning":"ハンドボール","example":"She belongs to the handball club.","circle":true},
  {"no":993,"word":"handkerchief","star":false,"pos":"名","meaning":"ハンカチ","example":"Take a handkerchief with you.","circle":true},
  {"no":994,"word":"handle","star":false,"pos":"動","meaning":"扱う、処理する","example":"It is easy to handle this machine.","circle":true},
  {"no":995,"word":"handmade","star":false,"pos":"形","meaning":"手づくりの","example":"I like handmade toys.","circle":false},
  {"no":996,"word":"handout","star":false,"pos":"名","meaning":"配布印刷物、ビラ、（教室などで配る）プリント","example":"I'll give you a handout.","circle":false},
  {"no":997,"word":"handsome","star":false,"pos":"形","meaning":"顔立ちが美しい、ハンサムな","example":"I love the actor because he is very handsome.","circle":true},
  {"no":998,"word":"hang","star":false,"pos":"動","meaning":"つるす      【活用】 hang - hung - hung","example":"We hang some pictures on the wall of our classroom.","circle":false},
  {"no":999,"word":"happen","star":false,"pos":"動","meaning":"起こる、生じる","example":"What happened?","circle":false},
  {"no":1000,"word":"happiness","star":false,"pos":"名","meaning":"幸福","example":"I want to share this happiness with other people.","circle":false}
];
