const WORDS25 = [
  {"no":2401,"word":"watch","star":true,"pos":"動・名","meaning":"①（動）見る\n②（名）腕時計","example":"①I am watching TV now.\n②This watch is a present from my father.","circle":false},
  {"no":2402,"word":"water","star":true,"pos":"名","meaning":"水","example":"You should drink a lot of water in summer.","circle":false},
  {"no":2403,"word":"watermelon","star":true,"pos":"名","meaning":"スイカ","example":"Watermelon is a popular summer fruit.","circle":true},
  {"no":2404,"word":"wave","star":false,"pos":"動・名","meaning":"①（動）手を振る\n②（名）波","example":"①The students waved to us from their bus.\n②The big waves crashed against the rocks.","circle":false},
  {"no":2405,"word":"way","star":true,"pos":"名","meaning":"①道　   ※by the way  ところで 　\n              on the way to ～　～へ行く途中で\n②方法","example":"①Can you tell me the way to the museum?\n②You can solve this problem in three ways.","circle":false},
  {"no":2406,"word":"we","star":true,"pos":"代","meaning":"私たちは（が）","example":"We had a very good time last Sunday.","circle":false},
  {"no":2407,"word":"weak","star":false,"pos":"形","meaning":"弱い、かすかな","example":"I heard a weak voice.","circle":false},
  {"no":2408,"word":"wear","star":false,"pos":"動","meaning":"身に付けている　　　【活用】 wear - wore - worn","example":"We must wear our school uniform in school.","circle":false},
  {"no":2409,"word":"weather","star":true,"pos":"名","meaning":"天気","example":"The weather will be nice next weekend.","circle":false},
  {"no":2410,"word":"website","star":false,"pos":"名","meaning":"ウェブサイト","example":"The website is useful for getting information about Hyogo.","circle":false},
  {"no":2411,"word":"wedding","star":false,"pos":"名","meaning":"結婚式","example":"My brother looked very happy at his wedding.","circle":true},
  {"no":2412,"word":"Wednesday","star":true,"pos":"名","meaning":"水曜日","example":"My father comes home early on Wednesdays.","circle":false},
  {"no":2413,"word":"week","star":false,"pos":"名","meaning":"週","example":"We are going to have an exam next week.","circle":false},
  {"no":2414,"word":"weekday","star":false,"pos":"名","meaning":"平日","example":"The city hall is open only on weekdays.","circle":true},
  {"no":2415,"word":"weekend","star":false,"pos":"名","meaning":"週末","example":"Please enjoy your weekend.","circle":false},
  {"no":2416,"word":"weight","star":false,"pos":"名","meaning":"重さ、体重、おもり","example":"What is the weight of your luggage?","circle":true},
  {"no":2417,"word":"weightlifting","star":true,"pos":"名","meaning":"ウェイトリフティング","example":"He is training hard for the Olympic weightlifting contest.","circle":true},
  {"no":2418,"word":"welcome","star":true,"pos":"動・間・形","meaning":"①（動）歓迎する、（間）ようこそ　　　※Welcome to ～　～へようこそ\n②（形）歓迎される　　　※You're welcome.  どういたしまして","example":"①Welcome to Hyogo.\n②A: Thank you for your help.  B: You're welcome.","circle":false},
  {"no":2419,"word":"well","star":true,"pos":"形・副・間","meaning":"①（形・副）うまい、うまく、上手に、健康で　\n②（間）え～と、さて、ところで","example":"①My mother cooks very well.\n②A: How was your weekend?   B: Well, it was not bad.","circle":false},
  {"no":2420,"word":"were","star":false,"pos":"動","meaning":"～であった、（～に）いた、あった （are の過去形）","example":"We were very nervous on the stage.","circle":false},
  {"no":2421,"word":"west","star":false,"pos":"名・形・副","meaning":"西（の、へ）、西方","example":"A strong wind is blowing from the west.","circle":false},
  {"no":2422,"word":"western","star":false,"pos":"形","meaning":"西の、（大文字で）西洋の","example":"I like Japanese food better than Western food.","circle":false},
  {"no":2423,"word":"wet","star":false,"pos":"形","meaning":"ぬれた、ぬれている","example":"My clothes got wet because it started to rain.","circle":true},
  {"no":2424,"word":"whale","star":false,"pos":"名","meaning":"クジラ","example":"The whale is the largest animal on earth.","circle":true},
  {"no":2425,"word":"what","star":true,"pos":"代・形","meaning":"何､何の､どんな\n※What a ～!　なんという～　What about ～?　～はどうですか　\nWhat's up?  どうしたの　What's wrong ? / What's the matter?  どうかしたの 　What time ～?　何時に～ですか  what to ～ 何を～したらよいか","example":"What did you do during the summer vacation?","circle":false},
  {"no":2426,"word":"wheel","star":false,"pos":"名","meaning":"車輪","example":"My bike's wheel is broken and I can't ride it.","circle":true},
  {"no":2427,"word":"wheelchair","star":true,"pos":"名","meaning":"車いす","example":"The players in wheelchairs played basketball very well.","circle":true},
  {"no":2428,"word":"when","star":true,"pos":"接・副","meaning":"いつ、～するとき　　※when to ～　いつ～したらよいか","example":"I feel happy when I am with my friends.","circle":false},
  {"no":2429,"word":"where","star":true,"pos":"副","meaning":"どこに（へ）　　　　※where to ～　どこに～したらよいか","example":"Where did you find my bag?","circle":false},
  {"no":2430,"word":"which","star":false,"pos":"代・形","meaning":"①どちら（の）、どれ（どの）\n②～する・・・　（名詞＋which ～）前にある人以外の名詞を修飾する【関係代名詞】","example":"①Which subject do you like the best?\n②This is the watch which my father gave me.","circle":false},
  {"no":2431,"word":"while","star":false,"pos":"接・名","meaning":"（～する）間に　　※  for a while　しばらくの間","example":"I will sing the song while you are playing the piano.","circle":false},
  {"no":2432,"word":"white","star":true,"pos":"名・形","meaning":"白（の）","example":"We have to wear white shirts and shoes for school.","circle":false},
  {"no":2433,"word":"whiteboard","star":false,"pos":"名","meaning":"ホワイトボード","example":"Please write your answer on the whiteboard.","circle":true},
  {"no":2434,"word":"who","star":true,"pos":"代","meaning":"①だれ\n②～する・・・　（名詞＋who ～）前にある人を表す名詞を修飾する【関係代名詞】","example":"①Who is he?\n②The girl who is running over there is my sister.","circle":false},
  {"no":2435,"word":"whole","star":false,"pos":"形","meaning":"全体の、すべての","example":"I am the happiest girl in the whole world.","circle":false},
  {"no":2436,"word":"whose","star":false,"pos":"代","meaning":"だれの","example":"Whose bag is this?   There's no name on it.","circle":false},
  {"no":2437,"word":"why","star":true,"pos":"副","meaning":"なぜ\n※Why don't you ～?  ～しませんか　Why not? ええ、もちろん","example":"Why don’t you have lunch with us?","circle":false},
  {"no":2438,"word":"wide","star":false,"pos":"形・副","meaning":"幅の広い、幅が～ある","example":"The river is about 30 meters wide.","circle":false},
  {"no":2439,"word":"wife","star":false,"pos":"名","meaning":"妻","example":"He said that he met his wife in high school.","circle":false},
  {"no":2440,"word":"Wi-Fi","star":false,"pos":"名","meaning":"ワイファイ","example":"You can use Wi-Fi here.","circle":true},
  {"no":2441,"word":"wild","star":false,"pos":"名・形","meaning":"野生（の）","example":"These are pictures of wild animals in Australia.","circle":false},
  {"no":2442,"word":"will","star":false,"pos":"助","meaning":"～でしょう、～するつもりである\n※Will you ～?　～してくれませんか","example":"I will never forget about this game.","circle":false},
  {"no":2443,"word":"win","star":false,"pos":"動","meaning":"勝つ　　　　　【活用】 win - won - won","example":"We practiced very hard to win the last game.","circle":false},
  {"no":2444,"word":"wind","star":false,"pos":"名","meaning":"風","example":"We can use the wind to make electricity.","circle":false},
  {"no":2445,"word":"window","star":true,"pos":"名","meaning":"窓","example":"Could you open the window?","circle":false},
  {"no":2446,"word":"windy","star":false,"pos":"形","meaning":"風の強い","example":"It's windy today.","circle":false},
  {"no":2447,"word":"wing","star":false,"pos":"名","meaning":"翼","example":"That bird has big wings.","circle":false},
  {"no":2448,"word":"winner","star":false,"pos":"名","meaning":"勝つ（勝った）人、勝利者","example":"I was a winner at the game.","circle":false},
  {"no":2449,"word":"winter","star":true,"pos":"名","meaning":"冬","example":"I like winter because I can ski.","circle":false},
  {"no":2450,"word":"wipe","star":false,"pos":"動","meaning":"ふく、ぬぐう","example":"Will you wipe the table?","circle":true},
  {"no":2451,"word":"wisdom","star":false,"pos":"名","meaning":"賢明（さ）、知恵","example":"I should learn a lot of wisdom from my grandparents.","circle":true},
  {"no":2452,"word":"wish","star":false,"pos":"動・名","meaning":"（動）願う　　（名）願い　　　　※make a wish  願いごとをする","example":"We make a wish on New Year's Day.","circle":false},
  {"no":2453,"word":"with","star":true,"pos":"前","meaning":"①～といっしょに\n②～のある、～を持った\n③～を使って","example":"①I like to play with children.\n②The woman with short hair is our P.E. teacher.\n③You can make origami with this paper.","circle":false},
  {"no":2454,"word":"within","star":false,"pos":"前","meaning":"～以内で","example":"Please finish writing within five minutes.","circle":false},
  {"no":2455,"word":"without","star":false,"pos":"前","meaning":"～なしで","example":"We cannot live without help from other people.","circle":false},
  {"no":2456,"word":"woman","star":false,"pos":"名","meaning":"（大人の）女性      【複数】 women","example":"That woman is my homeroom teacher.","circle":false},
  {"no":2457,"word":"wonder","star":false,"pos":"動","meaning":"～かなあと思う、～かどうか知りたいと思う","example":"I wonder why she can't come.","circle":false},
  {"no":2458,"word":"wonderful","star":true,"pos":"形","meaning":"すばらしい、とてもすてきな","example":"The wonderful time passed quickly.","circle":false},
  {"no":2459,"word":"wood","star":false,"pos":"名","meaning":"（切った）木、木材","example":"This floor is made of wood.","circle":false},
  {"no":2460,"word":"wooden","star":false,"pos":"形","meaning":"木でできた、木製の","example":"Wooden houses are popular in Japan.","circle":true},
  {"no":2461,"word":"word","star":false,"pos":"名","meaning":"ことば、単語","example":"The word “heiwa” means “peace” in English.","circle":false},
  {"no":2462,"word":"work","star":false,"pos":"動・名","meaning":"①（動）働く、勉強する　（名）仕事、勉強、作品　　※at work 仕事に出かけていて\n②（動）（機械などが）機能する、（計画などが）うまくいく","example":"①I want to work abroad in the future.\n②Our plan worked very well.","circle":false},
  {"no":2463,"word":"workbook","star":false,"pos":"名","meaning":"ワークブック","example":"Please bring your workbook to every lesson.","circle":true},
  {"no":2464,"word":"worker","star":false,"pos":"名","meaning":"労働者    ※office worker  会社員","example":"My father is an office worker.","circle":false},
  {"no":2465,"word":"world","star":true,"pos":"名","meaning":"世界　　※all over the world 世界中","example":"The book is read all over the world.","circle":false},
  {"no":2466,"word":"World Heritage (Site)","star":false,"pos":"名","meaning":"世界遺産","example":"Himeji Castle is a World Heritage Site.","circle":false},
  {"no":2467,"word":"worldwide","star":false,"pos":"副","meaning":"世界中で（に）","example":"The song is loved worldwide.","circle":true},
  {"no":2468,"word":"worried","star":false,"pos":"形","meaning":"心配した、不安な","example":"I am worried about the test next week.","circle":false},
  {"no":2469,"word":"worry","star":false,"pos":"動","meaning":"心配する","example":"Don't worry.","circle":false},
  {"no":2470,"word":"worse","star":false,"pos":"形","meaning":"もっと悪い（下手な、ひどい）　（bad の比較級）","example":"The weather will be worse tomorrow.","circle":false},
  {"no":2471,"word":"worst","star":false,"pos":"形","meaning":"最も悪い（下手な、ひどい） （badの最上級）","example":"It was the worst typhoon we've ever had.","circle":false},
  {"no":2472,"word":"would","star":true,"pos":"助","meaning":"willの過去形　　※would like to ～　～したいと思う\nWould you ～?　～してくださいませんか\nWould you like ～?　～はいかがですか　\nWould you like to ～?　～したいですか","example":"Would you like some coffee?","circle":false},
  {"no":2473,"word":"wow","star":false,"pos":"間","meaning":"うわー！わあ！（驚き・喜びを表す）","example":"Wow!  That's great!","circle":false},
  {"no":2474,"word":"wrap","star":false,"pos":"動","meaning":"包む、包装する","example":"Could you wrap it for me?","circle":false},
  {"no":2475,"word":"wrestling","star":true,"pos":"名","meaning":"レスリング","example":"She won a gold medal in wrestling.","circle":true},
  {"no":2476,"word":"wrist","star":false,"pos":"名","meaning":"手首","example":"He always wears a silver watch on his wrist.","circle":true},
  {"no":2477,"word":"write","star":true,"pos":"動","meaning":"書く　　【活用】 write - wrote - written","example":"We write our wishes on small pieces of paper.","circle":false},
  {"no":2478,"word":"writer","star":false,"pos":"名","meaning":"作家、著者","example":"Haruki Murakami is a famous writer around the world.","circle":false},
  {"no":2479,"word":"writing","star":false,"pos":"名","meaning":"書くこと、書かれた文字、筆跡","example":"His writing is very good.","circle":false},
  {"no":2480,"word":"wrong","star":false,"pos":"形","meaning":"悪い、調子が悪い、間違っている     ※What's wrong ? どうしたの","example":"I was wrong.  You are right.","circle":false},
  {"no":2481,"word":"yacht","star":false,"pos":"名","meaning":"ヨット","example":"The man crossed the sea in a yacht.","circle":true},
  {"no":2482,"word":"yard","star":false,"pos":"名","meaning":"（家などの周りの）庭、中庭、裏庭","example":"My mother grows some vegetables in our yard.","circle":true},
  {"no":2483,"word":"yawn","star":false,"pos":"動","meaning":"あくびをする","example":"People yawn when they are bored.","circle":true},
  {"no":2484,"word":"yeah","star":false,"pos":"副","meaning":"ああ、うん、そう","example":"A: Do you like sushi?  B: Yeah, I love sushi!","circle":true},
  {"no":2485,"word":"year","star":true,"pos":"名","meaning":"年、１年　　　　　※ ～ year(s) later  ～年後、　～ year(s) old ～歳","example":"She is thirty-six years old.","circle":false},
  {"no":2486,"word":"yellow","star":true,"pos":"名・形","meaning":"黄色（の）","example":"The red bag is smaller than the yellow bag.","circle":false},
  {"no":2487,"word":"yen","star":true,"pos":"名","meaning":"円（日本の通貨単位）","example":"A: How much is this?  B: It's two thousand yen.","circle":false},
  {"no":2488,"word":"yes","star":true,"pos":"副","meaning":"はい、そうです","example":"A: Do you like dogs?  B: Yes, I do.","circle":false},
  {"no":2489,"word":"yesterday","star":false,"pos":"副・名","meaning":"昨日（は）","example":"I played basketball yesterday.","circle":false},
  {"no":2490,"word":"yet","star":false,"pos":"副","meaning":"①（否定文で）まだ～（しない）　※not ～ yet　まだ～していない\n②（肯定の疑問文で）もう～したか","example":"①I haven’t finished my homework yet.\n②Have you finished your homework yet?","circle":false},
  {"no":2491,"word":"yogurt","star":false,"pos":"名","meaning":"ヨーグルト","example":"My mother makes yogurt from milk.","circle":true},
  {"no":2492,"word":"you","star":true,"pos":"代","meaning":"あなた、あなたたち","example":"Have you ever been to the U.S.?","circle":false},
  {"no":2493,"word":"young","star":false,"pos":"形","meaning":"若い、幼い","example":"When I was young, I lived in Amagasaki.","circle":false},
  {"no":2494,"word":"your","star":true,"pos":"代","meaning":"あなたの、あなたたちの","example":"Your computer is newer than mine.","circle":false},
  {"no":2495,"word":"yours","star":false,"pos":"代","meaning":"あなたのもの、あなたたちのもの","example":"I want a bag like yours.","circle":false},
  {"no":2496,"word":"yourself","star":false,"pos":"代","meaning":"あなた自身を（で、に、が）　　※by yourself 　自分で、あなた自身で","example":"You can do it by yourself.","circle":false},
  {"no":2497,"word":"yummy","star":false,"pos":"形","meaning":"おいしい","example":"This soup is really yummy.","circle":true},
  {"no":2498,"word":"zebra","star":false,"pos":"名","meaning":"シマウマ","example":"You can see some zebras at the zoo.","circle":true},
  {"no":2499,"word":"zero","star":true,"pos":"名・形","meaning":"０、ゼロ（の）","example":"In winter, the temperature often falls below zero.","circle":false},
  {"no":2500,"word":"zoo","star":true,"pos":"名","meaning":"動物園","example":"I went to Oji zoo yesterday.","circle":false}
];
