const WORDS04 = [
  {"no":301,"word":"butterfly","star":false,"pos":"名","meaning":"チョウ","example":"You can see this butterfly only in Japan.","circle":true},
  {"no":302,"word":"button","star":false,"pos":"名","meaning":"（衣服の、機械などの）ボタン","example":"Press the button to move that machine.","circle":false},
  {"no":303,"word":"buy","star":true,"pos":"動","meaning":"買う   【活用】 buy - bought - bought","example":"I am going to buy a new computer.","circle":false},
  {"no":304,"word":"by","star":true,"pos":"前","meaning":"①（方法・手段）～によって　\n②（時間）～までに　\n③（場所）～のそばに","example":"①I will go there by train.\n②You must come home by six o'clock.\n③My house is by the river.","circle":false},
  {"no":305,"word":"bye","star":false,"pos":"間","meaning":"さようなら、バイバイ","example":"I will see you tomorrow.  Bye!","circle":true},
  {"no":306,"word":"cabbage","star":true,"pos":"名","meaning":"キャベツ","example":"I cut the cabbage and made a healthy salad.","circle":true},
  {"no":307,"word":"café","star":false,"pos":"名","meaning":"カフェ、喫茶店","example":"My favorite café has delicious sweets and coffee.","circle":true},
  {"no":308,"word":"cafeteria","star":false,"pos":"名","meaning":"カフェテリア、食堂","example":"Both students and teachers have lunch in the cafeteria.","circle":false},
  {"no":309,"word":"cage","star":false,"pos":"名","meaning":"かご、おり","example":"Our cats go into their cage at night.","circle":true},
  {"no":310,"word":"cake","star":true,"pos":"名","meaning":"ケーキ","example":"I made a cake with my sister.","circle":false},
  {"no":311,"word":"calendar","star":true,"pos":"名","meaning":"カレンダー、暦","example":"This calendar has a lot of pictures.","circle":false},
  {"no":312,"word":"call","star":false,"pos":"動","meaning":"①呼ぶ　\n②電話をかける　　　※call (～) back  電話をかけなおす","example":"①Please call me Ken.\n②I will call you tomorrow.","circle":false},
  {"no":313,"word":"calligraphy","star":true,"pos":"名","meaning":"書道","example":"I will show Japanese calligraphy to my American friend.","circle":false},
  {"no":314,"word":"calm","star":false,"pos":"形","meaning":"穏やかな、静かな","example":"The sea is usually calm during summer.","circle":true},
  {"no":315,"word":"camera","star":false,"pos":"名","meaning":"カメラ","example":"That's a nice camera!","circle":false},
  {"no":316,"word":"camp","star":true,"pos":"動・名","meaning":"キャンプ（する）　　※go camping  キャンプに行く","example":"He often camps to take pictures of wild animals.","circle":false},
  {"no":317,"word":"campaign","star":false,"pos":"名","meaning":"運動、キャンペーン","example":"Many people joined the campaign against the war.","circle":true},
  {"no":318,"word":"can","star":true,"pos":"助・名","meaning":"①～することができる　　※Can I ～?　～してもよいですか\nCan you ～?  ～してもらえますか\n②缶","example":"①He can play basketball very well. \n②We collect paper, bottles, cans, and other things.","circle":false},
  {"no":319,"word":"Canada","star":false,"pos":"名","meaning":"カナダ","example":"A: Are you from Canada?  B: Yes, I am.","circle":false},
  {"no":320,"word":"cancel","star":false,"pos":"動","meaning":"～を取り消す、中止する","example":"I would like to cancel my order.","circle":true},
  {"no":321,"word":"cancer","star":false,"pos":"名","meaning":"（病気の）がん","example":"Cancer is a very serious disease.","circle":true},
  {"no":322,"word":"candle","star":false,"pos":"名","meaning":"ろうそく","example":"On January 17, people light many candles in Hyogo.","circle":false},
  {"no":323,"word":"candy","star":false,"pos":"名","meaning":"キャンディ","example":"I sometimes buy some candies for my little sister.","circle":false},
  {"no":324,"word":"canoe","star":true,"pos":"名","meaning":"カヌー","example":"I went down the river by canoe.","circle":true},
  {"no":325,"word":"cap","star":true,"pos":"名","meaning":"（ふちのない）帽子、（びんの）ふた","example":"A: Where's my cap?  B: It's on the table.","circle":false},
  {"no":326,"word":"capital","star":false,"pos":"名","meaning":"首都","example":"Tokyo is the capital of Japan.","circle":false},
  {"no":327,"word":"capital letter","star":false,"pos":"名","meaning":"大文字","example":"You must start someone's name with a capital letter.","circle":false},
  {"no":328,"word":"captain","star":false,"pos":"名","meaning":"キャプテン","example":"He is the captain of our team.","circle":false},
  {"no":329,"word":"car","star":true,"pos":"名","meaning":"車、乗用車","example":"I like Japanese cars.","circle":false},
  {"no":330,"word":"card","star":true,"pos":"名","meaning":"カード、トランプ　　※play cards  トランプをする","example":"I will send a Christmas card to my grandmother.","circle":false},
  {"no":331,"word":"cardboard","star":false,"pos":"名","meaning":"段ボール","example":"The albums are kept in this cardboard box.","circle":true},
  {"no":332,"word":"care","star":false,"pos":"動・名","meaning":"世話（する）、注意（する）　\n※take care of  ～　～の世話をする　  Take care.　気をつけて","example":"He took care of his two sisters.","circle":false},
  {"no":333,"word":"career","star":false,"pos":"名","meaning":"職業、経歴　  ※career experience　職業体験学習","example":"I want to work in a shop for career experience.","circle":false},
  {"no":334,"word":"careful","star":false,"pos":"形","meaning":"注意深い、慎重な","example":"Be careful.","circle":false},
  {"no":335,"word":"carefully","star":false,"pos":"副","meaning":"注意深く","example":"You have to read the questions carefully.","circle":false},
  {"no":336,"word":"carpenter","star":false,"pos":"名","meaning":"大工","example":"Carpenters make houses.","circle":false},
  {"no":337,"word":"carpet","star":false,"pos":"名","meaning":"じゅうたん、カーペット","example":"The actor is slowly walking down the red carpet.","circle":true},
  {"no":338,"word":"carrot","star":true,"pos":"名","meaning":"ニンジン","example":"I could not eat carrots when I was small.","circle":false},
  {"no":339,"word":"carry","star":false,"pos":"動","meaning":"持っている、持ち歩く、運ぶ　　 【活用】 carry - carried - carried","example":"It is very hard to carry a large box by yourself.","circle":false},
  {"no":340,"word":"cartoon","star":false,"pos":"名","meaning":"漫画","example":"I like drawing cartoons.","circle":false},
  {"no":341,"word":"cartoonist","star":false,"pos":"名","meaning":"漫画家","example":"I want to be a cartoonist in the future.","circle":false},
  {"no":342,"word":"case","star":false,"pos":"名","meaning":"①ケース、箱　\n②場合","example":"①Put your camera into that black case.\n②In this case, you should think in a different way.","circle":false},
  {"no":343,"word":"castle","star":true,"pos":"名","meaning":"城","example":"Have you visited Himeji Castle before?","circle":false},
  {"no":344,"word":"cat","star":true,"pos":"名","meaning":"ネコ","example":"Now cats are very popular in Japan.","circle":false},
  {"no":345,"word":"catch","star":false,"pos":"動","meaning":"捕まえる     【活用】 catch - caught - caught","example":"I must catch him to talk about the plan.","circle":false},
  {"no":346,"word":"cause","star":false,"pos":"動・名","meaning":"（動）～を引き起こす、～の原因となる　　（名）原因","example":"Heavy rain was the cause of the terrible car accident.","circle":false},
  {"no":347,"word":"CD","star":false,"pos":"名","meaning":"compact diskの略","example":"What a lot of CDs!","circle":false},
  {"no":348,"word":"ceiling","star":false,"pos":"名","meaning":"天井","example":"The ceiling is so high that I cannot clean it.","circle":true},
  {"no":349,"word":"celebrate","star":false,"pos":"動","meaning":"祝う","example":"Let's celebrate her birthday.","circle":false},
  {"no":350,"word":"cellphone","star":false,"pos":"名","meaning":"携帯電話（mobile phone とも言う）","example":"Cellphones are very convenient.","circle":false},
  {"no":351,"word":"cent","star":false,"pos":"名","meaning":"セント（アメリカ・オーストラリア・カナダなどの通貨単位）","example":"It is two dollars sixty-five cents.","circle":false},
  {"no":352,"word":"center","star":false,"pos":"名","meaning":"中心、真ん中、センター（施設）","example":"I live in the center of Amagasaki city.","circle":false},
  {"no":353,"word":"centimeter","star":false,"pos":"名","meaning":"センチメートル","example":"I am 155 centimeters tall.","circle":false},
  {"no":354,"word":"central","star":false,"pos":"形","meaning":"中央の","example":"Many train lines start from the central station.","circle":true},
  {"no":355,"word":"century","star":false,"pos":"名","meaning":"世紀、１００年","example":"He is one of the best singers in the 20th century.","circle":false},
  {"no":356,"word":"ceremony","star":false,"pos":"名","meaning":"式、式典","example":"We practiced the songs for the graduation ceremony.","circle":true},
  {"no":357,"word":"certainly","star":false,"pos":"副","meaning":"確かに、（返事で）承知しました、もちろん","example":"A: Can I have some water?  B: Certainly.","circle":true},
  {"no":358,"word":"chain","star":false,"pos":"名","meaning":"くさり","example":"I use a chain to lock my bike.","circle":false},
  {"no":359,"word":"chair","star":true,"pos":"名","meaning":"いす","example":"Please sit on this chair.","circle":false},
  {"no":360,"word":"chalk","star":false,"pos":"名","meaning":"チョーク","example":"We have four colors of chalk here.","circle":true},
  {"no":361,"word":"challenge","star":false,"pos":"動・名","meaning":"挑戦（する）","example":"Studying in America will be a big challenge for me.","circle":false},
  {"no":362,"word":"champion","star":false,"pos":"名","meaning":"優勝者、チャンピオン","example":"She practiced very hard to become a champion.","circle":false},
  {"no":363,"word":"championship","star":false,"pos":"名","meaning":"選手権（大会）","example":"Our team won the championship.","circle":false},
  {"no":364,"word":"chance","star":false,"pos":"名","meaning":"機会、チャンス","example":"I missed the chance to see him.","circle":false},
  {"no":365,"word":"change","star":false,"pos":"動・名","meaning":"①（動）変わる、変える　（名）変化\n②（名）つり銭","example":"①My life changed after I met him. \n②Your change is fifty yen.","circle":false},
  {"no":366,"word":"character","star":false,"pos":"名","meaning":"①（小説・劇などの）登場人物　\n②（人の）性格、（物の）特色","example":"①There are four characters in this story.\n②Every person has a different character.","circle":false},
  {"no":367,"word":"charge","star":false,"pos":"動","meaning":"充電する","example":"I have to charge my cellphone.","circle":false},
  {"no":368,"word":"charity","star":false,"pos":"名","meaning":"慈善、チャリティー","example":"We can send the money to a charity group.","circle":false},
  {"no":369,"word":"chart","star":false,"pos":"名","meaning":"図表","example":"What can you learn from the chart?","circle":false},
  {"no":370,"word":"chat","star":false,"pos":"動・名","meaning":"おしゃべりをする、おしゃべり","example":"We enjoyed chatting for about an hour.","circle":true},
  {"no":371,"word":"cheap","star":false,"pos":"形","meaning":"安価な、安い","example":"The dress was cheap.","circle":false},
  {"no":372,"word":"check","star":true,"pos":"動","meaning":"照合する、確認する　　※check out　調べる","example":"You should check what is in your bag again.","circle":false},
  {"no":373,"word":"cheek","star":false,"pos":"名","meaning":"ほほ","example":"Tears fell down her cheeks.","circle":true},
  {"no":374,"word":"cheer","star":false,"pos":"動","meaning":"元気づける、声援する     ※cheer (～) up   ～を元気づける","example":"The news cheered her up.","circle":false},
  {"no":375,"word":"cheerful","star":false,"pos":"形","meaning":"明るい、陽気な","example":"My mother is very cheerful.","circle":false},
  {"no":376,"word":"cheerfully","star":false,"pos":"副","meaning":"明るく、元気よく","example":"The teacher always talks to us cheerfully.","circle":false},
  {"no":377,"word":"cheese","star":true,"pos":"名","meaning":"チーズ","example":"Please give me some cheese.","circle":false},
  {"no":378,"word":"chef","star":false,"pos":"名","meaning":"（熟練した）コック、料理長","example":"He is practicing cooking every day to be a good chef.","circle":false},
  {"no":379,"word":"chemical","star":false,"pos":"名・形","meaning":"（名）化学物質　　（形）化学の","example":"My father doesn't use any chemicals on his farm.","circle":true},
  {"no":380,"word":"cherry","star":true,"pos":"名","meaning":"サクラの木、サクランボ","example":"Cherries are my favorite fruit.","circle":true},
  {"no":381,"word":"cherry blossom","star":false,"pos":"名","meaning":"サクラの花","example":"The cherry blossoms at Shukugawa Park are beautiful.","circle":false},
  {"no":382,"word":"cherry tree","star":false,"pos":"名","meaning":"サクラの木","example":"In April, people have parties under cherry trees.","circle":false},
  {"no":383,"word":"chess","star":false,"pos":"名","meaning":"チェス","example":"It is difficult for me to learn the rules of chess.","circle":true},
  {"no":384,"word":"chest","star":false,"pos":"名","meaning":"胸","example":"Try to throw the ball at your partner's chest.","circle":true},
  {"no":385,"word":"chew","star":false,"pos":"動","meaning":"（繰り返し）かむ","example":"You should chew your food a lot when you eat.","circle":true},
  {"no":386,"word":"chicken","star":true,"pos":"名","meaning":"鶏肉","example":"Today I will use chicken to make this soup.","circle":false},
  {"no":387,"word":"child","star":false,"pos":"名","meaning":"子ども　　【複数】 children","example":"How many children do you have?","circle":false},
  {"no":388,"word":"childhood","star":false,"pos":"名","meaning":"子どもの頃","example":"The singer lived in Hyogo during her childhood.","circle":true},
  {"no":389,"word":"chilly","star":false,"pos":"形","meaning":"寒くて身ぶるいするような","example":"It is a little chilly this morning.","circle":true},
  {"no":390,"word":"chimpanzee","star":false,"pos":"名","meaning":"チンパンジー","example":"Chimpanzees can learn things quickly.","circle":true},
  {"no":391,"word":"chin","star":false,"pos":"名","meaning":"あご","example":"He touches his chin when he thinks.","circle":true},
  {"no":392,"word":"China","star":false,"pos":"名","meaning":"中国","example":"You know a lot about China.","circle":false},
  {"no":393,"word":"Chinese","star":false,"pos":"名・形","meaning":"中国の、中国人（の）、中国語（の）","example":"She speaks Chinese well.","circle":false},
  {"no":394,"word":"chip","star":false,"pos":"名","meaning":"（野菜などの）薄切り、（アメリカで）ポテトチップス","example":"My mother cut the potatoes and made chips.","circle":true},
  {"no":395,"word":"chocolate","star":true,"pos":"名","meaning":"チョコレート","example":"I like chocolate very much.","circle":false},
  {"no":396,"word":"choice","star":false,"pos":"名","meaning":"選ぶこと、選択　  ※make a choice　選択する、選ぶ","example":"You have a lot of choices for your future.","circle":false},
  {"no":397,"word":"choose","star":false,"pos":"動","meaning":"選ぶ　  　【活用】 choose - chose - chosen","example":"Students can choose their lunches.","circle":false},
  {"no":398,"word":"chopstick","star":false,"pos":"名","meaning":"箸","example":"Chopsticks are used in Japan and some Asian countries.","circle":false},
  {"no":399,"word":"chorus","star":false,"pos":"名","meaning":"合唱団（部）","example":"I was a member of the chorus when I was a student.","circle":false},
  {"no":400,"word":"chorus contest","star":false,"pos":"名","meaning":"合唱コンクール","example":"We are practicing hard to win the chorus contest.","circle":false}
];
