const WORDS02 = [
  {"no":101,"word":"appreciate","star":false,"pos":"動","meaning":"感謝する","example":"I appreciate your kindness.","circle":true},
  {"no":102,"word":"approach","star":false,"pos":"動","meaning":"近づく","example":"A strong typhoon is approaching.","circle":true},
  {"no":103,"word":"April","star":true,"pos":"名","meaning":"４月","example":"In April, we can see many flowers.","circle":false},
  {"no":104,"word":"apron","star":false,"pos":"名","meaning":"エプロン","example":"When I cook, I always wear an apron.","circle":true},
  {"no":105,"word":"aquarium","star":true,"pos":"名","meaning":"水族館","example":"You can see a good dolphin show at the aquarium.","circle":true},
  {"no":106,"word":"Arabic","star":false,"pos":"名・形","meaning":"アラブの、アラブ人（の）、アラブ語（の）","example":"Arabic is spoken in West Asia and North Africa.","circle":true},
  {"no":107,"word":"archery","star":true,"pos":"名","meaning":"アーチェリー　　※Japanese archery  弓道","example":"I am a member of the Japanese archery club.","circle":true},
  {"no":108,"word":"architect","star":false,"pos":"名","meaning":"建築家","example":"My dream is to be an architect.","circle":false},
  {"no":109,"word":"are","star":true,"pos":"動","meaning":"～である、（～に）いる、ある （主語が we, you, they などの複数形の時の現在形） \n※are ～ing  ～している、しようとしている　\n【活用】 are - were - been","example":"We are junior high school students.","circle":false},
  {"no":110,"word":"area","star":false,"pos":"名","meaning":"地域、地方","example":"I will show you the shopping area of my town.","circle":false},
  {"no":111,"word":"argument","star":false,"pos":"名","meaning":"議論、口論","example":"I sometimes have arguments with my parents.","circle":true},
  {"no":112,"word":"arm","star":false,"pos":"名","meaning":"腕","example":"I broke my right arm when I was playing basketball.","circle":false},
  {"no":113,"word":"around","star":false,"pos":"前・副","meaning":"①（前）～のまわりに（まわって）  　※around the world 　世界中\n②（副）～ごろ","example":"①Please sit around the table.\n②I arrived there around seven o'clock.","circle":false},
  {"no":114,"word":"arrest","star":false,"pos":"動","meaning":"逮捕する","example":"The man was arrested for stealing the money.","circle":true},
  {"no":115,"word":"arrival","star":false,"pos":"名","meaning":"到着","example":"The arrival time of Flight No.771 is 10:30.","circle":false},
  {"no":116,"word":"arrive","star":false,"pos":"動","meaning":"到着する    ※arrive at ～ ～に到着する","example":"Will she arrive in time?","circle":false},
  {"no":117,"word":"art","star":true,"pos":"名","meaning":"美術","example":"I am a member of the art club.","circle":false},
  {"no":118,"word":"article","star":false,"pos":"名","meaning":"（新聞や雑誌の）記事","example":"The newspaper article was interesting.","circle":true},
  {"no":119,"word":"artist","star":true,"pos":"名","meaning":"芸術家","example":"This picture was painted by a famous artist.","circle":false},
  {"no":120,"word":"as","star":false,"pos":"前・接・副","meaning":"①（接）～するとき\n ②（接）～なので\n ③（接）～するように\n ④（接・副）as ～ as … 　…と同じくらい～\n ⑤（前）～として","example":"①As I opened the door, the cat came out.\n②As I feel sick, I will not go out today.\n③As you know, we will have tests tomorrow.\n④He is as tall as his father.\n⑤He worked very hard as a scientist.","circle":false},
  {"no":121,"word":"Asia","star":false,"pos":"名","meaning":"アジア","example":"Japan is a country in Asia.","circle":false},
  {"no":122,"word":"Asian","star":false,"pos":"名・形","meaning":"アジアの、アジア人（の）","example":"Many people from Asian countries visit Japan every year.","circle":false},
  {"no":123,"word":"ask","star":false,"pos":"動","meaning":"たずねる、求める　　　※ask for ～　～を求める","example":"Please ask me anything.","circle":false},
  {"no":124,"word":"asleep","star":false,"pos":"形","meaning":"眠って　　 ※fall asleep 寝入る","example":"I fell asleep while I was watching TV.","circle":true},
  {"no":125,"word":"assembly","star":false,"pos":"名","meaning":"集会","example":"We have a school assembly every month.","circle":true},
  {"no":126,"word":"assistant","star":false,"pos":"名","meaning":"店員、助手","example":"My sister works as a shop assistant.","circle":false},
  {"no":127,"word":"astronaut","star":true,"pos":"名","meaning":"宇宙飛行士","example":"He is a famous astronaut in Japan.","circle":false},
  {"no":128,"word":"at","star":true,"pos":"前","meaning":"①（場所・時間の一点）　～に、～で\n②～に（向かって）","example":"①I will see you at the station.\n②Look at me.","circle":false},
  {"no":129,"word":"athlete","star":false,"pos":"名","meaning":"運動選手、アスリート","example":"He is one of my favorite athletes.","circle":false},
  {"no":130,"word":"atomic","star":false,"pos":"形","meaning":"原子（力）の","example":"In science class, we learned about atomic power.","circle":true},
  {"no":131,"word":"atomic bomb","star":false,"pos":"名","meaning":"原子爆弾","example":"Two atomic bombs were dropped on Japan.","circle":true},
  {"no":132,"word":"attach","star":false,"pos":"動","meaning":"付ける","example":"Please attach the pictures to the message.","circle":true},
  {"no":133,"word":"attack","star":false,"pos":"動","meaning":"攻撃する","example":"In this game, you can attack other people anytime.","circle":false},
  {"no":134,"word":"attend","star":false,"pos":"動","meaning":"出席する、参加する","example":"I attended the club meeting.","circle":false},
  {"no":135,"word":"attention","star":false,"pos":"名","meaning":"注意、注目     ※pay attention to ～ ～に注意を払う","example":"May I have your attention, please?","circle":false},
  {"no":136,"word":"attract","star":false,"pos":"動","meaning":"（注意、興味など）を引きつける","example":"The singer's beautiful voice attracted us.","circle":false},
  {"no":137,"word":"attraction","star":false,"pos":"名","meaning":"魅力あるもの、アトラクション","example":"The panda is the main attraction at the zoo.","circle":true},
  {"no":138,"word":"attractive","star":false,"pos":"形","meaning":"魅力的な、人を引きつける","example":"The singer is very attractive.","circle":true},
  {"no":139,"word":"audience","star":false,"pos":"名","meaning":"聴衆、観客","example":"You should look at the audience when you speak.","circle":false},
  {"no":140,"word":"August","star":true,"pos":"名","meaning":"８月","example":"The war ended on August 15, 1945.","circle":false},
  {"no":141,"word":"aunt","star":false,"pos":"名","meaning":"おば（父母の姉妹）","example":"I visited my aunt yesterday.","circle":false},
  {"no":142,"word":"Australia","star":false,"pos":"名","meaning":"オーストラリア","example":"He will go to Australia this summer.","circle":false},
  {"no":143,"word":"Australian","star":false,"pos":"名・形","meaning":"オーストラリアの、オーストラリア人（の）","example":"I have some Australian friends.","circle":false},
  {"no":144,"word":"author","star":false,"pos":"名","meaning":"作者、作家","example":"What is the author's message?","circle":true},
  {"no":145,"word":"autumn","star":true,"pos":"名","meaning":"秋","example":"You can eat delicious fruits in autumn.","circle":false},
  {"no":146,"word":"available","star":false,"pos":"形","meaning":"利用できる","example":"Computers are available in the library.","circle":true},
  {"no":147,"word":"average","star":false,"pos":"名・形","meaning":"平均（の）","example":"The average score on the test was 65.","circle":false},
  {"no":148,"word":"avocado","star":false,"pos":"名","meaning":"アボカド","example":"I like eating avocados with mayonnaise.","circle":true},
  {"no":149,"word":"award","star":false,"pos":"名","meaning":"賞、賞品","example":"I got an award for my English essay.","circle":true},
  {"no":150,"word":"away","star":false,"pos":"副","meaning":"離れて、遠くに　　　        ※far away 遠く離れて","example":"My house is far away from here.","circle":false},
  {"no":151,"word":"awesome","star":false,"pos":"形","meaning":"すごい、すばらしい、最高の","example":"The view from the top of the mountain is awesome.","circle":true},
  {"no":152,"word":"baby","star":false,"pos":"名","meaning":"赤ちゃん                        ※have a baby  赤ちゃんが生まれる","example":"My cousin will have a baby next month.","circle":false},
  {"no":153,"word":"back","star":false,"pos":"副・名","meaning":"①（副）後ろへ、帰って　　         ※be back  戻る\n②（名）後ろ、背中","example":"①I will be back soon.\n②She was carrying a baby on her back.","circle":false},
  {"no":154,"word":"backpack","star":false,"pos":"名","meaning":"リュックサック、バックパック","example":"I take a backpack when I go hiking.","circle":true},
  {"no":155,"word":"bacon","star":false,"pos":"名","meaning":"ベーコン","example":"I ate bacon for breakfast this morning.","circle":true},
  {"no":156,"word":"bad","star":false,"pos":"形","meaning":"悪い　　　※That's too bad. お気の毒に\n【活用】 bad - worse - worst","example":"That's bad news.","circle":false},
  {"no":157,"word":"badminton","star":true,"pos":"名","meaning":"バドミントン","example":"I started playing badminton when I was ten years old.","circle":false},
  {"no":158,"word":"bag","star":true,"pos":"名","meaning":"かばん、袋","example":"I need a big bag.","circle":false},
  {"no":159,"word":"bake","star":false,"pos":"動","meaning":"（オーブンで）焼く","example":"My mother bakes a birthday cake for me every year.","circle":true},
  {"no":160,"word":"bakery","star":false,"pos":"名","meaning":"パン屋","example":"There is a good bakery next to my house.","circle":false},
  {"no":161,"word":"balance","star":false,"pos":"名","meaning":"釣り合い、バランス","example":"The boy couldn't keep his balance on his new bicycle.","circle":false},
  {"no":162,"word":"balcony","star":false,"pos":"名","meaning":"バルコニー、ベランダ","example":"I grow some plants on my balcony.","circle":true},
  {"no":163,"word":"ball","star":true,"pos":"名","meaning":"ボール、球","example":"Try to pass the ball quickly to the next person.","circle":false},
  {"no":164,"word":"balloon","star":false,"pos":"名","meaning":"風船","example":"Children like playing with balloons.","circle":false},
  {"no":165,"word":"ballpoint pen","star":false,"pos":"名","meaning":"ボールペン","example":"Please use a ballpoint pen on this paper.","circle":true},
  {"no":166,"word":"bamboo","star":false,"pos":"名","meaning":"竹","example":"This toy is made of bamboo.","circle":false},
  {"no":167,"word":"ban","star":false,"pos":"動","meaning":"禁止する","example":"Riding bikes is banned on this street.","circle":true},
  {"no":168,"word":"banana","star":true,"pos":"名","meaning":"バナナ","example":"I eat a banana every morning.","circle":false},
  {"no":169,"word":"band","star":false,"pos":"名","meaning":"バンド、楽団    　※school band / brass band 吹奏楽部","example":"I play the guitar in a band.","circle":false},
  {"no":170,"word":"bank","star":false,"pos":"名","meaning":"銀行","example":"Go down this street and turn left at the bank.","circle":false},
  {"no":171,"word":"barbecue（barbeque）","star":false,"pos":"名","meaning":"バーベキュー","example":"Let's have a barbecue outside tomorrow.","circle":true},
  {"no":172,"word":"barber","star":false,"pos":"名","meaning":"理髪師","example":"My brother is studying to become a barber.","circle":true},
  {"no":173,"word":"barrier","star":false,"pos":"名","meaning":"壁、障壁、柵","example":"We couldn't go into the area because there was a barrier.","circle":true},
  {"no":174,"word":"baseball","star":true,"pos":"名","meaning":"野球","example":"I like playing baseball.","circle":false},
  {"no":175,"word":"basic","star":false,"pos":"形","meaning":"基本的な","example":"Let's start with this basic question.","circle":false},
  {"no":176,"word":"basically","star":false,"pos":"副","meaning":"基本的に","example":"He is basically a good person.","circle":true},
  {"no":177,"word":"basket","star":false,"pos":"名","meaning":"かご、バスケット","example":"Please put your clothes into this basket.","circle":true},
  {"no":178,"word":"basketball","star":true,"pos":"名","meaning":"バスケットボール","example":"I am a member of the basketball club.","circle":false},
  {"no":179,"word":"bat","star":true,"pos":"名","meaning":"（野球などの）バット","example":"My father gave me a baseball bat as a present.","circle":true},
  {"no":180,"word":"bath","star":true,"pos":"名","meaning":"入浴、ふろ      ※take a bath 入浴する","example":"Japanese people like taking a bath.","circle":false},
  {"no":181,"word":"bathroom","star":false,"pos":"名","meaning":"浴室、（主にアメリカで）トイレ","example":"Where is the bathroom?","circle":false},
  {"no":182,"word":"bathtub","star":false,"pos":"名","meaning":"バスタブ、浴槽","example":"I wash the bathtub when I finish taking a bath.","circle":true},
  {"no":183,"word":"battery","star":false,"pos":"名","meaning":"電池、バッテリー","example":"This flashlight needs a battery.","circle":true},
  {"no":184,"word":"bay","star":false,"pos":"名","meaning":"湾、入り江","example":"There are many ships in the bay.","circle":true},
  {"no":185,"word":"be","star":true,"pos":"動","meaning":"～である、（～に）いる、ある、～になる  （be動詞の原形）","example":"I want to be a teacher.","circle":false},
  {"no":186,"word":"beach","star":true,"pos":"名","meaning":"浜、浜辺","example":"Let's go to the beach after lunch.","circle":false},
  {"no":187,"word":"beak","star":false,"pos":"名","meaning":"くちばし","example":"The bird has a sharp beak.","circle":true},
  {"no":188,"word":"bean","star":true,"pos":"名","meaning":"豆","example":"During Setsubun, we throw beans.","circle":true},
  {"no":189,"word":"bear","star":true,"pos":"名","meaning":"クマ","example":"Some bears live in this mountain.","circle":false},
  {"no":190,"word":"beat","star":false,"pos":"動","meaning":"打ち負かす、打つ、たたく    【活用】 beat - beat - beaten/beat","example":"On the stage, my heart was beating quickly.","circle":true},
  {"no":191,"word":"beautiful","star":true,"pos":"形","meaning":"美しい、きれいな","example":"Look at the beautiful flowers.","circle":false},
  {"no":192,"word":"beautifully","star":false,"pos":"副","meaning":"美しく","example":"The picture was painted beautifully.","circle":true},
  {"no":193,"word":"beauty","star":false,"pos":"名","meaning":"美しさ","example":"We enjoyed the beauty of nature in the mountains.","circle":false},
  {"no":194,"word":"because","star":false,"pos":"接","meaning":"（なぜなら）～だから　　 ※because of  ～　～の理由で","example":"I will not go out because I am sick.","circle":false},
  {"no":195,"word":"become","star":false,"pos":"動","meaning":"～になる　　　【活用】 become - became - become","example":"My brother became a doctor.","circle":false},
  {"no":196,"word":"bed","star":true,"pos":"名","meaning":"ベッド、寝床　　　       　※go to bed  寝る","example":"I go to bed at 10 p.m. every night.","circle":false},
  {"no":197,"word":"bedroom","star":false,"pos":"名","meaning":"寝室","example":"My bedroom is on the second floor.","circle":false},
  {"no":198,"word":"bee","star":false,"pos":"名","meaning":"ハチ","example":"Honey is made by bees.","circle":true},
  {"no":199,"word":"beef","star":true,"pos":"名","meaning":"牛肉","example":"Kobe beef is popular among foreign tourists.","circle":false},
  {"no":200,"word":"been","star":false,"pos":"動","meaning":"beの過去分詞　　      　※have been to　～　～に行ったことがある","example":"I have been to America twice.","circle":false}
];
