const WORDS08 = [
{"no":701,"word":"else","star":false,"pos":"形・副","meaning":"他に（の）、その他（の）　　　※anything else　他に何か","example":"Do you need anything else?","circle":false},
{"no":702,"word":"e(-)mail","star":false,"pos":"名","meaning":"電子メール、Eメール","example":"Thank you for your kind e-mail.","circle":false},
{"no":703,"word":"embarrassed","star":false,"pos":"形","meaning":"恥ずかしい、気まずい","example":"The mistake made me embarrassed.","circle":false},
{"no":704,"word":"emergency","star":false,"pos":"名","meaning":"緊急事態、非常時","example":"Do you know what to do in an emergency?","circle":false},
{"no":705,"word":"empty","star":false,"pos":"形","meaning":"空の","example":"Your cup is empty. Would you like more tea?","circle":false},
{"no":706,"word":"encourage","star":false,"pos":"動","meaning":"勇気づける、励ます","example":"I was encouraged by my classmates.","circle":false},
{"no":707,"word":"end","star":false,"pos":"動・名","meaning":"①（動）終わる、終える　\n②（名）最後、端　　※in the end 　最後に（は）","example":"①When does this class end?\n②This is the end of my story.","circle":false},
{"no":708,"word":"endangered","star":false,"pos":"形","meaning":"絶滅寸前の","example":"We must try to save endangered species.","circle":true},
{"no":709,"word":"enemy","star":false,"pos":"名","meaning":"敵","example":"Please understand that I am not your enemy.","circle":true},
{"no":710,"word":"energy","star":false,"pos":"名","meaning":"エネルギー","example":"We use a lot of energy every day.","circle":false},
{"no":711,"word":"engine","star":false,"pos":"名","meaning":"エンジン","example":"This engine is powerful and also eco-friendly.","circle":true},
{"no":712,"word":"engineer","star":false,"pos":"名","meaning":"技師、エンジニア","example":"He's an engineer at a computer company.","circle":false},
{"no":713,"word":"England","star":false,"pos":"名","meaning":"イングランド（主にグレートブリテン島の南部地域）","example":"She's from England.","circle":false},
{"no":714,"word":"English","star":true,"pos":"名・形","meaning":"英語（の）、イギリスの、イギリス人（の）","example":"Learning English is interesting.","circle":false},
{"no":715,"word":"enjoy","star":true,"pos":"動","meaning":"楽しむ、～は楽しい（と思う）","example":"People enjoyed talking with them.","circle":false},
{"no":716,"word":"enough","star":false,"pos":"形","meaning":"十分な、ちょうどいい数（量）の","example":"I don't have enough money to buy a computer.","circle":false},
{"no":717,"word":"enter","star":false,"pos":"動","meaning":"（学校などに）入る","example":"I will enter high school next spring.","circle":false},
{"no":718,"word":"entertainment","star":false,"pos":"名","meaning":"娯楽","example":"Watching movies was popular entertainment then.","circle":true},
{"no":719,"word":"entrance","star":true,"pos":"名","meaning":"入り口、玄関、入学","example":"This is the entrance of this building.","circle":false},
{"no":720,"word":"envelope","star":false,"pos":"名","meaning":"封筒","example":"I need an envelope to send this letter.","circle":true},
{"no":721,"word":"environment","star":false,"pos":"名","meaning":"環境","example":"We have to work together to save the environment.","circle":false},
{"no":722,"word":"environmental","star":false,"pos":"形","meaning":"環境の","example":"I want to study environmental problems at university.","circle":true},
{"no":723,"word":"erase","star":false,"pos":"動","meaning":"～を消す","example":"We have to erase the blackboard.","circle":false},
{"no":724,"word":"eraser","star":true,"pos":"名","meaning":"消しゴム","example":"Whose eraser is this?","circle":false},
{"no":725,"word":"escalator","star":false,"pos":"名","meaning":"エスカレーター","example":"You can take the escalator to that floor.","circle":true},
{"no":726,"word":"escape","star":false,"pos":"動","meaning":"逃げる","example":"My cat sometimes escapes from my house.","circle":false},
{"no":727,"word":"especially","star":false,"pos":"副","meaning":"特に","example":"I like Japanese food, especially sushi.","circle":false},
{"no":728,"word":"essay","star":false,"pos":"名","meaning":"小論文、作文、エッセイ","example":"I have to finish my essay by next Wednesday.","circle":true},
{"no":729,"word":"etc.","star":false,"pos":"","meaning":"～など（et ceteraの略）","example":"We talked about family, school, etc.","circle":true},
{"no":730,"word":"EU","star":false,"pos":"名","meaning":"欧州連合（European Unionの略）","example":"France is a member of the EU.","circle":true},
{"no":731,"word":"Europe","star":false,"pos":"名","meaning":"ヨーロッパ","example":"Manga and anime are popular in Europe.","circle":false},
{"no":732,"word":"European","star":false,"pos":"名・形","meaning":"ヨーロッパの人、ヨーロッパの","example":"I am going to visit some European countries this summer.","circle":true},
{"no":733,"word":"evacuation","star":false,"pos":"名","meaning":"避難","example":"This school is a place for evacuation in this town.","circle":true},
{"no":734,"word":"eve","star":false,"pos":"名","meaning":"前夜、前日","example":"On Christmas Eve, I enjoy dinner with my family.","circle":true},
{"no":735,"word":"even","star":false,"pos":"副","meaning":"～でさえ、～でも","example":"He gets up early even on holidays.","circle":false},
{"no":736,"word":"evening","star":true,"pos":"名","meaning":"夕方、晩","example":"In the evening, I watched a soccer game on TV.","circle":false},
{"no":737,"word":"event","star":true,"pos":"名","meaning":"（重要な）出来事、事件、行事","example":"I enjoyed many school events.","circle":false},
{"no":738,"word":"ever","star":false,"pos":"副","meaning":"（疑問文・否定文で）今までに、かつて","example":"Have you ever seen a traditional Japanese festival?","circle":false},
{"no":739,"word":"every","star":false,"pos":"形","meaning":"すべての、毎～","example":"Every year, many foreigners visit Hyogo.","circle":false},
{"no":740,"word":"everybody","star":false,"pos":"代","meaning":"みんな","example":"Everybody knows the story of \"Momotaro\".","circle":false},
{"no":741,"word":"everyday","star":false,"pos":"形","meaning":"毎日の、日常の","example":"The Internet is necessary in our everyday life.","circle":true},
{"no":742,"word":"everyone","star":true,"pos":"代","meaning":"みんな","example":"Everyone in my host family is kind to me.","circle":false},
{"no":743,"word":"everything","star":false,"pos":"代","meaning":"すべてのこと（もの）","example":"Everything is OK.","circle":false},
{"no":744,"word":"everywhere","star":false,"pos":"副","meaning":"いたるところ、どこでも","example":"In Japan, you can see sushi restaurants everywhere.","circle":false},
{"no":745,"word":"exactly","star":false,"pos":"副","meaning":"正確に、ちょうど、（答えに使って）そのとおりです","example":"It is exactly 9 o'clock now.","circle":true},
{"no":746,"word":"exam（examination）","star":false,"pos":"名","meaning":"試験　※entrance exam    入学試験","example":"We are going to have an exam next week.","circle":false},
{"no":747,"word":"example","star":false,"pos":"名","meaning":"例、実例　　※for example  例えば","example":"Let's look at two examples.","circle":false},
{"no":748,"word":"excellent","star":false,"pos":"形","meaning":"非常に優れた、優秀な","example":"Your report is excellent.","circle":false},
{"no":749,"word":"exchange","star":false,"pos":"名","meaning":"交換","example":"Our city has a student exchange program with Korea.","circle":false},
{"no":750,"word":"excited","star":false,"pos":"形","meaning":"興奮した","example":"You look really excited!","circle":false},
{"no":751,"word":"exciting","star":true,"pos":"形","meaning":"興奮させる、わくわくするような","example":"The soccer game we watched last night was very exciting.","circle":false},
{"no":752,"word":"excuse","star":true,"pos":"動","meaning":"許す   ※Excuse me.　失礼します、すみません","example":"Excuse me.  What time is it now?","circle":false},
{"no":753,"word":"exercise","star":false,"pos":"名","meaning":"運動、練習問題　　※do some exercise  運動する","example":"We do some exercises in PE class.","circle":false},
{"no":754,"word":"exit","star":false,"pos":"名","meaning":"出口","example":"The exit is on your left side.","circle":true},
{"no":755,"word":"expect","star":false,"pos":"動","meaning":"予期する、期待する","example":"I didn't expect to meet you here.","circle":true},
{"no":756,"word":"expensive","star":false,"pos":"形","meaning":"（値段が）高い","example":"The pen I lost was very expensive.","circle":false},
{"no":757,"word":"experience","star":false,"pos":"動・名","meaning":"経験（する）、体験（する）","example":"Working with foreign people will be a great experience.","circle":false},
{"no":758,"word":"experiment","star":false,"pos":"名","meaning":"実験","example":"We did an interesting experiment in science class.","circle":true},
{"no":759,"word":"expert","star":false,"pos":"名","meaning":"専門家、エキスパート","example":"This report was written by experts around the world.","circle":false},
{"no":760,"word":"explain","star":false,"pos":"動","meaning":"説明する","example":"It's difficult for me to explain sumo.","circle":false},
{"no":761,"word":"explanation","star":false,"pos":"名","meaning":"説明","example":"Listen to the explanation carefully.","circle":true},
{"no":762,"word":"explore","star":false,"pos":"動","meaning":"探検する","example":"I enjoyed exploring the island with my friends.","circle":true},
{"no":763,"word":"express","star":false,"pos":"動・名","meaning":"①（動）表現する、言い表す\n②（名）急行、速達","example":"①It is difficult to express our feelings.\n②I will take the 9 a.m. express to Tokyo.","circle":false},
{"no":764,"word":"expression","star":false,"pos":"名","meaning":"表現","example":"You will learn some expressions for shopping today.","circle":false},
{"no":765,"word":"eye","star":true,"pos":"名","meaning":"目","example":"Please close your eyes.","circle":false},
{"no":766,"word":"eyebrow","star":false,"pos":"名","meaning":"まゆ、まゆ毛","example":"He raised his eyebrows when he heard the news.","circle":true},
{"no":767,"word":"eyelid","star":false,"pos":"名","meaning":"まぶた","example":"Eyes are protected by eyelids.","circle":true},
{"no":768,"word":"face","star":true,"pos":"動・名","meaning":"①（名）顔、表情\n②（動）（危険・困難などに）立ち向かう、直面する","example":"①The light showed his face.\n②We are facing a new problem.","circle":false},
{"no":769,"word":"facial","star":false,"pos":"形","meaning":"顔の","example":"Facial expressions are important for communication.","circle":true},
{"no":770,"word":"facility","star":false,"pos":"名","meaning":"施設、設備","example":"The hotel is popular because of its unique facilities.","circle":true},
{"no":771,"word":"fact","star":false,"pos":"名","meaning":"事実、現実　　※in fact　実は","example":"In fact, I left my textbook at home.","circle":false},
{"no":772,"word":"factory","star":false,"pos":"名","meaning":"工場","example":"My mother works at a computer factory.","circle":false},
{"no":773,"word":"fail","star":false,"pos":"動","meaning":"失敗する、しくじる、（学科・試験に）落ちる","example":"You studied very hard, so you will not fail the test.","circle":true},
{"no":774,"word":"failure","star":false,"pos":"名","meaning":"失敗","example":"You can learn something from failure.","circle":true},
{"no":775,"word":"fair","star":false,"pos":"形","meaning":"公平な","example":"You ate all the cakes!  It's not fair.","circle":false},
{"no":776,"word":"fairy","star":false,"pos":"名・形","meaning":"（名）妖精　（形）妖精のような","example":"People believe that fairies live in the forest.","circle":true},
{"no":777,"word":"fall","star":true,"pos":"動・名","meaning":"①（動）落ちる　　   【活用】 fall - fell - fallen\n②（名）秋、滝","example":"①Alice fell into the hole.\n②It's spring in Japan now, but it's fall in New Zealand.","circle":false},
{"no":778,"word":"familiar","star":false,"pos":"形","meaning":"よく知られた、なじみのある","example":"This story is familiar to all young children.","circle":true},
{"no":779,"word":"family","star":true,"pos":"名","meaning":"家族","example":"She went to Thailand on holiday with her family.","circle":false},
{"no":780,"word":"famous","star":true,"pos":"形","meaning":"有名な　　※be famous for ～　～で有名な","example":"My town is famous for its delicious grapes.","circle":false},
{"no":781,"word":"fan","star":false,"pos":"名","meaning":"①（スポーツなどの）ファン　\n②扇","example":"①I'm a big fan of the Hanshin Tigers.\n②This is a traditional Japanese fan.","circle":false},
{"no":782,"word":"fantastic","star":true,"pos":"形","meaning":"すばらしい、すてきな","example":"That drama performance was fantastic!","circle":true},
{"no":783,"word":"far","star":false,"pos":"形・副","meaning":"（距離が）遠くに、遠く（い）","example":"How far is the nearest station from here?","circle":false},
{"no":784,"word":"farewell","star":false,"pos":"名","meaning":"別れ","example":"Can you come to the farewell party?","circle":false},
{"no":785,"word":"farm","star":false,"pos":"名","meaning":"農場","example":"My grandfather was working at the farm.","circle":false},
{"no":786,"word":"farmer","star":true,"pos":"名","meaning":"農場主、農業をする人","example":"My grandfather is a farmer.","circle":false},
{"no":787,"word":"farming","star":false,"pos":"名","meaning":"農業","example":"Many young people are interested in farming.","circle":true},
{"no":788,"word":"fashion","star":false,"pos":"名","meaning":"流行、はやり","example":"That design is this year's fashion.","circle":false},
{"no":789,"word":"fast","star":true,"pos":"形・副","meaning":"（速度が）速く（い）","example":"The animal can run fast.","circle":false},
{"no":790,"word":"fast food","star":false,"pos":"名","meaning":"ファストフード","example":"Eating only fast food is bad for your health.","circle":true},
{"no":791,"word":"fat","star":false,"pos":"形","meaning":"太った","example":"My dog is a little too fat.","circle":true},
{"no":792,"word":"father","star":true,"pos":"名","meaning":"父、父親","example":"This is my father.","circle":false},
{"no":793,"word":"favorite","star":true,"pos":"名・形","meaning":"お気に入りの（もの）、大好きな（もの）","example":"Music is one of my favorite things.","circle":false},
{"no":794,"word":"feather","star":false,"pos":"名","meaning":"羽、羽毛","example":"This jacket has a lot of feathers in it.","circle":true},
{"no":795,"word":"feature","star":false,"pos":"名","meaning":"特徴、特長、特質","example":"One feature of Kobe is its port area.","circle":true},
{"no":796,"word":"February","star":true,"pos":"名","meaning":"２月","example":"There is an event called “Setsubun” in February.","circle":false},
{"no":797,"word":"fee","star":false,"pos":"名","meaning":"料金、入場料","example":"How much is the entrance fee?","circle":false},
{"no":798,"word":"feed","star":false,"pos":"動","meaning":"えさをやる、食物を与える      【活用】 feed - fed - fed","example":"I feed the cat every morning.","circle":false},
{"no":799,"word":"feel","star":false,"pos":"動","meaning":"（体や心に）感じる、気分が～である  　【活用】 feel - felt - felt","example":"I felt happy when I heard the news.","circle":false},
{"no":800,"word":"feeling","star":false,"pos":"名","meaning":"感情、気持ち","example":"We can share our ideas and feelings in any language.","circle":false}
];
