const WORDS05 = [
  {"no":401,"word":"Christmas","star":false,"pos":"名","meaning":"クリスマス","example":"Many Japanese eat cakes at Christmas.","circle":false},
  {"no":402,"word":"Christmas card","star":false,"pos":"名","meaning":"クリスマスカード","example":"I send a Christmas card to the family every year.","circle":false},
  {"no":403,"word":"church","star":false,"pos":"名","meaning":"教会","example":"My family goes to church every Sunday.","circle":false},
  {"no":404,"word":"circle","star":true,"pos":"名","meaning":"円","example":"Please draw a circle in your notebook.","circle":false},
  {"no":405,"word":"city","star":true,"pos":"名","meaning":"市","example":"London is a beautiful city.","circle":false},
  {"no":406,"word":"city hall","star":false,"pos":"名","meaning":"市役所","example":"You should visit the city hall to get some information.","circle":false},
  {"no":407,"word":"civil servant","star":false,"pos":"名","meaning":"公務員","example":"My father works for this city as a civil servant.","circle":true},
  {"no":408,"word":"clap","star":false,"pos":"動","meaning":"（手を）たたく","example":"Everyone clapped their hands after the performance.","circle":true},
  {"no":409,"word":"clarinet","star":false,"pos":"名","meaning":"クラリネット","example":"My parents bought me a clarinet for my birthday.","circle":true},
  {"no":410,"word":"class","star":true,"pos":"名","meaning":"授業、クラス","example":"I like Mr. Tanaka's English class.","circle":false},
  {"no":411,"word":"classic","star":false,"pos":"形","meaning":"古典的な","example":"This is one of the classic books.  Everyone knows the story.","circle":false},
  {"no":412,"word":"classical","star":false,"pos":"形","meaning":"古典主義の、クラシックの","example":"I love listening to classical music.","circle":true},
  {"no":413,"word":"classmate","star":true,"pos":"名","meaning":"クラスメイト、級友","example":"She is talking with her classmates.","circle":false},
  {"no":414,"word":"classroom","star":true,"pos":"名","meaning":"教室","example":"Do you eat lunch in your classroom?","circle":false},
  {"no":415,"word":"clean","star":true,"pos":"動・形","meaning":"①（動）掃除する　　　\n②（形）きれいな","example":"①In Japan, students clean their classrooms by themselves.\n②Keep your classroom clean.","circle":false},
  {"no":416,"word":"clean-up","star":false,"pos":"名","meaning":"掃除","example":"December 31st is a clean-up day in Japan.","circle":true},
  {"no":417,"word":"clear","star":false,"pos":"動・形","meaning":"①（動）片付ける\n②（形）晴れた、（話の内容などが）はっきりした","example":"①I clear the table after dinner.\n②His face was not clear in the darkness.","circle":false},
  {"no":418,"word":"clearly","star":false,"pos":"副","meaning":"はっきりと","example":"Please speak clearly.","circle":false},
  {"no":419,"word":"clerk","star":false,"pos":"名","meaning":"店員","example":"I'm a clerk at a hotel.","circle":false},
  {"no":420,"word":"clever","star":false,"pos":"形","meaning":"利口な","example":"My brother is very clever.","circle":false},
  {"no":421,"word":"climate","star":false,"pos":"名","meaning":"気候","example":"The world climate is changing.","circle":false},
  {"no":422,"word":"climb","star":true,"pos":"動","meaning":"登る","example":"I want to climb Mt. Rokko.","circle":false},
  {"no":423,"word":"climber","star":false,"pos":"名","meaning":"登山者","example":"Many foreign climbers visit Mt. Fuji every year.","circle":true},
  {"no":424,"word":"clinic","star":false,"pos":"名","meaning":"診療所","example":"You don't look well.  You should go to a clinic.","circle":false},
  {"no":425,"word":"clock","star":true,"pos":"名","meaning":"（壁に掛ける）時計","example":"There is a big, old clock in my house.","circle":false},
  {"no":426,"word":"close","star":false,"pos":"動・形・副","meaning":"①（動）閉じる、閉める\n②（形・副）近い（く）、接近した（して）、親しい　\n※close to ～　～の近くに","example":"①I closed my eyes.\n②She is one of my close friends.","circle":false},
  {"no":427,"word":"closed","star":false,"pos":"形","meaning":"閉じた、閉じている、閉店の","example":"The bank is closed today.","circle":true},
  {"no":428,"word":"closet","star":false,"pos":"名","meaning":"押し入れ、クローゼット","example":"This closet is too small for all of my clothes.","circle":true},
  {"no":429,"word":"cloth","star":false,"pos":"名","meaning":"布","example":"I made some masks with cotton cloth.","circle":true},
  {"no":430,"word":"clothes","star":true,"pos":"名","meaning":"衣服、服","example":"I love Japanese clothes.","circle":false},
  {"no":431,"word":"cloud","star":false,"pos":"名","meaning":"雲","example":"There are a lot of clouds in the sky today.","circle":false},
  {"no":432,"word":"cloudy","star":true,"pos":"形","meaning":"くもりの、くもった","example":"It's cloudy today.","circle":false},
  {"no":433,"word":"club","star":true,"pos":"名","meaning":"クラブ、部","example":"I belong to a tennis club.","circle":false},
  {"no":434,"word":"club activity","star":false,"pos":"名","meaning":"部活動","example":"Most students do club activities after school.","circle":false},
  {"no":435,"word":"coach","star":false,"pos":"名","meaning":"コーチ","example":"He’s our tennis coach.","circle":false},
  {"no":436,"word":"coast","star":false,"pos":"名","meaning":"海岸","example":"My house is near the coast.","circle":false},
  {"no":437,"word":"coat","star":false,"pos":"名","meaning":"（衣類の）コート","example":"This coat is warm.","circle":false},
  {"no":438,"word":"coffee","star":true,"pos":"名","meaning":"コーヒー","example":"Would you like some coffee?","circle":false},
  {"no":439,"word":"coin","star":false,"pos":"名","meaning":"硬貨","example":"Look at these.  These are Australian coins.","circle":false},
  {"no":440,"word":"cola","star":false,"pos":"名","meaning":"コーラ","example":"I'll have a hamburger, French fries, and a cola.","circle":false},
  {"no":441,"word":"cold","star":true,"pos":"名・形","meaning":"①（形）寒い、冷たい\n②（名）風邪　  　※have a cold  風邪をひいている","example":"①The water is very cold.\n②I have a cold.","circle":false},
  {"no":442,"word":"collect","star":false,"pos":"動","meaning":"集める、収集する","example":"My hobby is collecting comic books.","circle":false},
  {"no":443,"word":"collection","star":false,"pos":"名","meaning":"収集","example":"My brother has a collection of old coins.","circle":false},
  {"no":444,"word":"college","star":false,"pos":"名","meaning":"（単科）大学","example":"She is studying Japanese art at a college.","circle":false},
  {"no":445,"word":"color","star":true,"pos":"名","meaning":"色","example":"What color do you like the best?","circle":false},
  {"no":446,"word":"colorful","star":false,"pos":"形","meaning":"色とりどりの","example":"I was excited to see many colorful bags at the shop.","circle":false},
  {"no":447,"word":"comb","star":false,"pos":"名","meaning":"くし","example":"Traditional Japanese combs are beautiful.","circle":true},
  {"no":448,"word":"combine","star":false,"pos":"動","meaning":"結合する、いっしょにする（なる）","example":"Let's combine the two things and see what will happen.","circle":true},
  {"no":449,"word":"come","star":false,"pos":"動","meaning":"来る\n※come from ～　～出身である、～から生じる  come back 戻る\ncome in (into) 入る　　【活用】 come - came - come","example":"We came to Japan three months ago.","circle":false},
  {"no":450,"word":"comedian","star":true,"pos":"名","meaning":"喜劇役者、コメディアン","example":"The comedian is funny and I always laugh.","circle":false},
  {"no":451,"word":"comedy","star":false,"pos":"名","meaning":"喜劇","example":"I don't like sad stories.  I like comedies.","circle":false},
  {"no":452,"word":"comfortable","star":false,"pos":"形","meaning":"心地よい、快適な","example":"This is a very comfortable bed.","circle":true},
  {"no":453,"word":"comic","star":false,"pos":"名・形","meaning":"（comics で）漫画（の）　　※comic book 漫画本","example":"I bought a comic book.","circle":false},
  {"no":454,"word":"comic book","star":false,"pos":"名","meaning":"漫画本","example":"Japanese comic books are very popular.","circle":false},
  {"no":455,"word":"comment","star":false,"pos":"名","meaning":"意見、コメント　　※make a comment  意見を述べる","example":"My teacher gave me some comments about my report.","circle":false},
  {"no":456,"word":"common","star":false,"pos":"形","meaning":"ふつうの、よくある     ※in common　共通の","example":"This is one of the common mistakes.","circle":false},
  {"no":457,"word":"communicate","star":false,"pos":"動","meaning":"意思を伝達する、（考え、情報などを）伝える","example":"We can communicate in English.","circle":false},
  {"no":458,"word":"communication","star":false,"pos":"名","meaning":"コミュニケーション、意思の疎通","example":"Communication is very important.","circle":false},
  {"no":459,"word":"community","star":false,"pos":"名","meaning":"地域社会、コミュニティー","example":"We always help each other in our community.","circle":false},
  {"no":460,"word":"company","star":false,"pos":"名","meaning":"会社","example":"My father works at a car company.","circle":false},
  {"no":461,"word":"compare","star":false,"pos":"動","meaning":"比較する、比べる","example":"Let's compare this car with that car.","circle":false},
  {"no":462,"word":"compasses","star":false,"pos":"名","meaning":"コンパス（複数形で使う）","example":"You should use compasses when you draw a circle.","circle":true},
  {"no":463,"word":"complain","star":false,"pos":"動","meaning":"不平を言う","example":"Let's stop complaining and try again.","circle":true},
  {"no":464,"word":"computer","star":true,"pos":"名","meaning":"コンピューター","example":"I want to buy a new computer.","circle":false},
  {"no":465,"word":"concert","star":false,"pos":"名","meaning":"演奏会、コンサート","example":"There is a wonderful concert hall in Nishinomiya.","circle":false},
  {"no":466,"word":"conclusion","star":false,"pos":"名","meaning":"結論","example":"We talked a lot and finally came to a conclusion.","circle":false},
  {"no":467,"word":"condition","star":false,"pos":"名","meaning":"状況、状態","example":"It's not a good idea to play baseball in such bad conditions.","circle":false},
  {"no":468,"word":"confidence","star":false,"pos":"名","meaning":"自信","example":"He had a lot of confidence because of his training.","circle":true},
  {"no":469,"word":"confident","star":false,"pos":"形","meaning":"自信を持った","example":"Be confident and work hard!","circle":false},
  {"no":470,"word":"confused","star":false,"pos":"形","meaning":"混乱した","example":"I was confused because she explained it very fast.","circle":false},
  {"no":471,"word":"congratulation","star":false,"pos":"名","meaning":"（Congratulations! で）おめでとう","example":"You won the speech contest.  Congratulations!","circle":false},
  {"no":472,"word":"connect","star":false,"pos":"動","meaning":"つなぐ、つながる","example":"We are connected by e-mail.","circle":false},
  {"no":473,"word":"connection","star":false,"pos":"名","meaning":"接続、つながり、関係","example":"I want to find a connection between these two facts.","circle":false},
  {"no":474,"word":"consider","star":false,"pos":"動","meaning":"よく考える","example":"We should consider how to save our environment.","circle":true},
  {"no":475,"word":"contact","star":false,"pos":"動","meaning":"（人と）連絡を取る","example":"You can contact me if you have any questions.","circle":false},
  {"no":476,"word":"contain","star":false,"pos":"動","meaning":"含む、入れている","example":"This book contains a lot of useful information.","circle":true},
  {"no":477,"word":"content","star":false,"pos":"名","meaning":"内容","example":"I like the design of the book but I don't like its content.","circle":false},
  {"no":478,"word":"contest","star":true,"pos":"名","meaning":"コンテスト、コンクール","example":"Our chorus contest is held in September.","circle":false},
  {"no":479,"word":"continent","star":false,"pos":"名","meaning":"大陸","example":"There are seven continents around the world.","circle":true},
  {"no":480,"word":"continue","star":false,"pos":"動","meaning":"続ける、続く","example":"We ate lunch and then continued our practice.","circle":false},
  {"no":481,"word":"control","star":false,"pos":"名","meaning":"制御　　　※out of control  制御しきれなくなって","example":"The robot got out of control.","circle":false},
  {"no":482,"word":"convenience","star":false,"pos":"名","meaning":"便利、都合","example":"It is a great convenience to live near the station.","circle":false},
  {"no":483,"word":"convenience store","star":true,"pos":"名","meaning":"コンビニエンスストア","example":"There are many convenience stores in Japan.","circle":false},
  {"no":484,"word":"convenient","star":false,"pos":"形","meaning":"便利な、都合のいい","example":"Low-floor buses are convenient for everyone.","circle":false},
  {"no":485,"word":"conversation","star":false,"pos":"名","meaning":"会話","example":"We often enjoy conversations on the Internet.","circle":true},
  {"no":486,"word":"cook","star":true,"pos":"動・名","meaning":"①（動）調理する　\n②（名）料理人","example":"①My grandmother came to my house and cooked for me.\n②He is one of the best cooks in Japan.","circle":false},
  {"no":487,"word":"cookie","star":false,"pos":"名","meaning":"クッキー","example":"Let's make cookies this weekend!","circle":true},
  {"no":488,"word":"cooking","star":true,"pos":"名","meaning":"料理（すること）","example":"I like cooking.","circle":false},
  {"no":489,"word":"cool","star":true,"pos":"形","meaning":"①涼しい\n②すてきな","example":"①It's getting cooler.\n②Japanese manga is cool.","circle":false},
  {"no":490,"word":"cooperation","star":false,"pos":"名","meaning":"協力","example":"I need your cooperation to do this job.","circle":true},
  {"no":491,"word":"copy","star":false,"pos":"動","meaning":"まねる、写しとる","example":"She copied her teacher's painting.","circle":false},
  {"no":492,"word":"corn","star":true,"pos":"名","meaning":"トウモロコシ","example":"My uncle sends me a lot of corn every year.","circle":true},
  {"no":493,"word":"corner","star":false,"pos":"名","meaning":"かど","example":"Turn left at the next corner.","circle":false},
  {"no":494,"word":"correct","star":false,"pos":"動","meaning":"正す、直す","example":"Please correct my English mistakes.","circle":false},
  {"no":495,"word":"cost","star":false,"pos":"動","meaning":"（費用などが）かかる　　【活用】 cost - cost - cost","example":"This watch costs 10,000 yen.","circle":false},
  {"no":496,"word":"costume","star":false,"pos":"名","meaning":"（民族などの）服装、（舞台の）衣装","example":"We wear special costumes at Halloween parties.","circle":false},
  {"no":497,"word":"cotton","star":false,"pos":"名","meaning":"木綿","example":"A yukata is a summer cotton kimono.","circle":false},
  {"no":498,"word":"couch","star":false,"pos":"名","meaning":"ソファー、長椅子","example":"I sit on the couch when I watch TV.","circle":true},
  {"no":499,"word":"cough","star":false,"pos":"名","meaning":"せき","example":"I have a bad cough.","circle":false},
  {"no":500,"word":"could","star":false,"pos":"助","meaning":"canの過去形　\n※Could you ～ ?　～してくださいませんか　（Can you ～ ? の丁寧な言い方）","example":"①I could not catch any fish yesterday.\n②Could you tell me the way to Himeji Castle?","circle":false}
];
