const WORDS13 = [
  {"no":1201,"word":"king","star":true,"pos":"名","meaning":"王","example":"The king was loved by everyone.","circle":false},
  {"no":1202,"word":"kitchen","star":false,"pos":"名","meaning":"台所、調理場","example":"My mother is in the kitchen.","circle":false},
  {"no":1203,"word":"kite","star":false,"pos":"名","meaning":"凧","example":"You can see many kites in the New Year's sky.","circle":false},
  {"no":1204,"word":"kiwi","star":true,"pos":"名","meaning":"キウイ（kiwi fruit とも言う）","example":"I like to eat kiwi fruit with yogurt.","circle":true},
  {"no":1205,"word":"knee","star":true,"pos":"名","meaning":"膝","example":"I cannot run because I injured my knee.","circle":false},
  {"no":1206,"word":"knife","star":false,"pos":"名","meaning":"ナイフ　　【複数】 knives","example":"Knives are dangerous.  They are not toys.","circle":false},
  {"no":1207,"word":"knit","star":false,"pos":"動","meaning":"編む","example":"My mother knitted a sweater for me.","circle":true},
  {"no":1208,"word":"knock","star":false,"pos":"動・名","meaning":"（動）ノックする、たたく　（名）（ドア・窓などを）たたく音","example":"Why did you knock at my door?","circle":false},
  {"no":1209,"word":"know","star":true,"pos":"動","meaning":"知っている、知る　　　【活用】 know - knew - known","example":"You know a lot about Japan.","circle":false},
  {"no":1210,"word":"knowledge","star":false,"pos":"名","meaning":"知識","example":"My uncle has a good knowledge of world history.","circle":true},
  {"no":1211,"word":"koala","star":true,"pos":"名","meaning":"コアラ","example":"When I go to Australia, I want to see koalas.","circle":true},
  {"no":1212,"word":"Korea","star":false,"pos":"名","meaning":"韓国・朝鮮","example":"I went to Korea with my family.","circle":false},
  {"no":1213,"word":"Korean","star":false,"pos":"名・形","meaning":"韓国・朝鮮の、韓国・朝鮮人（の）、韓国・朝鮮語（の）","example":"I love Korean food very much.","circle":false},
  {"no":1214,"word":"lack","star":false,"pos":"名","meaning":"不足","example":"Lack of sleep is not good for your health.","circle":true},
  {"no":1215,"word":"lady","star":false,"pos":"名","meaning":"女性、婦人","example":"The lady standing over there is my aunt.","circle":false},
  {"no":1216,"word":"lake","star":true,"pos":"名","meaning":"湖","example":"Lake Biwa is the largest lake in Japan.","circle":false},
  {"no":1217,"word":"lamp","star":false,"pos":"名","meaning":"明かり、ランプ、電気スタンド","example":"At night, I use a lamp for reading books.","circle":true},
  {"no":1218,"word":"land","star":false,"pos":"動・名","meaning":"①（動）上陸する、着陸する\n②（名）土地、国","example":"①The plane landed safely.\n②We bought the land to build a house.","circle":false},
  {"no":1219,"word":"language","star":false,"pos":"名","meaning":"言語、言葉","example":"What languages do people speak in your country?","circle":false},
  {"no":1220,"word":"lantern","star":false,"pos":"名","meaning":"ちょうちん、ランタン","example":"I made a pumpkin lantern for Halloween.","circle":true},
  {"no":1221,"word":"large","star":true,"pos":"形","meaning":"（広くて）大きい、（数、量が）多い","example":"What a large building!","circle":false},
  {"no":1222,"word":"last","star":false,"pos":"動・形","meaning":"①（動）続く\n②（形）（時間的に）この前の\n③（形）最後の　　　※at last 最後には、ついに","example":"①The game lasted about an hour. \n②Last year I visited many places. \n③It's my last wish.","circle":false},
  {"no":1223,"word":"late","star":false,"pos":"形・副","meaning":"（時間・時期が）遅い（く）、遅れた（て）","example":"Oh, no.  I'm late!","circle":false},
  {"no":1224,"word":"later","star":false,"pos":"副","meaning":"後で、のちほど、～後　　　※～ year(s) later ～年後","example":"Ten years later, he became a teacher.","circle":false},
  {"no":1225,"word":"latest","star":false,"pos":"形","meaning":"最新の","example":"Please visit our website for the latest news.","circle":true},
  {"no":1226,"word":"laugh","star":false,"pos":"動","meaning":"（声を出して）笑う","example":"They began to laugh when they heard my story.","circle":false},
  {"no":1227,"word":"laughter","star":false,"pos":"名","meaning":"笑い","example":"There is always some laughter in my team.","circle":true},
  {"no":1228,"word":"laundry","star":false,"pos":"名","meaning":"洗濯（物）","example":"I do the laundry after I return home.","circle":true},
  {"no":1229,"word":"law","star":false,"pos":"名","meaning":"法律","example":"You must obey the law.","circle":true},
  {"no":1230,"word":"lawyer","star":false,"pos":"名","meaning":"弁護士","example":"My brother became a lawyer.","circle":false},
  {"no":1231,"word":"lazy","star":false,"pos":"形","meaning":"怠惰な、なまけている","example":"She is too lazy to get up early.","circle":true},
  {"no":1232,"word":"lead","star":false,"pos":"動","meaning":"導く、案内する　　 【活用】 lead - led - led","example":"I can lead you to Himeji Castle.","circle":false},
  {"no":1233,"word":"leader","star":false,"pos":"名","meaning":"指導者、リーダー","example":"He will be a good leader in the future.","circle":false},
  {"no":1234,"word":"leaf","star":false,"pos":"名","meaning":"葉　　【複数】 leaves","example":"The autumn leaves in Japan are so beautiful.","circle":true},
  {"no":1235,"word":"learn","star":false,"pos":"動","meaning":"学ぶ、覚える、知る","example":"I want to learn about Hyogo.","circle":false},
  {"no":1236,"word":"least","star":false,"pos":"代・形・副","meaning":"（littleの最上級）　最も少ない、最小（の）\n【活用】 little - less -least　　　※at least 少なくとも","example":"He had the least money of us all.","circle":false},
  {"no":1237,"word":"leave","star":true,"pos":"動","meaning":"①去る、出発する　\n②残す、置いていく、忘れる　　【活用】 leave - left - left","example":"①I left home around six o'clock.\n②I left the textbook at home.","circle":false},
  {"no":1238,"word":"left","star":true,"pos":"副・名","meaning":"左（へ）、左の方に","example":"Go down this street and turn left at the restaurant.","circle":false},
  {"no":1239,"word":"leg","star":true,"pos":"名","meaning":"（人・動物などの）あし、すね","example":"This dog has short legs.","circle":false},
  {"no":1240,"word":"lemon","star":true,"pos":"名","meaning":"レモン","example":"There are some lemons on that tree.","circle":false},
  {"no":1241,"word":"lemonade","star":false,"pos":"名","meaning":"レモネード","example":"May I have a glass of lemonade?","circle":true},
  {"no":1242,"word":"lend","star":false,"pos":"動","meaning":"～を貸す      【活用】 lend - lent - lent","example":"Can you lend me one thousand yen?","circle":false},
  {"no":1243,"word":"less","star":false,"pos":"形・副","meaning":"もっと少ない（く） （littleの比較級）  　【活用】 little - less - least","example":"We have had less rain this year.","circle":true},
  {"no":1244,"word":"lesson","star":false,"pos":"名","meaning":"授業、レッスン","example":"We have four English lessons every week.","circle":false},
  {"no":1245,"word":"let","star":false,"pos":"動","meaning":"～させる","example":"Let me explain a little.","circle":false},
  {"no":1246,"word":"let's","star":true,"pos":"動","meaning":"～しましょう  　※Yes, let's.　そうしよう","example":"Let's go shopping.","circle":false},
  {"no":1247,"word":"letter","star":false,"pos":"名","meaning":"①文字　\n②（ふつう封筒に入った）手紙","example":"①“G” is the third letter of “light”.\n②I am writing a letter to my grandmother.","circle":false},
  {"no":1248,"word":"lettuce","star":true,"pos":"名","meaning":"レタス","example":"I usually put bacon and lettuce in a sandwich.","circle":true},
  {"no":1249,"word":"level","star":false,"pos":"名","meaning":"水平（面）、水位、レベル","example":"We should think about the rising sea levels.","circle":false},
  {"no":1250,"word":"librarian","star":false,"pos":"名","meaning":"司書、図書館員","example":"The librarian introduced this book to me.","circle":true},
  {"no":1251,"word":"library","star":true,"pos":"名","meaning":"図書館、図書室","example":"I like to go to the library to read books.","circle":false},
  {"no":1252,"word":"license","star":false,"pos":"名","meaning":"許可、免許","example":"You need a license to drive a car.","circle":true},
  {"no":1253,"word":"lie","star":false,"pos":"動","meaning":"横たわる、横になる　【活用】 lie - lay - lain","example":"Some people were lying on the beach.","circle":false},
  {"no":1254,"word":"life","star":true,"pos":"名","meaning":"生活、一生、命   　　【複数】 lives","example":"My grandmother always enjoys her life.","circle":false},
  {"no":1255,"word":"lifestyle","star":false,"pos":"名","meaning":"生活様式","example":"We must change our lifestyles to save the earth.","circle":false},
  {"no":1256,"word":"lift","star":false,"pos":"動","meaning":"持ち上げる","example":"You need a lot of power to lift a mikoshi.","circle":false},
  {"no":1257,"word":"light","star":false,"pos":"名・形","meaning":"①（名）光、あかり、電灯　　（動）～に火をつける、ともす\n②（形）軽い","example":"①Please turn on the light.\n②This computer is very light.","circle":false},
  {"no":1258,"word":"light bulb","star":false,"pos":"名","meaning":"電球","example":"We need to buy some new light bulbs.","circle":true},
  {"no":1259,"word":"like","star":true,"pos":"動・前","meaning":"①（動）～を好む、～が好きである\n※would like to ～　～したいと思う\n②（前）～のように、～のような\n※look like ～ ～のように見える\n③（前）～に似ている、～に似た","example":"①I like English very much.\n②Please eat soba noodles like this.\n③It looks like a small bear.","circle":false},
  {"no":1260,"word":"limit","star":false,"pos":"動・名","meaning":"制限（する）","example":"You should limit your time for computer games.","circle":true},
  {"no":1261,"word":"line","star":false,"pos":"名","meaning":"線、（電車の）路線、電話線、列","example":"Please take the JR Bantan Line to visit Takeda Castle.","circle":false},
  {"no":1262,"word":"lion","star":true,"pos":"名","meaning":"ライオン","example":"You can see a lot of lions under the tree.","circle":false},
  {"no":1263,"word":"lip","star":false,"pos":"名","meaning":"くちびる","example":"I usually put some cream on my lips.","circle":true},
  {"no":1264,"word":"list","star":false,"pos":"名","meaning":"名簿、リスト","example":"Please write your name on the list.","circle":false},
  {"no":1265,"word":"listen","star":true,"pos":"動","meaning":"（じっと）聞く、耳を傾ける  ※listen to ～ ～を聞く、～に耳を傾ける","example":"I often enjoy listening to music on the radio.","circle":false},
  {"no":1266,"word":"listener","star":false,"pos":"名","meaning":"聞き手","example":"Try to look at the listeners when you speak.","circle":true},
  {"no":1267,"word":"liter","star":false,"pos":"名","meaning":"リットル","example":"She drinks two liters of water every day.","circle":true},
  {"no":1268,"word":"little","star":false,"pos":"形・副","meaning":"①（形）小さい、かわいらしい、幼い     【活用】 little - less - least\n②（副）※a little ～　少し～    ※little by little  少しずつ","example":"①We found a little dog under the tree.\n②I’m a little busy now.","circle":false},
  {"no":1269,"word":"live","star":true,"pos":"動","meaning":"住んでいる、生きている","example":"I have lived in Kobe since then.","circle":false},
  {"no":1270,"word":"living","star":false,"pos":"名・形","meaning":"（名）生活　（形）生きている","example":"We should be kind to all living things.","circle":true},
  {"no":1271,"word":"living room","star":false,"pos":"名","meaning":"居間、リビングルーム","example":"I go to the living room when I want to watch TV.","circle":false},
  {"no":1272,"word":"local","star":false,"pos":"形","meaning":"地元の","example":"We want to know more about the local foods in Tamba.","circle":false},
  {"no":1273,"word":"lock","star":false,"pos":"動","meaning":"かぎを掛ける","example":"Please lock the door when you leave the room.","circle":false},
  {"no":1274,"word":"locker","star":false,"pos":"名","meaning":"ロッカー","example":"American high school students have their own lockers.","circle":true},
  {"no":1275,"word":"London","star":false,"pos":"名","meaning":"ロンドン","example":"London is one of the cities I want to visit.","circle":false},
  {"no":1276,"word":"lonely","star":false,"pos":"形","meaning":"ひとりぼっちの、さびしい","example":"I felt lonely when I visited America by myself.","circle":false},
  {"no":1277,"word":"long","star":true,"pos":"形・副","meaning":"長い（く） 　※for a long time　長い間","example":"Fireworks have a long history in Japan.","circle":false},
  {"no":1278,"word":"look","star":true,"pos":"動","meaning":"①（注意してよく）見る　\n②（外見が）～に見える\n※look at ～　～を（注意して）見る　look for ～　～を探す　\nlook forward to ～ ～を楽しみに待つ  look like ～　～のように見える","example":"①Let's look at two examples.　\n②You look happy.","circle":false},
  {"no":1279,"word":"lose","star":false,"pos":"動","meaning":"失う、なくす  ※lose a game ゲームに負ける　\n【活用】 lose - lost - lost","example":"I lost my umbrella again.","circle":false},
  {"no":1280,"word":"loss","star":false,"pos":"名","meaning":"失うこと、喪失","example":"I heard your dog died.  I'm sorry for your loss.","circle":true},
  {"no":1281,"word":"lot","star":false,"pos":"名","meaning":"※a lot of ～又はlots of ～　たくさんの～　　a lot　たくさん、とても","example":"I had a lot of fun.","circle":false},
  {"no":1282,"word":"loud","star":false,"pos":"形","meaning":"（声が）大きい","example":"Our teacher spoke in a loud voice.","circle":false},
  {"no":1283,"word":"loudly","star":false,"pos":"副","meaning":"大声で","example":"We said goodbye loudly.","circle":false},
  {"no":1284,"word":"love","star":true,"pos":"動・名","meaning":"愛（する）、～が大好きである   ※I'd love to.　喜んで","example":"I love Japanese food.","circle":false},
  {"no":1285,"word":"lovely","star":false,"pos":"形","meaning":"すてきな、美しい","example":"You can see a lovely night view from the top of Mt. Rokko.","circle":true},
  {"no":1286,"word":"low","star":false,"pos":"形","meaning":"低い","example":"That wall is very low.","circle":false},
  {"no":1287,"word":"luck","star":true,"pos":"名","meaning":"幸運、運   　　　　※Good luck!　幸運を","example":"Good luck.","circle":false},
  {"no":1288,"word":"luckily","star":false,"pos":"副","meaning":"幸運にも","example":"Luckily, the weather was nice on the day.","circle":true},
  {"no":1289,"word":"lucky","star":false,"pos":"形","meaning":"運のよい、幸運な","example":"I was lucky to meet my favorite singer.","circle":false},
  {"no":1290,"word":"luggage","star":false,"pos":"名","meaning":"手荷物","example":"Please put your luggage here.","circle":true},
  {"no":1291,"word":"lunch","star":true,"pos":"名","meaning":"昼食、弁当","example":"We have lunch at noon.","circle":false},
  {"no":1292,"word":"lunch break","star":false,"pos":"名","meaning":"昼休み","example":"We sometimes play tennis during lunch break.","circle":false},
  {"no":1293,"word":"lunchbox","star":false,"pos":"名","meaning":"弁当箱","example":"My father washes his lunchbox every day.","circle":true},
  {"no":1294,"word":"machine","star":false,"pos":"名","meaning":"機械","example":"Robots are machines.","circle":false},
  {"no":1295,"word":"magazine","star":false,"pos":"名","meaning":"雑誌","example":"We collect newspapers and magazines for recycling.","circle":false},
  {"no":1296,"word":"magic","star":false,"pos":"名","meaning":"魔法、ふしぎな力","example":"I'm interested in magic.","circle":false},
  {"no":1297,"word":"magnet","star":true,"pos":"名","meaning":"磁石","example":"Use this magnet to put the picture up on the blackboard.","circle":true},
  {"no":1298,"word":"mailbox","star":false,"pos":"名","meaning":"郵便ポスト、郵便受け","example":"Could you get the letters from the mailbox?","circle":false},
  {"no":1299,"word":"main","star":false,"pos":"形","meaning":"主な、主要な","example":"I have two main reasons.","circle":false},
  {"no":1300,"word":"major","star":false,"pos":"形","meaning":"（他と比べて）大きな、主要な、重要な","example":"Some major sports events are held in Hyogo.","circle":false}
];
