const WORDS10 = [
  {"no":901,"word":"gap","star":false,"pos":"名","meaning":"すき間、へだたり","example":"Be careful!  There is a gap.","circle":true},
  {"no":902,"word":"garage","star":false,"pos":"名","meaning":"車庫、ガレージ","example":"My father keeps his car in the garage.","circle":false},
  {"no":903,"word":"garden","star":true,"pos":"名","meaning":"庭、庭園","example":"There are many flowers in the garden.","circle":false},
  {"no":904,"word":"gas","star":false,"pos":"名","meaning":"ガス、気体","example":"The gas station is near my house.","circle":false},
  {"no":905,"word":"gate","star":false,"pos":"名","meaning":"門、出入り口","example":"Please close the gate.","circle":false},
  {"no":906,"word":"gather","star":false,"pos":"動","meaning":"集める、集まる","example":"Let's gather here at seven.","circle":false},
  {"no":907,"word":"general","star":false,"pos":"形","meaning":"一般的な、全体の","example":"In general, I like music.","circle":false},
  {"no":908,"word":"gentle","star":false,"pos":"形","meaning":"やさしい、穏やかな","example":"He is a gentle person.","circle":false},
  {"no":909,"word":"gentleman","star":false,"pos":"名","meaning":"紳士、男性","example":"That gentleman is my uncle.","circle":false},
  {"no":910,"word":"get","star":true,"pos":"動","meaning":"得る、手に入れる、～になる、着く","example":"I got a new bike.","circle":false},
  {"no":911,"word":"gift","star":false,"pos":"名","meaning":"贈り物、才能","example":"I got a birthday gift from my parents.","circle":false},
  {"no":912,"word":"girl","star":true,"pos":"名","meaning":"少女、女の子","example":"That girl is my sister.","circle":false},
  {"no":913,"word":"give","star":true,"pos":"動","meaning":"与える、あげる","example":"Please give me some water.","circle":false},
  {"no":914,"word":"glad","star":false,"pos":"形","meaning":"うれしい、喜んで","example":"I'm glad to see you.","circle":false},
  {"no":915,"word":"glass","star":false,"pos":"名","meaning":"グラス、ガラス","example":"There is some water in the glass.","circle":false},
  {"no":916,"word":"go","star":true,"pos":"動","meaning":"行く、進む","example":"I go to school by bike.","circle":false},
  {"no":917,"word":"goal","star":false,"pos":"名","meaning":"目標、ゴール","example":"My goal is to be a scientist.","circle":false},
  {"no":918,"word":"gold","star":false,"pos":"名","meaning":"金、金色","example":"The ring is made of gold.","circle":false},
  {"no":919,"word":"good","star":true,"pos":"形","meaning":"よい、上手な","example":"She is good at tennis.","circle":false},
  {"no":920,"word":"government","star":false,"pos":"名","meaning":"政府","example":"The government made a new rule.","circle":false},
  {"no":921,"word":"grade","star":false,"pos":"名","meaning":"学年、成績","example":"What grade are you in?","circle":false},
  {"no":922,"word":"graduate","star":false,"pos":"動","meaning":"卒業する","example":"I graduated from high school last year.","circle":false},
  {"no":923,"word":"grand","star":false,"pos":"形","meaning":"壮大な、立派な","example":"We saw a grand building.","circle":false},
  {"no":924,"word":"grandfather","star":false,"pos":"名","meaning":"祖父","example":"My grandfather lives in Kyoto.","circle":false},
  {"no":925,"word":"grandmother","star":false,"pos":"名","meaning":"祖母","example":"My grandmother likes cooking.","circle":false},
  {"no":926,"word":"grass","star":false,"pos":"名","meaning":"草、芝生","example":"The grass is green.","circle":false},
  {"no":927,"word":"great","star":true,"pos":"形","meaning":"すばらしい、大きな","example":"You did a great job.","circle":false},
  {"no":928,"word":"green","star":true,"pos":"形","meaning":"緑の、環境にやさしい","example":"The leaves are green.","circle":false},
  {"no":929,"word":"ground","star":false,"pos":"名","meaning":"地面、土地","example":"The ball fell to the ground.","circle":false},
  {"no":930,"word":"group","star":false,"pos":"名","meaning":"集団、グループ","example":"We worked in a group.","circle":false},
  {"no":931,"word":"grow","star":false,"pos":"動","meaning":"成長する、育てる","example":"Plants grow quickly in summer.","circle":false},
  {"no":932,"word":"guess","star":false,"pos":"動","meaning":"推測する、言い当てる","example":"Can you guess the answer?","circle":false},
  {"no":933,"word":"guest","star":false,"pos":"名","meaning":"客、招
