const WORDS14 = [
  {"no":1301,"word":"make","star":true,"pos":"動","meaning":"①作る　　　　　　　　　【活用】 make - made - made\n②～を…にする　　※be made from（of） ～　　～から作られている","example":"①I make a birthday cake for my mother every year.\n②This song always makes me happy.","circle":false},
  {"no":1302,"word":"maker","star":false,"pos":"名","meaning":"制作者","example":"The violin was made by a famous violin maker.","circle":false},
  {"no":1303,"word":"Malaysia","star":false,"pos":"名","meaning":"マレーシア","example":"I have never been to Malaysia.","circle":false},
  {"no":1304,"word":"male","star":false,"pos":"名・形","meaning":"雄（の）、男性（の）","example":"I have a male cat at home.","circle":true},
  {"no":1305,"word":"man","star":false,"pos":"名","meaning":"（大人の）男性、男（の人）    【複数】 men","example":"Who's that man?  I don't know him.","circle":false},
  {"no":1306,"word":"manager","star":false,"pos":"名","meaning":"経営者、園長","example":"I'm the manager of this zoo.","circle":false},
  {"no":1307,"word":"mango","star":false,"pos":"名","meaning":"マンゴー","example":"Most mangos come from foreign countries.","circle":true},
  {"no":1308,"word":"manner","star":false,"pos":"名","meaning":"行儀、マナー","example":"It is bad manners to talk while you are eating something.","circle":false},
  {"no":1309,"word":"many","star":true,"pos":"名・代・形","meaning":"多く（の）、たくさん（の）　　【活用】 many - more - most","example":"Last year I visited many places.","circle":false},
  {"no":1310,"word":"map","star":true,"pos":"名","meaning":"地図","example":"Please find the country on this map.","circle":false},
  {"no":1311,"word":"marathon","star":true,"pos":"名","meaning":"マラソン","example":"Have you run a marathon before?","circle":true},
  {"no":1312,"word":"March","star":true,"pos":"名","meaning":"３月","example":"March is the end of the school year in Japan.","circle":false},
  {"no":1313,"word":"march","star":false,"pos":"動・名","meaning":"（動）ずんずん歩く　（名）行進、マーチ","example":"We practiced a march for our band's performance.","circle":true},
  {"no":1314,"word":"mark","star":false,"pos":"名","meaning":"印、マーク","example":"Have you ever seen this mark?","circle":false},
  {"no":1315,"word":"marker","star":true,"pos":"名","meaning":"マーカーペン、マジックペン","example":"May I borrow a marker to write the address?","circle":true},
  {"no":1316,"word":"market","star":false,"pos":"名","meaning":"市、市場","example":"I'll go to the market to get some fresh fish.","circle":false},
  {"no":1317,"word":"married","star":false,"pos":"形","meaning":"結婚している","example":"She is married to her old friend.","circle":false},
  {"no":1318,"word":"marry","star":false,"pos":"動","meaning":"結婚する","example":"My mother married when she was 25 years old.","circle":false},
  {"no":1319,"word":"martial arts","star":false,"pos":"名","meaning":"武道、武術（複数形で使う）","example":"Both judo and kendo are Japanese martial arts.","circle":true},
  {"no":1320,"word":"mascot","star":false,"pos":"名","meaning":"マスコット","example":"Habatan is the mascot of Hyogo Prefecture.","circle":true},
  {"no":1321,"word":"mask","star":false,"pos":"名","meaning":"お面、マスク","example":"People wear masks in Japan when they have a cold.","circle":false},
  {"no":1322,"word":"master","star":false,"pos":"名","meaning":"主人","example":"I am the master of this house.","circle":false},
  {"no":1323,"word":"match","star":false,"pos":"名","meaning":"試合","example":"I didn't win my kendo match yesterday.","circle":false},
  {"no":1324,"word":"material","star":false,"pos":"名","meaning":"材料、原料","example":"What materials do you need to make this doll?","circle":false},
  {"no":1325,"word":"math","star":true,"pos":"名","meaning":"数学（mathematicsを短くした形）","example":"Can you help me with math homework?","circle":false},
  {"no":1326,"word":"matter","star":false,"pos":"名","meaning":"事柄、困ったこと　　※What's the matter?　どうしたのですか","example":"What's the matter?","circle":false},
  {"no":1327,"word":"May","star":true,"pos":"名","meaning":"５月","example":"I was born in May.","circle":false},
  {"no":1328,"word":"may","star":false,"pos":"助","meaning":"①～してもよい　\n②～かもしれない、たぶん～だろう \n※May I ～?　～してもよいですか\nMay I help you?　 いらっしゃいませ","example":"①May I speak to Paul, please?\n②We may have some rain tomorrow.","circle":false},
  {"no":1329,"word":"maybe","star":false,"pos":"副","meaning":"たぶん、もしかすると","example":"Maybe I will go with you.","circle":false},
  {"no":1330,"word":"mayonnaise","star":false,"pos":"名","meaning":"マヨネーズ","example":"Do you want mayonnaise on your sandwich?","circle":true},
  {"no":1331,"word":"mayor","star":false,"pos":"名","meaning":"市（町、村）長","example":"The mayor of this city went to this high school.","circle":true},
  {"no":1332,"word":"me","star":true,"pos":"代","meaning":"私を、私に　　　※Me, too. 私も","example":"Could you ask him to call me back?","circle":false},
  {"no":1333,"word":"meal","star":false,"pos":"名","meaning":"食事","example":"Communication during meal time is very important.","circle":false},
  {"no":1334,"word":"mean","star":false,"pos":"動","meaning":"意味する、～の意味である　　  【活用】mean - meant - meant","example":"What does this word mean?","circle":false},
  {"no":1335,"word":"meaning","star":false,"pos":"名","meaning":"意味","example":"A word often has many meanings.","circle":false},
  {"no":1336,"word":"meat","star":false,"pos":"名","meaning":"肉","example":"I like fish better than meat.","circle":false},
  {"no":1337,"word":"mechanical pencil","star":false,"pos":"名","meaning":"シャープペンシル","example":"I started to use mechanical pencils in junior high school.","circle":true},
  {"no":1338,"word":"medal","star":false,"pos":"名","meaning":"メダル","example":"I got the gold medal in a soccer tournament last fall.","circle":false},
  {"no":1339,"word":"media","star":false,"pos":"名","meaning":"マスメディア、媒体","example":"He gets a lot of attention from the media.","circle":false},
  {"no":1340,"word":"medical","star":false,"pos":"形","meaning":"医学の","example":"There are some medical books in the library.","circle":false},
  {"no":1341,"word":"medicine","star":false,"pos":"名","meaning":"薬、医薬","example":"The doctor gave me some medicine.","circle":false},
  {"no":1342,"word":"medium","star":false,"pos":"名・形","meaning":"中間（の）","example":"A: What size of T-shirt do you wear?  B: Medium.","circle":false},
  {"no":1343,"word":"meet","star":true,"pos":"動","meaning":"会う、出会う　　※Nice to meet you.　はじめまして\n【活用】 meet - met - met","example":"She wants to meet her British friend.","circle":false},
  {"no":1344,"word":"meeting","star":false,"pos":"名","meaning":"集まり、会議","example":"There is no club meeting after school today.","circle":false},
  {"no":1345,"word":"melody","star":false,"pos":"名","meaning":"メロディー、旋律","example":"In music class, we sang a beautiful melody.","circle":true},
  {"no":1346,"word":"melon","star":true,"pos":"名","meaning":"メロン","example":"Melon is an expensive fruit in Japan.","circle":true},
  {"no":1347,"word":"melt","star":false,"pos":"動","meaning":"とける","example":"The ice is melting under the sun.","circle":false},
  {"no":1348,"word":"member","star":false,"pos":"名","meaning":"会員、メンバー","example":"He's a member of a basketball team.","circle":false},
  {"no":1349,"word":"memorial","star":false,"pos":"名・形","meaning":"（名）記念する物　（形）記念の、追悼の","example":"There is a memorial for victims of the war in the park.","circle":true},
  {"no":1350,"word":"memory","star":true,"pos":"名","meaning":"思い出、記憶","example":"I have good memories of my stay in Australia.","circle":false},
  {"no":1351,"word":"menu","star":false,"pos":"名","meaning":"献立表、メニュー","example":"There are many restaurants with English menus.","circle":false},
  {"no":1352,"word":"merit","star":false,"pos":"名","meaning":"長所、よい点","example":"What are the merits of this book?","circle":false},
  {"no":1353,"word":"message","star":false,"pos":"名","meaning":"伝えたいこと、メッセージ、伝言\n※leave(take) a message 伝言を残す（受け取る）","example":"Will you give him a message, please?","circle":false},
  {"no":1354,"word":"meter","star":false,"pos":"名","meaning":"メートル","example":"I ran about 100 meters to catch the bus.","circle":false},
  {"no":1355,"word":"method","star":false,"pos":"名","meaning":"方法、方式","example":"There are many methods to practice English.","circle":true},
  {"no":1356,"word":"Mexico","star":false,"pos":"名","meaning":"メキシコ","example":"Mexico and the U.S. share a border.","circle":true},
  {"no":1357,"word":"microwave oven","star":false,"pos":"名","meaning":"電子レンジ（microwave のみでもよい）","example":"You can cook many things in a microwave oven.","circle":true},
  {"no":1358,"word":"mid","star":false,"pos":"形","meaning":"中間の　　※mid-term exam  中間考査","example":"I'll do my best in the mid-term exam.","circle":true},
  {"no":1359,"word":"middle","star":false,"pos":"名","meaning":"真ん中、中間　　　 ※in the middle of ～ ～の真ん中に","example":"The festival was held in the middle of October.","circle":false},
  {"no":1360,"word":"midnight","star":false,"pos":"名","meaning":"夜の１２時","example":"I woke up at midnight.","circle":false},
  {"no":1361,"word":"might","star":false,"pos":"助","meaning":"mayの過去形","example":"You might be able to see the star tonight.","circle":true},
  {"no":1362,"word":"mild","star":false,"pos":"形","meaning":"おだやかな","example":"The weather is very mild today.","circle":true},
  {"no":1363,"word":"mile","star":false,"pos":"名","meaning":"マイル（約1.6km）","example":"I run about 2 miles every morning.","circle":true},
  {"no":1364,"word":"milk","star":true,"pos":"名","meaning":"牛乳、ミルク","example":"I usually have milk for breakfast.","circle":false},
  {"no":1365,"word":"million","star":false,"pos":"名・形","meaning":"１００万（の）","example":"Over five million people live in Hyogo.","circle":false},
  {"no":1366,"word":"mind","star":false,"pos":"名","meaning":"心　　　※keep ～ in mind  　～を心にとめておく","example":"I will keep this story in mind.","circle":false},
  {"no":1367,"word":"mine","star":false,"pos":"代","meaning":"私のもの　　　　　※a friend of mine 私の友人（の１人）","example":"That book is mine.","circle":false},
  {"no":1368,"word":"mineral water","star":true,"pos":"名","meaning":"ミネラルウォーター","example":"You should drink mineral water in foreign countries.","circle":true},
  {"no":1369,"word":"minute","star":false,"pos":"名","meaning":"①（時間の）分　\n②ちょっとの間　　※Just a minute.　ちょっと待って","example":"①We still have a few minutes before the lesson.\n②Would you please wait for a minute?","circle":false},
  {"no":1370,"word":"mirror","star":false,"pos":"名","meaning":"鏡","example":"I looked in the mirror to check my face.","circle":false},
  {"no":1371,"word":"miss","star":false,"pos":"動","meaning":"①（機会などを）逃す、（乗り物に）乗り遅れる\n②～がいなくてさみしい","example":"①I missed the bus this morning.\n②I really miss you.","circle":false},
  {"no":1372,"word":"mission","star":false,"pos":"名","meaning":"使節、使命、任務","example":"My mission is to help people in need.","circle":true},
  {"no":1373,"word":"mistake","star":false,"pos":"名","meaning":"誤り、間違い　   ※make a mistake　間違う","example":"I think you made a mistake.","circle":false},
  {"no":1374,"word":"misunderstand","star":false,"pos":"動","meaning":"誤解する  【活用】 misunderstand - misunderstood - misunderstood","example":"I am afraid you misunderstand my idea.","circle":true},
  {"no":1375,"word":"mix","star":false,"pos":"動","meaning":"混ぜる","example":"What color do you get if you mix green and red?","circle":false},
  {"no":1376,"word":"mobile phone","star":false,"pos":"名","meaning":"携帯電話（cellphone とも言う）","example":"We can do many things with mobile phones.","circle":true},
  {"no":1377,"word":"model","star":false,"pos":"名","meaning":"模型","example":"Like many young boys, he likes to build model cars.","circle":false},
  {"no":1378,"word":"modern","star":false,"pos":"形","meaning":"現代の、現代の","example":"Modern life is very convenient.","circle":true},
  {"no":1379,"word":"mom","star":false,"pos":"名","meaning":"ママ、お母さん","example":"Mom, what time is it now?","circle":false},
  {"no":1380,"word":"moment","star":false,"pos":"名","meaning":"瞬間　　　※Just a moment.  ちょと待ってください","example":"That was the best moment in my life.","circle":false},
  {"no":1381,"word":"Monday","star":true,"pos":"名","meaning":"月曜日","example":"We have a meeting on Monday.","circle":false},
  {"no":1382,"word":"money","star":false,"pos":"名","meaning":"お金","example":"I need money to buy new DVDs.","circle":false},
  {"no":1383,"word":"monkey","star":true,"pos":"名","meaning":"サル","example":"I saw monkeys in the zoo.","circle":false},
  {"no":1384,"word":"monster","star":false,"pos":"名","meaning":"怪物","example":"People believed that a monster lived in the forest.","circle":true},
  {"no":1385,"word":"month","star":true,"pos":"名","meaning":"月、ひと月（間）","example":"He stayed there for one month.","circle":false},
  {"no":1386,"word":"monument","star":false,"pos":"名","meaning":"記念碑","example":"The monument was built to remember the earthquake.","circle":true},
  {"no":1387,"word":"moon","star":false,"pos":"名","meaning":"（天体の）月","example":"The moon will be beautiful tonight.","circle":false},
  {"no":1388,"word":"moral education","star":true,"pos":"名","meaning":"（教科の）道徳","example":"We have a class for moral education every week.","circle":true},
  {"no":1389,"word":"more","star":false,"pos":"形・副\n名・代","meaning":"（形）（more ～で）もっと～　（副）もっと多く（many, muchの比較級）\n※more than ～　～以上に\n（名・代）もっと多くの物（人・事・量）","example":"①Toyooka had more snow this year than last year.\n②Could you tell me more?","circle":false},
  {"no":1390,"word":"moreover","star":false,"pos":"副","meaning":"さらに、そのうえ","example":"He is smart.  Moreover, he is kind.","circle":true},
  {"no":1391,"word":"morning","star":true,"pos":"名","meaning":"朝、午前　　　※Good morning.　おはよう","example":"Good morning, Mr. Tanaka.","circle":false},
  {"no":1392,"word":"most","star":false,"pos":"形・副\n名・代","meaning":"（形）（しばしば the most ～で）最も～　\n（副）最も多く（many, muchの最上級）\n（名・代）大部分、たいてい　　※most of ～　～の大部分","example":"①Baseball is one of the most popular sports in Japan.\n②Most of us agreed with this plan.","circle":false},
  {"no":1393,"word":"mother","star":true,"pos":"名","meaning":"母、母親","example":"This is my mother.","circle":false},
  {"no":1394,"word":"mountain","star":true,"pos":"名","meaning":"山","example":"Mt. Rokko is a famous mountain in Hyogo.","circle":false},
  {"no":1395,"word":"mouse","star":true,"pos":"名","meaning":"ネズミ","example":"Mickey is the most famous mouse in the world.","circle":false},
  {"no":1396,"word":"mouth","star":true,"pos":"名","meaning":"口","example":"Open your mouth.","circle":false},
  {"no":1397,"word":"move","star":false,"pos":"動","meaning":"①動く、移動する　\n②（心を）動かす、感動させる\n③引っ越す","example":"①She was so tired that she could not move.\n②I was moved by the speech.\n③My family moved to this town last year.","circle":false},
  {"no":1398,"word":"movement","star":false,"pos":"名","meaning":"動き、（社会的）運動","example":"There was a big movement against war.","circle":false},
  {"no":1399,"word":"movie","star":false,"pos":"名","meaning":"映画","example":"I like watching movies in English.","circle":false},
  {"no":1400,"word":"movie theater","star":false,"pos":"名","meaning":"映画館","example":"The movie theater is next to the bank.","circle":false}
];
