const WORDS21 = [
  {"no":2001,"word":"so","star":false,"pos":"接・副","meaning":"①とても    　※so ～ that … (can't) 　とても～なので…（できない） \n②そのように\n③だから、それで","example":"①I was so sleepy that I went to bed early.\n②I think so.\n③He wanted to win the game, so he practiced harder.","circle":false},
  {"no":2002,"word":"soap","star":false,"pos":"名","meaning":"せっけん","example":"Please wash your hands carefully with soap.","circle":true},
  {"no":2003,"word":"soccer","star":true,"pos":"名","meaning":"サッカー","example":"Soccer is my favorite sport.","circle":false},
  {"no":2004,"word":"social","star":false,"pos":"形","meaning":"社会の、社会的な","example":"Food waste is a social problem.","circle":true},
  {"no":2005,"word":"social media","star":false,"pos":"名","meaning":"ソーシャル・メディア","example":"We can get a lot of information on social media.","circle":true},
  {"no":2006,"word":"social studies","star":true,"pos":"名","meaning":"社会科","example":"My favorite subject is social studies.","circle":false},
  {"no":2007,"word":"society","star":false,"pos":"名","meaning":"社会","example":"She wants to change the society.","circle":false},
  {"no":2008,"word":"sock","star":false,"pos":"名","meaning":"靴下","example":"I don't like wear socks at home.","circle":true},
  {"no":2009,"word":"soda","star":false,"pos":"名","meaning":"ソーダ水","example":"I like to drink soda with lemon.","circle":true},
  {"no":2010,"word":"sofa","star":false,"pos":"名","meaning":"ソファー","example":"I like sitting on a sofa and watching TV.","circle":false},
  {"no":2011,"word":"soft","star":true,"pos":"形","meaning":"やわらかい","example":"Is your bed too soft for you?","circle":false},
  {"no":2012,"word":"softball","star":false,"pos":"名","meaning":"ソフトボール","example":"If it's sunny, we'll play softball tomorrow.","circle":false},
  {"no":2013,"word":"softly","star":false,"pos":"副","meaning":"優しく、穏やかに、静かに","example":"The lady always speaks to me very softly.","circle":true},
  {"no":2014,"word":"soil","star":false,"pos":"名","meaning":"土壌、土","example":"The soil around here is good for growing rice.","circle":true},
  {"no":2015,"word":"solar","star":false,"pos":"形","meaning":"太陽の","example":"Solar energy is one of the clean energies.","circle":false},
  {"no":2016,"word":"soldier","star":false,"pos":"名","meaning":"兵士、軍人","example":"My grandmother's father was a soldier.","circle":true},
  {"no":2017,"word":"solution","star":false,"pos":"名","meaning":"解決策","example":"Education is one of the solutions to change the world.","circle":false},
  {"no":2018,"word":"solve","star":false,"pos":"動","meaning":"解決する","example":"There are three ways to solve the problem.","circle":false},
  {"no":2019,"word":"some","star":false,"pos":"代・形","meaning":"いくつか（の）、いくらか（の）\n※Some ～,　and others…　～する人がいれば、・・・する人もいる","example":"I have some friends in America.","circle":false},
  {"no":2020,"word":"somebody","star":false,"pos":"代","meaning":"誰か、ある人","example":"Somebody found my textbook.","circle":true},
  {"no":2021,"word":"someday","star":false,"pos":"副","meaning":"いつか、そのうち","example":"I want to study abroad someday.","circle":false},
  {"no":2022,"word":"somehow","star":false,"pos":"副","meaning":"何らかの形で、何とかして、どうにかして","example":"I didn't study hard, but somehow I passed the test.","circle":true},
  {"no":2023,"word":"someone","star":false,"pos":"代","meaning":"だれか","example":"I'm looking for someone who can play baseball.","circle":false},
  {"no":2024,"word":"something","star":false,"pos":"代","meaning":"何か","example":"I want something to drink.","circle":false},
  {"no":2025,"word":"sometime","star":false,"pos":"副","meaning":"いつか","example":"I want to live in a foreign country sometime.","circle":true},
  {"no":2026,"word":"sometimes","star":true,"pos":"副","meaning":"ときどき","example":"I sometimes visit my grandmother.","circle":false},
  {"no":2027,"word":"somewhere","star":false,"pos":"副","meaning":"どこかに、どこかへ、どこかで","example":"Let's go somewhere this Sunday.","circle":false},
  {"no":2028,"word":"son","star":false,"pos":"名","meaning":"息子","example":"Our teacher has two sons.","circle":false},
  {"no":2029,"word":"song","star":false,"pos":"名","meaning":"歌","example":"We enjoyed singing songs together.","circle":false},
  {"no":2030,"word":"soon","star":false,"pos":"副","meaning":"すぐに、まもなく","example":"Spring will come soon.","circle":false},
  {"no":2031,"word":"sore","star":false,"pos":"形","meaning":"痛い","example":"Yesterday I ran a lot, so today my legs are sore.","circle":true},
  {"no":2032,"word":"sore throat","star":false,"pos":"名","meaning":"のどの痛み","example":"I have a sore throat.","circle":false},
  {"no":2033,"word":"sorry","star":true,"pos":"形・間","meaning":"すまなく思って、残念に思って　※I'm sorry.  ごめんなさい","example":"I'm sorry I'm late.","circle":false},
  {"no":2034,"word":"sound","star":false,"pos":"動・名","meaning":"①（動）～に聞こえる　　※sound like ～　～のように聞こえる\n②（名）音","example":"①A: I bought a new bike.  B: That sounds nice.\n②Don't make a sound.","circle":false},
  {"no":2035,"word":"soup","star":true,"pos":"名","meaning":"スープ","example":"I have rice and miso soup for breakfast every morning.","circle":false},
  {"no":2036,"word":"sour","star":true,"pos":"名","meaning":"酸っぱい、酸味のきいた","example":"The lemon tasted very sour.","circle":true},
  {"no":2037,"word":"south","star":false,"pos":"名・形・副","meaning":"南（の、へ）、南方","example":"Many birds fly south in winter.","circle":false},
  {"no":2038,"word":"South Africa","star":false,"pos":"名","meaning":"南アフリカ共和国","example":"Our ALT is from South Africa.","circle":true},
  {"no":2039,"word":"southern","star":false,"pos":"形","meaning":"南の","example":"Awaji Island is in the southern part of Hyogo.","circle":true},
  {"no":2040,"word":"souvenir","star":false,"pos":"名","meaning":"みやげ","example":"I saw many souvenir shops in Tokyo.","circle":false},
  {"no":2041,"word":"soy sauce","star":false,"pos":"名","meaning":"しょうゆ","example":"Good soy sauce is produced in Tatsuno.","circle":true},
  {"no":2042,"word":"soybean","star":false,"pos":"名","meaning":"大豆","example":"Tofu is made from soybeans.","circle":false},
  {"no":2043,"word":"space","star":false,"pos":"名","meaning":"①空間　\n②宇宙","example":"①There is not enough space for all these books.\n②She is the first woman that went to space.","circle":false},
  {"no":2044,"word":"spaghetti","star":true,"pos":"名","meaning":"スパゲッティ","example":"On weekends, I usually have spaghetti for lunch.","circle":true},
  {"no":2045,"word":"Spain","star":false,"pos":"名","meaning":"スペイン","example":"I have never been to Spain.","circle":false},
  {"no":2046,"word":"Spanish","star":false,"pos":"名・形","meaning":"スペインの、スペイン人（の）、スペイン語（の）","example":"I want to learn Spanish.","circle":false},
  {"no":2047,"word":"speak","star":true,"pos":"動","meaning":"話す　　【活用】 speak - spoke - spoken","example":"My sister can speak three languages.","circle":false},
  {"no":2048,"word":"speaker","star":false,"pos":"名","meaning":"話す人","example":"She is a good speaker of English.","circle":false},
  {"no":2049,"word":"special","star":false,"pos":"形","meaning":"特別な","example":"This book is very special to me.","circle":false},
  {"no":2050,"word":"species","star":false,"pos":"名","meaning":"（生物学上の）種（複数形で使う）","example":"We can see some rare species on this island.","circle":true},
  {"no":2051,"word":"specific","star":false,"pos":"形","meaning":"特定の、具体的な","example":"You should write specific reasons for your idea.","circle":true},
  {"no":2052,"word":"speech","star":true,"pos":"名","meaning":"演説、スピーチ      　※make a speech  スピーチをする","example":"I'm going to make a speech about my family.","circle":false},
  {"no":2053,"word":"speed","star":false,"pos":"名","meaning":"スピード、速度","example":"The cat ran at amazing speed.","circle":false},
  {"no":2054,"word":"spell","star":true,"pos":"動","meaning":"（～の語）をつづる","example":"How do you spell “environment”?","circle":false},
  {"no":2055,"word":"spend","star":false,"pos":"動","meaning":"（時間を）過ごす、費やす         【活用】 spend - spent - spent","example":"How do you spend your free time?","circle":false},
  {"no":2056,"word":"spice","star":false,"pos":"名","meaning":"香辛料、スパイス","example":"A lot of spices are used in Indian food.","circle":true},
  {"no":2057,"word":"spicy","star":false,"pos":"形","meaning":"辛い、香辛料のきいた","example":"Indian food is very spicy.","circle":true},
  {"no":2058,"word":"spider","star":true,"pos":"名","meaning":"クモ","example":"I am afraid of spiders.","circle":true},
  {"no":2059,"word":"spirit","star":false,"pos":"名","meaning":"心、精神、気力、勇気","example":"This is our school spirit.","circle":false},
  {"no":2060,"word":"splash","star":false,"pos":"動・名","meaning":"（動）（水などを）はねかける　（名）はね、水しぶき","example":"Children like to splash each other in the pool.","circle":true},
  {"no":2061,"word":"spoon","star":false,"pos":"名","meaning":"スプーン","example":"They don't use spoons when they eat.","circle":false},
  {"no":2062,"word":"sport","star":true,"pos":"名","meaning":"スポーツ","example":"I like playing sports.","circle":false},
  {"no":2063,"word":"sports day","star":false,"pos":"名","meaning":"運動会、体育の日","example":"Our school has sports day in September.","circle":false},
  {"no":2064,"word":"spot","star":false,"pos":"名","meaning":"場所、地点","example":"Mt. Rokko and Mt. Maya are great night view spots.","circle":false},
  {"no":2065,"word":"spread","star":false,"pos":"動","meaning":"広げる、広がる      【活用】 spread - spread - spread","example":"He spread his arms wide.","circle":false},
  {"no":2066,"word":"spring","star":true,"pos":"名","meaning":"春","example":"You can enjoy the cherry blossoms in spring.","circle":false},
  {"no":2067,"word":"square","star":true,"pos":"名・形","meaning":"（名）正方形　（形）正方形の、四角の","example":"My house looks square from this side.","circle":true},
  {"no":2068,"word":"squirrel","star":false,"pos":"名","meaning":"リス","example":"Squirrels are cute animals.","circle":true},
  {"no":2069,"word":"stadium","star":false,"pos":"名","meaning":"競技場","example":"Hyogo has a famous baseball stadium called “Koshien”.","circle":false},
  {"no":2070,"word":"staff","star":false,"pos":"名","meaning":"職員、スタッフ","example":"The school's staff works very hard every day.","circle":true},
  {"no":2071,"word":"stage","star":false,"pos":"名","meaning":"舞台、ステージ","example":"We sang a song on the stage at our school festival.","circle":false},
  {"no":2072,"word":"stairs","star":false,"pos":"名","meaning":"階段（複数形で使う）","example":"She went up the stairs slowly.","circle":false},
  {"no":2073,"word":"stamp","star":false,"pos":"名","meaning":"切手","example":"I need some stamps to send letters.","circle":false},
  {"no":2074,"word":"stand","star":true,"pos":"動・名","meaning":"①（動）立つ、立っている　　　　【活用】 stand - stood - stood\n②（名）（物などを置く）台","example":"①Please stand up.\n②I bought a nice book stand.","circle":false},
  {"no":2075,"word":"standard","star":false,"pos":"名","meaning":"基準","example":"The Japanese standards of living improved after the war.","circle":true},
  {"no":2076,"word":"stapler","star":true,"pos":"名","meaning":"ホッチキス","example":"You can use this stapler for the papers.","circle":true},
  {"no":2077,"word":"star","star":true,"pos":"名","meaning":"星","example":"You can see different stars in different seasons.","circle":false},
  {"no":2078,"word":"start","star":false,"pos":"動","meaning":"始める、始まる","example":"In Japan, school starts in April.","circle":false},
  {"no":2079,"word":"station","star":true,"pos":"名","meaning":"駅、･･･署（所、局）","example":"Let's meet at the station.","circle":false},
  {"no":2080,"word":"stationery","star":true,"pos":"名","meaning":"文房具、事務用品","example":"This shop sells stationary of unique colors and designs.","circle":true},
  {"no":2081,"word":"statue","star":false,"pos":"名","meaning":"像、彫像","example":"Many tourists visit here to see this statue.","circle":true},
  {"no":2082,"word":"stay","star":false,"pos":"動・名","meaning":"滞在（する）、とどまる","example":"I'm going to stay in France for a week.","circle":false},
  {"no":2083,"word":"steak","star":true,"pos":"名","meaning":"ステーキ","example":"The steak he cooked was very delicious.","circle":false},
  {"no":2084,"word":"steal","star":false,"pos":"動","meaning":"盗む　　　　【活用】 steal - stole - stolen","example":"Her watch was stolen.","circle":false},
  {"no":2085,"word":"steam","star":false,"pos":"動・名","meaning":"（動）湯気を立てる　（名）蒸気","example":"In Kinosaki, you can see steam from the bath houses.","circle":true},
  {"no":2086,"word":"step","star":false,"pos":"動・名","meaning":"①（名）段階、（屋外の）階段\n②（動）歩く、踏み出す","example":"①Learning English is just the first step for me.\n②Please step back.","circle":false},
  {"no":2087,"word":"stew","star":false,"pos":"名","meaning":"シチュー","example":"We often cook stew in winter.","circle":true},
  {"no":2088,"word":"stick","star":false,"pos":"動・名","meaning":"①（動）くっつく ※stick to ～ ～にくっつく　\n【活用】 stick - stuck - stuck\n②（名）棒状のもの、杖","example":"①The baby birds tried to stick to their mother.\n②My dog found a stick and brought it to me.","circle":true},
  {"no":2089,"word":"sticky","star":false,"pos":"形","meaning":"ねばねばする、べとべとする、くっつく","example":"Honey is very sticky.","circle":true},
  {"no":2090,"word":"still","star":false,"pos":"副","meaning":"まだ、今でも","example":"The building is very old, but it is still beautiful.","circle":false},
  {"no":2091,"word":"stomach","star":false,"pos":"名","meaning":"胃、腹","example":"I have a pain in my stomach.","circle":false},
  {"no":2092,"word":"stomachache","star":false,"pos":"名","meaning":"胃痛、腹痛","example":"I have a stomachache.","circle":false},
  {"no":2093,"word":"stone","star":false,"pos":"名","meaning":"石","example":"The wall is made of stone.","circle":false},
  {"no":2094,"word":"stop","star":true,"pos":"動・名","meaning":"（動）止める、やめる　（名）中止、停止","example":"You should stop talking when someone speaks.","circle":false},
  {"no":2095,"word":"store","star":false,"pos":"名","meaning":"店","example":"There are a lot of stores along this street.","circle":false},
  {"no":2096,"word":"storm","star":false,"pos":"名","meaning":"嵐","example":"We had a big storm last night.","circle":true},
  {"no":2097,"word":"story","star":false,"pos":"名","meaning":"物語、話","example":"This is a story about a doctor's life.","circle":false},
  {"no":2098,"word":"stove","star":false,"pos":"名","meaning":"ガスレンジ、（料理用の）コンロ、レンジ","example":"Cook the bacon on the stove.","circle":true},
  {"no":2099,"word":"straight","star":true,"pos":"副","meaning":"まっすぐに","example":"Go straight along this street.","circle":false},
  {"no":2100,"word":"strange","star":false,"pos":"形","meaning":"奇妙な","example":"This is a very strange story.","circle":false}
];
