const WORDS18 = [
  {"no":1701,"word":"progress","star":false,"pos":"動・名","meaning":"進歩（する）、発達（する）      ※make progress  進歩する","example":"He made a lot of progress in English.","circle":true},
  {"no":1702,"word":"project","star":false,"pos":"名","meaning":"計画、企画","example":"We're now working on a project in our science class.","circle":false},
  {"no":1703,"word":"promise","star":false,"pos":"動・名","meaning":"約束（する）","example":"I broke my promise.","circle":false},
  {"no":1704,"word":"pronounce","star":false,"pos":"動","meaning":"発音する","example":"It is difficult to pronounce this word.","circle":true},
  {"no":1705,"word":"protect","star":false,"pos":"動","meaning":"保護する、守る","example":"Protect yourself in an emergency.","circle":false},
  {"no":1706,"word":"proud","star":false,"pos":"形","meaning":"～を誇りに思う　　　※be proud of ～　～を誇りに思う","example":"You should be proud of yourself.","circle":false},
  {"no":1707,"word":"provide","star":false,"pos":"動","meaning":"供給する、与える","example":"In this plan, breakfast is also provided.","circle":true},
  {"no":1708,"word":"public","star":false,"pos":"形","meaning":"公の、公共の","example":"Parks and libraries are public places.","circle":false},
  {"no":1709,"word":"publish","star":false,"pos":"動","meaning":"出版する","example":"His new novel will be published next month.","circle":true},
  {"no":1710,"word":"pudding","star":true,"pos":"名","meaning":"プリン","example":"This is the best pudding I've ever had.","circle":true},
  {"no":1711,"word":"pull","star":false,"pos":"動","meaning":"引く","example":"In the festival, many men pull a danjiri around the town.","circle":false},
  {"no":1712,"word":"pumpkin","star":false,"pos":"名","meaning":"カボチャ","example":"Pumpkin is a symbol of Halloween.","circle":true},
  {"no":1713,"word":"puppy","star":false,"pos":"名","meaning":"子犬","example":"I couldn't leave the puppy because it was so cute.","circle":true},
  {"no":1714,"word":"purple","star":true,"pos":"名・形","meaning":"紫色（の）","example":"Sometimes the sky looks purple.","circle":false},
  {"no":1715,"word":"purpose","star":false,"pos":"名","meaning":"目的、つもり","example":"What's the purpose of your visit?","circle":false},
  {"no":1716,"word":"purse","star":false,"pos":"名","meaning":"財布","example":"Oh, I left my purse at home.","circle":true},
  {"no":1717,"word":"push","star":false,"pos":"動","meaning":"押す","example":"Please push this button.","circle":false},
  {"no":1718,"word":"put","star":true,"pos":"動","meaning":"置く、つける　※put on ～　～を身に付ける　【活用】 put - put - put","example":"Put the textbook on the desk.","circle":false},
  {"no":1719,"word":"puzzle","star":false,"pos":"名","meaning":"パズル","example":"That puzzle was very easy for me.","circle":true},
  {"no":1720,"word":"pyramid","star":false,"pos":"名","meaning":"ピラミッド","example":"I want to see the pyramids someday.","circle":true},
  {"no":1721,"word":"quality","star":false,"pos":"名","meaning":"品質　　　※in quality  質的に","example":"Many of the goods in 100 yen shops are good quality.","circle":false},
  {"no":1722,"word":"quantity","star":false,"pos":"名","meaning":"量","example":"This plant needs a large quantity of water.","circle":true},
  {"no":1723,"word":"queen","star":true,"pos":"名","meaning":"女王","example":"The queen is loved by the people of the country.","circle":true},
  {"no":1724,"word":"question","star":false,"pos":"名","meaning":"質問、（試験の）問題","example":"May I ask you a question?","circle":false},
  {"no":1725,"word":"quick","star":false,"pos":"形","meaning":"すばやい、速い","example":"You need to be quick to play basketball.","circle":false},
  {"no":1726,"word":"quickly","star":false,"pos":"副","meaning":"すばやく、速く","example":"The basketball player moves very quickly.","circle":false},
  {"no":1727,"word":"quiet","star":false,"pos":"形","meaning":"静かな、おとなしい","example":"He is very shy and quiet.","circle":false},
  {"no":1728,"word":"quietly","star":false,"pos":"副","meaning":"静かに、黙って","example":"Children were sitting quietly.","circle":false},
  {"no":1729,"word":"quit","star":false,"pos":"動","meaning":"やめる　　【活用】 quit - quit - quit","example":"I should quit eating late at night.","circle":true},
  {"no":1730,"word":"quite","star":false,"pos":"副","meaning":"とても、本当に","example":"Japanese anime is quite popular in foreign countries.","circle":false},
  {"no":1731,"word":"quiz","star":false,"pos":"名","meaning":"テスト、クイズ","example":"We have a quiz every morning.","circle":false},
  {"no":1732,"word":"rabbit","star":true,"pos":"名","meaning":"ウサギ","example":"Alice saw a rabbit in the forest.","circle":false},
  {"no":1733,"word":"race","star":false,"pos":"名","meaning":"競争、レース","example":"We have a lot of  races on Sports Day.","circle":true},
  {"no":1734,"word":"racket","star":true,"pos":"名","meaning":"ラケット","example":"You need a racket to play tennis.","circle":false},
  {"no":1735,"word":"radio","star":false,"pos":"名","meaning":"ラジオ","example":"I listen to English on the radio every day.","circle":false},
  {"no":1736,"word":"railroad","star":false,"pos":"名","meaning":"鉄道、線路","example":"My brother knows everything about Japanese railroads.","circle":true},
  {"no":1737,"word":"rain","star":false,"pos":"動・名","meaning":"雨（が降る）","example":"It rained a lot last night.","circle":false},
  {"no":1738,"word":"rain forest","star":false,"pos":"名","meaning":"熱帯雨林","example":"We should protect this rain forest.","circle":false},
  {"no":1739,"word":"rainbow","star":true,"pos":"名","meaning":"虹","example":"I can see a rainbow over the mountains.","circle":false},
  {"no":1740,"word":"raincoat","star":false,"pos":"名","meaning":"レインコート","example":"Take your raincoat.  It's going to rain in the afternoon.","circle":true},
  {"no":1741,"word":"rainwater","star":false,"pos":"名","meaning":"雨水","example":"My grandfather uses rainwater for growing vegetables.","circle":true},
  {"no":1742,"word":"rainy","star":true,"pos":"形","meaning":"雨降りの、雨の多い","example":"If it’s rainy tomorrow, I will stay home.","circle":false},
  {"no":1743,"word":"raise","star":false,"pos":"動","meaning":"あげる","example":"Please raise your hand.","circle":false},
  {"no":1744,"word":"rapidly","star":false,"pos":"副","meaning":"速く、急速に","example":"The temperature will go up rapidly this afternoon.","circle":true},
  {"no":1745,"word":"rare","star":false,"pos":"形","meaning":"①まれな\n②（肉が）生焼けの","example":"①This plant is very rare around here.\n②\"How would you like your steak?\"  \"Rare, please.\"","circle":true},
  {"no":1746,"word":"raw","star":false,"pos":"形","meaning":"生の","example":"My American friend ate raw fish for the first time.","circle":true},
  {"no":1747,"word":"reach","star":false,"pos":"動","meaning":"着く、到着する","example":"We reached the top of the mountain.","circle":false},
  {"no":1748,"word":"read","star":true,"pos":"動","meaning":"読む、読書する　　【活用】 read - read - read","example":"Please read Lesson 9 in the textbook.","circle":false},
  {"no":1749,"word":"reading","star":true,"pos":"名","meaning":"読むこと、読書","example":"Reading is one of my hobbies.","circle":false},
  {"no":1750,"word":"ready","star":false,"pos":"形","meaning":"用意（準備）ができて\n※be ready for ～/to ～　～の（する）用意（準備）ができている","example":"Are you ready?","circle":false},
  {"no":1751,"word":"real","star":false,"pos":"形","meaning":"本当の、本物の","example":"I saw real gold for the first time.","circle":false},
  {"no":1752,"word":"reality","star":false,"pos":"名","meaning":"現実","example":"When I'm reading books, I can forget about reality.","circle":true},
  {"no":1753,"word":"realize","star":false,"pos":"動","meaning":"実感する、理解する","example":"She realized she made a mistake.","circle":false},
  {"no":1754,"word":"really","star":true,"pos":"副","meaning":"本当に、実際に、ほんと、へえー","example":"I'll really miss you.","circle":false},
  {"no":1755,"word":"reason","star":false,"pos":"名","meaning":"理由、わけ","example":"I agree with him.  I have three reasons.","circle":false},
  {"no":1756,"word":"receive","star":false,"pos":"動","meaning":"受け取る、もらう","example":"I received an e-mail from John.","circle":false},
  {"no":1757,"word":"recently","star":false,"pos":"副","meaning":"近ごろ、最近","example":"I recently bought a new phone.","circle":true},
  {"no":1758,"word":"recipe","star":false,"pos":"名","meaning":"（料理などの）作り方、レシピ","example":"This is a recipe for curry and rice.","circle":false},
  {"no":1759,"word":"recognize","star":false,"pos":"動","meaning":"（見たり聞いたりして）わかる、認める","example":"I couldn't recognize her because she looked different.","circle":true},
  {"no":1760,"word":"recommend","star":false,"pos":"動","meaning":"勧める","example":"I recommend this book to learn Japanese cooking.","circle":true},
  {"no":1761,"word":"record","star":false,"pos":"動・名","meaning":"（動）録音する、記録する　（名）記録","example":"I recorded my English speech and listened to it.","circle":true},
  {"no":1762,"word":"recover","star":false,"pos":"動","meaning":"回復する","example":"I was sick last week, but I have recovered now.","circle":true},
  {"no":1763,"word":"rectangle","star":true,"pos":"名","meaning":"長方形","example":"Please draw four lines to make a rectangle.","circle":true},
  {"no":1764,"word":"recycle","star":false,"pos":"動","meaning":"再生する、再利用する","example":"Our town recycles cans and bottles.","circle":false},
  {"no":1765,"word":"recycling","star":false,"pos":"名","meaning":"リサイクル（をすること）","example":"Students collect paper for recycling every month.","circle":false},
  {"no":1766,"word":"red","star":true,"pos":"名・形","meaning":"赤（の）","example":"Red is the team color of the Hiroshima Carp.","circle":false},
  {"no":1767,"word":"red pepper","star":false,"pos":"名","meaning":"トウガラシ","example":"Red pepper is often used in Korean food.","circle":true},
  {"no":1768,"word":"reduce","star":false,"pos":"動","meaning":"減らす、減少させる","example":"We should reduce waste.","circle":false},
  {"no":1769,"word":"refuse","star":false,"pos":"動","meaning":"拒否する、断る","example":"I refused a plastic bag at the convenience store.","circle":false},
  {"no":1770,"word":"regular","star":false,"pos":"形","meaning":"規則的な、定期的な","example":"Our club has regular meetings on Mondays.","circle":false},
  {"no":1771,"word":"relate","star":false,"pos":"動","meaning":"関連づける","example":"Please explain how the two things are related.","circle":true},
  {"no":1772,"word":"relationship","star":false,"pos":"名","meaning":"関係","example":"Our teammates have a good relationship with each other.","circle":true},
  {"no":1773,"word":"relax","star":false,"pos":"動","meaning":"くつろぐ","example":"It is important to relax sometimes.","circle":true},
  {"no":1774,"word":"relaxed","star":false,"pos":"形","meaning":"（人が）くつろいだ","example":"In winter, a kotatsu makes me relaxed.","circle":false},
  {"no":1775,"word":"relay","star":false,"pos":"名","meaning":"リレー競走","example":"On the sports day, I ran with my friends in a relay race.","circle":true},
  {"no":1776,"word":"release","star":false,"pos":"動","meaning":"放出する、（本などを）発売する","example":"The band will release a new album next month.","circle":true},
  {"no":1777,"word":"remain","star":false,"pos":"動・名","meaning":"（動）残る  （名）残り、遺跡","example":"I will remain in Hyogo after high school.","circle":true},
  {"no":1778,"word":"remember","star":false,"pos":"動","meaning":"覚えている、思い出す","example":"I remember my school days.","circle":false},
  {"no":1779,"word":"remind","star":false,"pos":"動","meaning":"思い出させる   ※remind A of B　 AにBを思い出させる","example":"This picture reminds me of my school days.","circle":false},
  {"no":1780,"word":"remove","star":false,"pos":"動","meaning":"取り除く、取り外す","example":"I will remove the dishes from the table.","circle":true},
  {"no":1781,"word":"rent","star":false,"pos":"動","meaning":"有料で借りる","example":"We rented some DVDs from the shop yesterday.","circle":false},
  {"no":1782,"word":"rental","star":false,"pos":"形","meaning":"レンタルの、賃貸しの","example":"In many cities, you can use a rental bicycle.","circle":false},
  {"no":1783,"word":"repair","star":false,"pos":"動","meaning":"修理する、直す","example":"Do you know how to repair a computer?","circle":false},
  {"no":1784,"word":"repeat","star":false,"pos":"動","meaning":"繰り返して言う","example":"Repeat the sentence after me.","circle":true},
  {"no":1785,"word":"reply","star":false,"pos":"動・名","meaning":"返答（する）","example":"Please reply to me within a week.","circle":true},
  {"no":1786,"word":"report","star":false,"pos":"動・名","meaning":"報告（する）、報告書","example":"Write a report about this problem.","circle":false},
  {"no":1787,"word":"reporter","star":false,"pos":"名","meaning":"新聞記者、ニュースレポーター","example":"The reporter wrote a story for the newspaper.","circle":true},
  {"no":1788,"word":"request","star":false,"pos":"動・名","meaning":"（動）求める、要望する　（名）依頼、要望","example":"We requested more holidays from our company.","circle":true},
  {"no":1789,"word":"rescue","star":false,"pos":"動","meaning":"救い出す、救出する","example":"There are robots to rescue people.","circle":false},
  {"no":1790,"word":"research","star":false,"pos":"動・名","meaning":"研究（する）、調査（する）","example":"I'm doing research for my homework.","circle":false},
  {"no":1791,"word":"researcher","star":false,"pos":"名","meaning":"研究者、調査員","example":"Researchers are studying cancer.","circle":true},
  {"no":1792,"word":"resident","star":false,"pos":"名","meaning":"住民、居住者","example":"I am a resident of Hyogo.","circle":true},
  {"no":1793,"word":"respect","star":false,"pos":"動・名","meaning":"尊敬（する）、尊重（する）","example":"I respect him because he works for others.","circle":false},
  {"no":1794,"word":"response","star":false,"pos":"名","meaning":"反応、返答","example":"The teacher gave a quick response to my question.","circle":true},
  {"no":1795,"word":"responsible","star":false,"pos":"形","meaning":"責任感のある、責任がある\n※be responsible for ～ ～に対して責任がある","example":"You should be responsible for yourself.","circle":true},
  {"no":1796,"word":"rest","star":false,"pos":"動・名","meaning":"（動）休む、横になる　（名）休憩","example":"You should rest for some time.","circle":false},
  {"no":1797,"word":"restaurant","star":true,"pos":"名","meaning":"レストラン","example":"This is a good restaurant.","circle":false},
  {"no":1798,"word":"restroom","star":true,"pos":"名","meaning":"（デパート・劇場などの）洗面所、トイレ","example":"Where is the restroom?","circle":false},
  {"no":1799,"word":"result","star":false,"pos":"名","meaning":"結果    　※as a result  その結果として","example":"I got my test results yesterday.","circle":false},
  {"no":1800,"word":"return","star":false,"pos":"動","meaning":"帰る、戻る","example":"We returned to school by bus.","circle":false}
];
