const WORDS24 = [
  {"no":2301,"word":"truck","star":true,"pos":"名","meaning":"トラック、貨物自動車","example":"As a farmer, my father drives a truck to carry vegetables.","circle":true},
  {"no":2302,"word":"true","star":false,"pos":"形","meaning":"本当の、真実の      ※come true  実現する","example":"Finally his dream came true.","circle":false},
  {"no":2303,"word":"truly","star":false,"pos":"副","meaning":"本当に","example":"I truly love my classmates.","circle":true},
  {"no":2304,"word":"trumpet","star":false,"pos":"名","meaning":"トランペット","example":"My friend plays the trumpet in the brass band.","circle":true},
  {"no":2305,"word":"trust","star":false,"pos":"動","meaning":"信頼する、信用する","example":"You can trust him because he always tries his best.","circle":true},
  {"no":2306,"word":"truth","star":false,"pos":"名","meaning":"真実、事実","example":"I want to know what happened.  Tell me the truth.","circle":true},
  {"no":2307,"word":"try","star":true,"pos":"動","meaning":"試す、やってみる　※try to ～ ～しようとする　　try on 試着する","example":"Let's try it again.","circle":false},
  {"no":2308,"word":"T-shirt","star":true,"pos":"名","meaning":"Tシャツ","example":"I like your new T-shirt.  You look cool!","circle":false},
  {"no":2309,"word":"tube","star":false,"pos":"名","meaning":"チューブ（ロンドンの地下鉄のニックネーム）","example":"I visited many places in London by using the tube.","circle":false},
  {"no":2310,"word":"Tuesday","star":true,"pos":"名","meaning":"火曜日","example":"On Tuesdays, I have music class.","circle":false},
  {"no":2311,"word":"tuna","star":false,"pos":"名","meaning":"マグロ","example":"I had tuna at the sushi restaurant.","circle":false},
  {"no":2312,"word":"tunnel","star":false,"pos":"名","meaning":"トンネル","example":"You can go to the town quickly through the tunnel.","circle":true},
  {"no":2313,"word":"Turkey","star":false,"pos":"名","meaning":"トルコ","example":"Turkey was influenced by both Asia and Europe.","circle":true},
  {"no":2314,"word":"turn","star":true,"pos":"動・名","meaning":"①（動）曲がる､回る　　　※turn on ～ ～をつける\nturn off ～ ～を消す　\n②（名）番、順番","example":"①Turn right at the next corner.\n②Now, it is your turn.","circle":false},
  {"no":2315,"word":"turtle","star":false,"pos":"名","meaning":"カメ","example":"There are beautiful turtles in Hawaii.","circle":false},
  {"no":2316,"word":"TV","star":true,"pos":"名","meaning":"テレビ (Televisionの略）","example":"I love watching TV.","circle":false},
  {"no":2317,"word":"twelfth","star":false,"pos":"名・形","meaning":"１２番目（の）","example":"My brother is in the twelfth grade.","circle":false},
  {"no":2318,"word":"twelve","star":true,"pos":"名・形","meaning":"１２（の）","example":"There are twelve pencils in this box.","circle":false},
  {"no":2319,"word":"twentieth","star":false,"pos":"名・形","meaning":"２０番目（の）","example":"The restaurant is on the twentieth floor.","circle":false},
  {"no":2320,"word":"twenty","star":true,"pos":"名・形","meaning":"２０（の）","example":"Twenty students are in this room.","circle":false},
  {"no":2321,"word":"twice","star":false,"pos":"副","meaning":"２度、２回、２倍(に)","example":"I have visited Himeji Castle twice.","circle":false},
  {"no":2322,"word":"twin","star":false,"pos":"名・形","meaning":"（名）双子　（形）双子の","example":"The twins wear the same clothes.","circle":true},
  {"no":2323,"word":"two","star":true,"pos":"名・形","meaning":"２つ（の）","example":"I have two sisters.","circle":false},
  {"no":2324,"word":"type","star":false,"pos":"名","meaning":"種類、タイプ","example":"Do you read this type of book?","circle":false},
  {"no":2325,"word":"typhoon","star":false,"pos":"名","meaning":"台風","example":"In Japan, the typhoon season starts from the end of August.","circle":false},
  {"no":2326,"word":"uh","star":false,"pos":"間","meaning":"あー、えー","example":"A: What do you want to eat for lunch?  B: Uh, akashiyaki.","circle":false},
  {"no":2327,"word":"um","star":false,"pos":"間","meaning":"うーん、えー、あー","example":"A: What do you want to eat?  B: Um, I can eat anything.","circle":true},
  {"no":2328,"word":"umbrella","star":true,"pos":"名","meaning":"傘","example":"Take your umbrella with you.  It may rain this afternoon.","circle":false},
  {"no":2329,"word":"unbelievable","star":false,"pos":"形","meaning":"信じられない、驚くべき","example":"The news about the accident was unbelievable.","circle":true},
  {"no":2330,"word":"uncle","star":false,"pos":"名","meaning":"おじ（父母の兄弟）","example":"I had dinner with my uncle last week.","circle":false},
  {"no":2331,"word":"uncomfortable","star":false,"pos":"形","meaning":"心地よくない","example":"We feel uncomfortable during the rainy season.","circle":true},
  {"no":2332,"word":"under","star":true,"pos":"前","meaning":"～の下に（で）","example":"Let's have lunch under this tree.","circle":false},
  {"no":2333,"word":"underground","star":false,"pos":"名","meaning":"（イギリスの）地下鉄（アメリカでは、subway）","example":"We went to the stadium by the underground.","circle":false},
  {"no":2334,"word":"understand","star":false,"pos":"動","meaning":"理解する　　　　　【活用】 understand - understood - understood","example":"Did you understand this story?","circle":false},
  {"no":2335,"word":"understanding","star":false,"pos":"名","meaning":"理解、知識","example":"Thank you for your understanding.","circle":true},
  {"no":2336,"word":"underwear","star":false,"pos":"名","meaning":"下着","example":"I have to buy new underwear.","circle":false},
  {"no":2337,"word":"unfair","star":false,"pos":"形","meaning":"不公平な、不正な","example":"My brother ate all of the cakes.  It was unfair!","circle":true},
  {"no":2338,"word":"unfortunately","star":false,"pos":"副","meaning":"不幸にも、運悪く、あいにく、残念ながら","example":"Unfortunately, I will not be able to come.","circle":true},
  {"no":2339,"word":"unicycle","star":true,"pos":"名","meaning":"一輪車","example":"I liked riding a unicycle in elementary school.","circle":true},
  {"no":2340,"word":"uniform","star":false,"pos":"名","meaning":"制服、ユニフォーム","example":"I like my school uniform.","circle":false},
  {"no":2341,"word":"unique","star":false,"pos":"形","meaning":"特有の、独特の","example":"I saw some unique animals there.","circle":false},
  {"no":2342,"word":"United Kingdom（U.K.）","star":false,"pos":"名","meaning":"イギリス（正式国名は、The United Kingdom of Great Britain and Northern Ireland）","example":"Football is the most popular sport in the United Kingdom.","circle":false},
  {"no":2343,"word":"United Nations","star":false,"pos":"名","meaning":"国際連合　　※U.N.（UN）(省略語)","example":"The United Nations had a meeting to talk about the problem.","circle":false},
  {"no":2344,"word":"United States","star":false,"pos":"名","meaning":"アメリカ合衆国(正式国名は、the United States of America)\n※U.S.（US）又は U.S.A.（USA） （省略語）","example":"I want to visit the United States to watch baseball.","circle":false},
  {"no":2345,"word":"university","star":false,"pos":"名","meaning":"（総合）大学","example":"I will go to university to study science.","circle":false},
  {"no":2346,"word":"unlucky","star":false,"pos":"形","meaning":"運が悪い","example":"In Japan, four is an unlucky number.","circle":true},
  {"no":2347,"word":"until","star":false,"pos":"前・接","meaning":"～（する）まで","example":"I will not go to bed until I finish this homework.","circle":false},
  {"no":2348,"word":"unusual","star":false,"pos":"形","meaning":"ふつうでない、めずらしい","example":"The weather is very unusual this year.","circle":true},
  {"no":2349,"word":"up","star":true,"pos":"前・副","meaning":"上へ","example":"The plane went up into the sky.","circle":false},
  {"no":2350,"word":"upset","star":false,"pos":"形","meaning":"取り乱した、腹を立てた","example":"I was upset when I heard the news.","circle":true},
  {"no":2351,"word":"upstairs","star":false,"pos":"副","meaning":"二階へ（に）、階上へ（に）","example":"If you want to buy shoes, please go upstairs.","circle":true},
  {"no":2352,"word":"us","star":false,"pos":"代","meaning":"私たちを（に）","example":"Please ask us if you don't know what to do.","circle":false},
  {"no":2353,"word":"use","star":true,"pos":"動","meaning":"使う","example":"You can use my dictionary.","circle":false},
  {"no":2354,"word":"used","star":false,"pos":"動・形","meaning":"①（動）※used to do ～　以前はよく～したものだ\n②（形）使い古した、中古の","example":"①I used to play tennis with my friends on weekends.\n②My father bought a used car.","circle":false},
  {"no":2355,"word":"useful","star":false,"pos":"形","meaning":"役に立つ","example":"The Internet is useful for getting information.","circle":false},
  {"no":2356,"word":"user","star":false,"pos":"名","meaning":"使用者、利用者","example":"This product is very popular and has many users.","circle":true},
  {"no":2357,"word":"usual","star":false,"pos":"形","meaning":"いつもの、ふつうの","example":"Rice with miso soup is my usual breakfast.","circle":true},
  {"no":2358,"word":"usually","star":true,"pos":"副","meaning":"ふつう、たいてい","example":"I usually get up at 6 o'clock.","circle":false},
  {"no":2359,"word":"vacation","star":true,"pos":"名","meaning":"休暇、休み","example":"What are you going to do during summer vacation?","circle":false},

  {"no":2360,"word":"vacuum cleaner（vacuum）","star":false,"pos":"名","meaning":"掃除機","example":"This vacuum cleaner is small but very powerful.","circle":true},
  {"no":2361,"word":"valuable","star":false,"pos":"形","meaning":"高価な、貴重な","example":"What is the most valuable thing to you?","circle":true},
  {"no":2362,"word":"van","star":false,"pos":"名","meaning":"小型トラック、ワゴン車、バン","example":"We traveled around Hokkaido in a van.","circle":true},
  {"no":2363,"word":"variety","star":false,"pos":"名","meaning":"バラエティー、変化に富むこと\n※variety show   バラエティー・ショー    a variety of ～ 様々な～","example":"I watched variety shows on TV yesterday.","circle":false},
  {"no":2364,"word":"various","star":false,"pos":"形","meaning":"いろいろな、さまざまな","example":"Students in the class are from various countries.","circle":true},
  {"no":2365,"word":"vase","star":false,"pos":"名","meaning":"花びん","example":"Let's put these flowers in that vase.","circle":true},
  {"no":2366,"word":"vegetable","star":true,"pos":"名","meaning":"野菜","example":"We have vegetables every day.","circle":false},
  {"no":2367,"word":"vending machine","star":false,"pos":"名","meaning":"自動販売機","example":"You can see a lot of vending machines in Japan.","circle":false},
  {"no":2368,"word":"very","star":true,"pos":"副","meaning":"とても、非常に","example":"I was very happy to see my old friend.","circle":false},
  {"no":2369,"word":"vet","star":true,"pos":"名","meaning":"獣医（veterinarianの略）","example":"My cat was sick, so I took her to the vet.","circle":true},
  {"no":2370,"word":"victim","star":false,"pos":"名","meaning":"犠牲者","example":"We pray for the victims of the earthquake every year.","circle":true},
  {"no":2371,"word":"victory","star":false,"pos":"名","meaning":"勝利、優勝","example":"This victory gave us hope.","circle":false},
  {"no":2372,"word":"video","star":false,"pos":"名","meaning":"ビデオ","example":"Watch this video first.  We will talk about it later.","circle":false},
  {"no":2373,"word":"video game","star":false,"pos":"名","meaning":"テレビゲーム","example":"The boy is playing a video game.","circle":false},
  {"no":2374,"word":"Vietnam","star":false,"pos":"名","meaning":"ベトナム","example":"I have a friend in Vietnam.","circle":false},
  {"no":2375,"word":"view","star":false,"pos":"名","meaning":"眺め、風景、考え　　　　※point of view  考え方","example":"The night view from Mt. Rokko is so beautiful.","circle":false},
  {"no":2376,"word":"village","star":false,"pos":"名","meaning":"村、村落","example":"People help each other in this small village.","circle":false},
  {"no":2377,"word":"vinegar","star":false,"pos":"名","meaning":"酢","example":"You need some vinegar and sugar to make sushi rice.","circle":true},
  {"no":2378,"word":"violence","star":false,"pos":"名","meaning":"暴力","example":"I am sad to see a lot of violence on TV.","circle":true},
  {"no":2379,"word":"violin","star":true,"pos":"名","meaning":"バイオリン","example":"He can play the violin very well.","circle":false},
  {"no":2380,"word":"visa","star":false,"pos":"名","meaning":"ビザ、査証","example":"People from overseas need a visa to work in Japan.","circle":true},
  {"no":2381,"word":"visit","star":true,"pos":"動・名","meaning":"訪問（する）","example":"My friend in Australia will visit my family next month.","circle":false},
  {"no":2382,"word":"visitor","star":false,"pos":"名","meaning":"訪問者、訪問客","example":"Japan has many visitors from foreign countries.","circle":false},
  {"no":2383,"word":"vocabulary","star":false,"pos":"名","meaning":"語彙","example":"I want to increase my English vocabulary.","circle":true},
  {"no":2384,"word":"voice","star":false,"pos":"名","meaning":"声","example":"Sorry, I can't hear your voice.","circle":false},
  {"no":2385,"word":"volleyball","star":true,"pos":"名","meaning":"バレーボール","example":"The boy plays volleyball every day.","circle":false},
  {"no":2386,"word":"volunteer","star":true,"pos":"名","meaning":"自分から進んでやる人、ボランティア \n※volunteer work ボランティア活動","example":"I am going to do volunteer work to help people.","circle":false},
  {"no":2387,"word":"wait","star":false,"pos":"動","meaning":"待つ　　　　　※wait for ～　～を待つ","example":"Please wait here until I come back.","circle":false},
  {"no":2388,"word":"waiter","star":false,"pos":"名","meaning":"接客係、ウェイター","example":"My brother works as a waiter at a restaurant.","circle":true},
  {"no":2389,"word":"wake","star":false,"pos":"動","meaning":"起きる、起こす　※wake ～ up　～を起こす \n【活用】 wake - woke - woken","example":"I have to wake up my sister every morning.","circle":false},
  {"no":2390,"word":"walk","star":true,"pos":"動・名","meaning":"歩く（こと）､散歩　　　　　　※take a walk  散歩する","example":"I walk to school every day.","circle":false},
  {"no":2391,"word":"wall","star":true,"pos":"名","meaning":"壁、塀","example":"There are two pictures on the wall.","circle":false},
  {"no":2392,"word":"wallet","star":false,"pos":"名","meaning":"財布","example":"Oh, no!  I lost my wallet.","circle":false},
  {"no":2393,"word":"want","star":true,"pos":"動","meaning":"～がほしい　\n※want to ～　～したい　want 人 to～　人に～してもらいたい","example":"I want to try a different sport in high school.","circle":false},
  {"no":2394,"word":"war","star":false,"pos":"名","meaning":"戦争、戦い","example":"People were happy when the war ended.","circle":false},
  {"no":2395,"word":"warm","star":false,"pos":"形","meaning":"暖かい","example":"Hyogo is nice and warm in May.","circle":false},
  {"no":2396,"word":"was","star":true,"pos":"動","meaning":"～であった、（～に）いた、あった （is, am の過去形）","example":"My family came to Hyogo when I was five years old.","circle":false},
  {"no":2397,"word":"wash","star":true,"pos":"動","meaning":"洗う","example":"I sometimes wash dishes for my family.","circle":false},
  {"no":2398,"word":"washing machine","star":false,"pos":"名","meaning":"洗たく機","example":"Please put your clothes in the washing machine.","circle":true},
  {"no":2399,"word":"Washington, D.C.","star":false,"pos":"名","meaning":"ワシントンD.C.（アメリカの首都）","example":"Washington, D.C. is the capital of the U.S.A..","circle":true},
  {"no":2400,"word":"waste","star":false,"pos":"動・名","meaning":"むだ、むだづかい（する）、浪費（する）","example":"It's a waste of time.","circle":false}
];
