const WORDS07 = [
{"no":601,"word":"dinner","star":true,"pos":"名","meaning":"ディナー、夕食","example":"This is a wonderful dinner.","circle":false},
{"no":602,"word":"dinosaur","star":false,"pos":"名","meaning":"恐竜","example":"My nephew knows a lot about dinosaurs.","circle":true},
{"no":603,"word":"direction","star":false,"pos":"名","meaning":"方角、方向","example":"Which direction is the train station?","circle":true},
{"no":604,"word":"directly","star":false,"pos":"副","meaning":"直接に","example":"You can ask me directly when you have questions.","circle":true},
{"no":605,"word":"director","star":false,"pos":"名","meaning":"（映画、劇などの）監督","example":"That Japanese director is famous all over the world.","circle":true},
{"no":606,"word":"dirty","star":false,"pos":"形","meaning":"汚い、汚れた","example":"My clothes are dirty, so I should wash them.","circle":true},
{"no":607,"word":"disability","star":false,"pos":"名","meaning":"（病気などによる）障害","example":"He has a disability, but he always accepts new challenges.","circle":true},
{"no":608,"word":"disagree","star":false,"pos":"動","meaning":"意見が合わない　　　※disagree with ～ ～と意見が合わない","example":"I disagree with you.","circle":false},
{"no":609,"word":"disappear","star":false,"pos":"動","meaning":"見えなくなる、消える","example":"Many kinds of animals disappeared from the earth.","circle":false},
{"no":610,"word":"disappointed","star":false,"pos":"形","meaning":"がっかりした","example":"I was disappointed to hear the news.","circle":false},
{"no":611,"word":"disaster","star":false,"pos":"名","meaning":"災害","example":"It is necessary for us to prepare for disasters.","circle":false},
{"no":612,"word":"discount","star":false,"pos":"名","meaning":"割引","example":"Could you give me a discount?","circle":false},
{"no":613,"word":"discover","star":false,"pos":"動","meaning":"見つける、見いだす","example":"He discovered electricity.","circle":false},
{"no":614,"word":"discovery","star":false,"pos":"名","meaning":"発見","example":"The discovery by the scientist was very interesting.","circle":true},
{"no":615,"word":"discuss","star":false,"pos":"動","meaning":"話し合う、討議する","example":"We discussed what to do to make our school better.","circle":true},
{"no":616,"word":"discussion","star":false,"pos":"名","meaning":"議論、討論","example":"We had a long discussion about the plan.","circle":true},
{"no":617,"word":"disease","star":false,"pos":"名","meaning":"病気","example":"The disease was very serious at that time.","circle":false},
{"no":618,"word":"dish","star":true,"pos":"名","meaning":"①皿\n②料理","example":"①Please wash the dishes after dinner.\n②This is today's main dish.","circle":false},
{"no":619,"word":"dislike","star":false,"pos":"動","meaning":"きらう","example":"I dislike learning new words.","circle":true},
{"no":620,"word":"display","star":false,"pos":"名","meaning":"展示","example":"We enjoyed the art displays at the museum.","circle":true},
{"no":621,"word":"distance","star":false,"pos":"名","meaning":"距離、遠い場所","example":"What is the distance from here to the station?","circle":false},
{"no":622,"word":"dive","star":false,"pos":"動","meaning":"飛び込む、（飛行機・鳥などが）急降下する、ダイビングをする","example":"I like to dive into the water at swimming pools.","circle":true},
{"no":623,"word":"divide","star":false,"pos":"動","meaning":"分ける","example":"Let's divide the cake between us.","circle":true},
{"no":624,"word":"do","star":true,"pos":"動・助","meaning":"①（動）～する、行う、行動する　　  【活用】 do - did - done\n②（助）（疑問文で）（～は～）しますか　\n③（助）（否定文で）（～は～しない）\n④（助）（否定の命令文で）（～は～）するな","example":"①What did you do during the spring vacation?\n②Do you speak Japanese?\n③I don't speak Japanese.\n④Don't speak Japanese in this class.","circle":false},
{"no":625,"word":"doctor","star":true,"pos":"名","meaning":"医師、博士","example":"She is a doctor.","circle":false},
{"no":626,"word":"does","star":false,"pos":"動・助","meaning":"主語が３人称単数形の時のdoの現在形","example":"Does your sister live with you?","circle":false},
{"no":627,"word":"dog","star":true,"pos":"名","meaning":"イヌ","example":"A dog was walking along the river.","circle":false},
{"no":628,"word":"doll","star":false,"pos":"名","meaning":"人形","example":"My father gave me this doll when I was a small child.","circle":false},
{"no":629,"word":"dollar","star":false,"pos":"名","meaning":"ドル（アメリカ・オーストラリア・カナダなどの通貨単位）","example":"It's five dollars.","circle":false},
{"no":630,"word":"dolphin","star":false,"pos":"名","meaning":"イルカ","example":"They often watch the dolphins from boats.","circle":false},
{"no":631,"word":"dome","star":false,"pos":"名","meaning":"ドーム","example":"Some baseball stadiums are domes.","circle":true},
{"no":632,"word":"donut","star":false,"pos":"名","meaning":"ドーナツ（doughnut のつづりもあり）","example":"My mother sometimes makes donuts for us.","circle":true},
{"no":633,"word":"door","star":false,"pos":"名","meaning":"ドア","example":"Please open the door.","circle":false},
{"no":634,"word":"dot","star":false,"pos":"名","meaning":"点","example":"I like ties with colorful dots.","circle":false},
{"no":635,"word":"doubt","star":false,"pos":"動・名","meaning":"（動）疑う  （名）疑い、疑念","example":"I doubt that the story is true.","circle":true},
{"no":636,"word":"down","star":true,"pos":"前・副","meaning":"下へ（に）、（道などに）沿って","example":"Go down the street and turn right.","circle":false},
{"no":637,"word":"download","star":false,"pos":"動","meaning":"ダウンロードする","example":"You can download the music from the Internet.","circle":true},
{"no":638,"word":"downtown","star":false,"pos":"副・名","meaning":"（町の）中心街（で）","example":"A new restaurant opened in the downtown area.","circle":true},
{"no":639,"word":"Dr.","star":false,"pos":"名","meaning":"（医者や博士の名の前につけて）～先生、～博士","example":"Dr. Yamanaka is a famous scientist all around the world.","circle":false},
{"no":640,"word":"drama","star":true,"pos":"名","meaning":"（テレビの）ドラマ、劇","example":"I like to watch dramas on TV.","circle":false},
{"no":641,"word":"draw","star":true,"pos":"動","meaning":"（線を）引く、（絵を）かく　　　　【活用】 draw - drew - drawn","example":"My hobby is drawing pictures.","circle":false},
{"no":642,"word":"drawer","star":false,"pos":"名","meaning":"引き出し","example":"There is still some space in the drawer.","circle":true},
{"no":643,"word":"dream","star":true,"pos":"動・名","meaning":"夢（を見る）","example":"His dream was to become a professional baseball player.","circle":false},
{"no":644,"word":"dress","star":false,"pos":"名","meaning":"衣装、ドレス","example":"I want to buy that beautiful dress.","circle":false},
{"no":645,"word":"dressed","star":false,"pos":"形","meaning":"服を着た　　　　  ※get dressed  服を着る","example":"I get dressed before breakfast every day.","circle":false},
{"no":646,"word":"dribble","star":false,"pos":"動","meaning":"ドリブルをする","example":"In basketball, you must dribble the ball.","circle":true},
{"no":647,"word":"dried","star":false,"pos":"形","meaning":"乾燥した","example":"Dried fruit and chocolate are mixed in these cakes.","circle":false},
{"no":648,"word":"drill","star":false,"pos":"名","meaning":"訓練","example":"Our school has a fire drill every year.","circle":false},
{"no":649,"word":"drink","star":true,"pos":"動・名","meaning":"①（動）飲む　　【活用】 drink - drank - drunk\n②（名）飲み物","example":"①What would you like to drink?\n②What is your favorite drink?","circle":false},
{"no":650,"word":"drive","star":false,"pos":"動","meaning":"（車を）運転する、ドライブする    【活用】 drive - drove - driven","example":"You have to drive on the left in Japan.","circle":false},
{"no":651,"word":"driver","star":true,"pos":"名","meaning":"（車を）運転する人、運転手","example":"I'm a taxi driver.","circle":false},
{"no":652,"word":"drone","star":false,"pos":"名","meaning":"ドローン（無人航空機）","example":"These pictures of our school were taken by a drone.","circle":true},
{"no":653,"word":"drop","star":false,"pos":"動・名","meaning":"①（動）落とす、落ちる\n②（名）しずく","example":"①Tears dropped from my eyes.\n②Put a few drops of lemon juice into the glass.","circle":false},
{"no":654,"word":"drugstore","star":false,"pos":"名","meaning":"ドラッグストア、薬局","example":"On the corner, there is a drugstore.","circle":false},
{"no":655,"word":"drum","star":true,"pos":"名","meaning":"太鼓、ドラム","example":"The boy plays the drum every day.","circle":false},
{"no":656,"word":"dry","star":false,"pos":"動・形","meaning":"（動）乾かす、（形）乾いた","example":"I'm drying my hair.","circle":false},
{"no":657,"word":"duck","star":false,"pos":"名","meaning":"カモ、アヒル","example":"There are many ducks in this park.","circle":false},
{"no":658,"word":"due","star":false,"pos":"形","meaning":"※due to ～  ～のために、～のせいで","example":"The game was cancelled due to the rain.","circle":true},
{"no":659,"word":"during","star":false,"pos":"前","meaning":"～の間（のいつか）","example":"What did you do during the spring vacation?","circle":false},
{"no":660,"word":"dust","star":false,"pos":"動・名","meaning":"（動）ほこりを払う    （名）ほこり、ちり","example":"There was some dust on the shelf.","circle":true},
{"no":661,"word":"duty","star":false,"pos":"名","meaning":"義務、職務","example":"Taking out the garbage is my duty.","circle":true},
{"no":662,"word":"DVD","star":false,"pos":"名","meaning":"digital video discの略","example":"Let's watch the DVD.","circle":false},
{"no":663,"word":"dying","star":false,"pos":"形","meaning":"瀕死の状態の、死にかかっている","example":"The fish was dying.","circle":false},
{"no":664,"word":"each","star":false,"pos":"代・形","meaning":"それぞれ（の）、各（の）～　　※each other  お互いに","example":"Each story has two or more characters.","circle":false},
{"no":665,"word":"ear","star":true,"pos":"名","meaning":"耳","example":"Elephants have big ears.","circle":false},
{"no":666,"word":"early","star":false,"pos":"形・副","meaning":"（時間的に）早い（く）","example":"It is good to get up early every day.","circle":false},
{"no":667,"word":"earth","star":false,"pos":"名","meaning":"地球","example":"The earth's environment is changing very fast.","circle":false},
{"no":668,"word":"earthquake","star":false,"pos":"名","meaning":"地震","example":"There was a big earthquake in Kobe in 1995.","circle":false},
{"no":669,"word":"easily","star":false,"pos":"副","meaning":"簡単に、容易に","example":"You can get information easily on the Internet.","circle":false},
{"no":670,"word":"east","star":false,"pos":"名・形・副","meaning":"東（の、へ）、東方","example":"The sun rises in the east.","circle":false},
{"no":671,"word":"eastern","star":false,"pos":"形","meaning":"東の","example":"Amagasaki is in the eastern part of Hyogo.","circle":true},
{"no":672,"word":"easy","star":true,"pos":"形","meaning":"やさしい、簡単な      ※take it easy 気楽にやる","example":"It is easy to read this book.","circle":false},
{"no":673,"word":"easygoing","star":false,"pos":"形","meaning":"のんきな、おおらかな","example":"My mother is always easygoing.","circle":true},
{"no":674,"word":"eat","star":true,"pos":"動","meaning":"食べる、食事をする　※eat out 外食する　【活用】 eat - ate - eaten","example":"We eat lunch in the cafeteria.","circle":false},
{"no":675,"word":"eco-friendly","star":false,"pos":"形","meaning":"環境にやさしい","example":"Taking my bag to the supermarket is eco-friendly.","circle":true},
{"no":676,"word":"economy","star":false,"pos":"名","meaning":"経済","example":"I want to work to improve our economy.","circle":false},
{"no":677,"word":"ecosystem","star":false,"pos":"名","meaning":"生態系","example":"We should work together to save the ecosystem.","circle":true},
{"no":678,"word":"edge","star":false,"pos":"名","meaning":"へり、端","example":"Don't run near the edge of the pool.","circle":true},
{"no":679,"word":"education","star":false,"pos":"名","meaning":"教育","example":"What are the good points about Japanese education?","circle":false},
{"no":680,"word":"effect","star":false,"pos":"名","meaning":"影響","example":"The accident had a big effect on him.","circle":false},
{"no":681,"word":"effective","star":false,"pos":"形","meaning":"効果的な、有効な","example":"This medicine is very effective against the disease.","circle":true},
{"no":682,"word":"effort","star":false,"pos":"名","meaning":"努力      ※make an effort 努力する","example":"We made a big effort to win the game.","circle":false},
{"no":683,"word":"egg","star":true,"pos":"名","meaning":"卵","example":"I had ham and eggs this morning.","circle":false},
{"no":684,"word":"eggplant","star":false,"pos":"名","meaning":"ナス","example":"Eggplants taste best in summer.","circle":true},
{"no":685,"word":"eight","star":true,"pos":"名・形","meaning":"８（の）","example":"It's eight o'clock.","circle":false},
{"no":686,"word":"eighteen","star":true,"pos":"名・形","meaning":"１８（の）","example":"It's just eighteen dollars.","circle":false},
{"no":687,"word":"eighteenth","star":false,"pos":"名・形","meaning":"１８番目（の）","example":"The room is on the eighteenth floor.","circle":false},
{"no":688,"word":"eighth","star":false,"pos":"名・形","meaning":"８番目（の）","example":"I am in the eighth grade.","circle":false},
{"no":689,"word":"eighty","star":true,"pos":"名・形","meaning":"８０（の）","example":"There are eighty seats in the room.","circle":false},
{"no":690,"word":"either","star":false,"pos":"接・副","meaning":"①どちらか　　　　※either A or B   AかBかどちらか\n②（否定）～もまた～ない","example":"①Either you or he must go.\n②I couldn't speak English either.","circle":false},
{"no":691,"word":"elbow","star":false,"pos":"名","meaning":"ひじ","example":"Don't put your elbows on the table.","circle":true},
{"no":692,"word":"elderly","star":false,"pos":"形","meaning":"年配の","example":"The number of elderly people is increasing in Japan.","circle":false},
{"no":693,"word":"electricity","star":false,"pos":"名","meaning":"電気","example":"It is difficult to live without electricity.","circle":false},
{"no":694,"word":"electronic","star":false,"pos":"形","meaning":"電子の　　※electronic device  電子機器","example":"Electronic dictionaries are very convenient.","circle":true},
{"no":695,"word":"elementary","star":false,"pos":"形","meaning":"初歩の、初等の","example":"This book is for students at the elementary level.","circle":true},
{"no":696,"word":"elementary school","star":true,"pos":"名","meaning":"小学校","example":"I am an elementary school student.","circle":false},
{"no":697,"word":"elephant","star":true,"pos":"名","meaning":"ゾウ","example":"The largest animal living on land is the elephant.","circle":false},
{"no":698,"word":"elevator","star":false,"pos":"名","meaning":"エレベーター","example":"We have four elevators in our building.","circle":false},
{"no":699,"word":"eleven","star":true,"pos":"名・形","meaning":"１１（の）","example":"I go to bed at about eleven o'clock.","circle":false},
{"no":700,"word":"eleventh","star":false,"pos":"名・形","meaning":"１１番目（の）","example":"I am in the eleventh grade.","circle":false}
];
