const WORDS09 = [
  {"no":801,"word":"female","star":false,"pos":"形","meaning":"女性の","example":"My homeroom teacher is female.","circle":true},
  {"no":802,"word":"fence","star":false,"pos":"名","meaning":"囲い、さく、へい","example":"There is a fence around my garden.","circle":true},
  {"no":803,"word":"ferry","star":false,"pos":"名","meaning":"フェリー","example":"You can take a ferry to the island.","circle":true},
  {"no":804,"word":"festival","star":true,"pos":"名","meaning":"お祭り、祭日、～祭、祭典","example":"There are many festivals in autumn.","circle":false},
  {"no":805,"word":"fever","star":false,"pos":"名","meaning":"（病気の）熱","example":"I have a fever.","circle":false},
  {"no":806,"word":"few","star":false,"pos":"形","meaning":"※a few ～　少数の～、少しの～","example":"The movie began just a few minutes ago.","circle":false},
  {"no":807,"word":"fiction","star":false,"pos":"名","meaning":"小説、フィクション","example":"This book is a science fiction.","circle":false},
  {"no":808,"word":"field","star":false,"pos":"名","meaning":"野原、畑、牧草地、実地","example":"The dog is running on the field.","circle":false},
  {"no":809,"word":"field trip","star":true,"pos":"名","meaning":"遠足、校外学習","example":"Our class is going on a field trip tomorrow.","circle":true},
  {"no":810,"word":"fifteen","star":true,"pos":"名・形","meaning":"１５（の）","example":"I am fifteen years old.","circle":false},
  {"no":811,"word":"fifteenth","star":false,"pos":"名・形","meaning":"１５番目（の）","example":"The room is on the fifteenth floor.","circle":false},
  {"no":812,"word":"fifth","star":false,"pos":"名・形","meaning":"５番目（の）","example":"My sister is in the fifth grade.","circle":false},
  {"no":813,"word":"fifty","star":true,"pos":"名・形","meaning":"５０（の）","example":"My father was born today fifty years ago.","circle":false},
  {"no":814,"word":"fight","star":false,"pos":"動・名","meaning":"（動）戦う　　　【活用】 fight - fought- fought\n（名）戦い","example":"Let's fight for our right.","circle":false},
  {"no":815,"word":"file","star":false,"pos":"名","meaning":"ファイル、書類ケース","example":"Put your paper in a file.","circle":true},
  {"no":816,"word":"fill","star":false,"pos":"動","meaning":"いっぱいにする、いっぱいになる","example":"We filled the glass with water.","circle":false},
  {"no":817,"word":"film","star":false,"pos":"名","meaning":"映画","example":"My dream is to make a film.","circle":true},
  {"no":818,"word":"final","star":false,"pos":"形","meaning":"最後の、最終の","example":"I met my wife in the final year of high school.","circle":false},
  {"no":819,"word":"finally","star":false,"pos":"副","meaning":"最後に、ついに","example":"Finally his dream came true.","circle":false},
  {"no":820,"word":"find","star":false,"pos":"動","meaning":"見つける、見いだす　 ※find out わかる　　\n【活用】 find - found - found","example":"I found the watch I lost yesterday.","circle":false},
  {"no":821,"word":"fine","star":true,"pos":"形","meaning":"元気な、調子の良い","example":"I'm fine, thank you.","circle":false},
  {"no":822,"word":"finger","star":false,"pos":"名","meaning":"手の指","example":"You have to use your fingers to play the guitar.","circle":false},
  {"no":823,"word":"finish","star":false,"pos":"動","meaning":"終わらせる、終わる","example":"She has already finished her homework.","circle":false},
  {"no":824,"word":"fire","star":false,"pos":"名","meaning":"火、火事","example":"The fire is burning the trees.","circle":false},
  {"no":825,"word":"fire station","star":true,"pos":"名","meaning":"消防署","example":"Our school is next to a fire station.","circle":true},
  {"no":826,"word":"firefighter","star":true,"pos":"名","meaning":"消防士","example":"The firefighter saved a child from a fire.","circle":true},
  {"no":827,"word":"firework","star":true,"pos":"名","meaning":"花火","example":"I like Bon-odori and fireworks festivals.","circle":false},
  {"no":828,"word":"first","star":true,"pos":"名・形・副","meaning":"１番目（の）、第１に、最初に\n※at first  最初は　　for the first time　初めて\nfirst of all  まず最初に","example":"This is the first camera I bought.","circle":false},
  {"no":829,"word":"fish","star":true,"pos":"動・名","meaning":"（動）魚つりをする　（名）魚（複数形も fish）※go fishing  釣りに行く","example":"You can eat fresh fish in Awaji Island.","circle":false},
  {"no":830,"word":"fisherman","star":false,"pos":"名","meaning":"漁師","example":"My father has been a fisherman for twenty years.","circle":true},
  {"no":831,"word":"fishing","star":true,"pos":"名","meaning":"つり","example":"I went fishing with my father yesterday.","circle":false},
  {"no":832,"word":"fit","star":false,"pos":"動","meaning":"（サイズ・形が）合う","example":"This shirt fits me very well.","circle":false},
  {"no":833,"word":"fitting room","star":false,"pos":"名","meaning":"試着室","example":"A: May I try it on?  B: Sure. The fitting room is over there.","circle":false},
  {"no":834,"word":"five","star":true,"pos":"名・形","meaning":"５（の）","example":"There are five members in my family.","circle":false},
  {"no":835,"word":"flag","star":false,"pos":"名","meaning":"旗","example":"The picture shows the flag of her country.","circle":false},
  {"no":836,"word":"flashlight","star":false,"pos":"名","meaning":"懐中電灯","example":"You will need a flashlight in an emergency.","circle":true},
  {"no":837,"word":"flavor","star":false,"pos":"名","meaning":"味、風味","example":"I like the flavor of chocolate.","circle":true},
  {"no":838,"word":"flight","star":false,"pos":"名","meaning":"飛行、（飛行機の）便","example":"We hope you will enjoy this flight.","circle":false},
  {"no":839,"word":"flight attendant","star":true,"pos":"名","meaning":"（旅客機の）客室乗務員","example":"The flight attendant led me to my seat.","circle":true},
  {"no":840,"word":"flood","star":false,"pos":"名","meaning":"洪水","example":"We had a serious flood last year.","circle":true},
  {"no":841,"word":"floor","star":false,"pos":"名","meaning":"床、階","example":"The shop is on the second floor.","circle":false},
  {"no":842,"word":"florist","star":true,"pos":"名","meaning":"花屋（の主人）","example":"When I was a little girl, I wanted to be a florist.","circle":false},
  {"no":843,"word":"flour","star":false,"pos":"名","meaning":"小麦粉","example":"Mix the flour and sugar.","circle":false},
  {"no":844,"word":"flower","star":true,"pos":"名","meaning":"花","example":"You can see a lot of flowers in Awaji Island.","circle":false},
  {"no":845,"word":"flower arrangement","star":false,"pos":"名","meaning":"華道","example":"I will teach flower arrangement to my host family.","circle":true},
  {"no":846,"word":"fluently","star":false,"pos":"副","meaning":"流ちょうに","example":"Our teacher speaks English fluently.","circle":false},
  {"no":847,"word":"flute","star":false,"pos":"名","meaning":"フルート、横笛","example":"I practice the flute after school every day.","circle":true},
  {"no":848,"word":"fly","star":false,"pos":"動","meaning":"飛ぶ、（飛行機で）行く（旅行する）　  【活用】 fly - flew - flown","example":"The toy plane flew as high as a bird.","circle":false},
  {"no":849,"word":"focus","star":false,"pos":"動・名","meaning":"（動）（注意などを）集中する、重点的に取り扱う　（名）中心","example":"You should try to focus in class.","circle":true},
  {"no":850,"word":"fog","star":false,"pos":"名","meaning":"霧、もや","example":"We often have heavy fog in this area.","circle":true},
  {"no":851,"word":"fold","star":false,"pos":"動","meaning":"折る","example":"I folded the origami paper carefully.","circle":true},
  {"no":852,"word":"follow","star":false,"pos":"動","meaning":"（～に）ついて行く、（～に）従う","example":"You have to follow the family's rules.","circle":false},
  {"no":853,"word":"following","star":false,"pos":"形","meaning":"次の","example":"Please answer the following questions.","circle":true},
  {"no":854,"word":"food","star":true,"pos":"名","meaning":"食べもの","example":"Do you have any famous local foods in your town?","circle":false},
  {"no":855,"word":"foolish","star":false,"pos":"形","meaning":"愚かな","example":"I'm sorry I did such a foolish thing.","circle":true},
  {"no":856,"word":"foot","star":false,"pos":"名","meaning":"足（足首から下の部分）　　【複数】 feet","example":"He hurt his left foot when he fell.","circle":false},
  {"no":857,"word":"football","star":true,"pos":"名","meaning":"アメリカンフットボール、サッカー","example":"I watched football on TV last night.","circle":false},
  {"no":858,"word":"for","star":true,"pos":"前","meaning":"①～のために（の）　\n②～にとって　\n③～を得るために　\n④～の理由で　\n⑤～の間","example":"①I'll get some food for you. \n②The test was easy for me.\n③People sometimes fight for food.\n④My uncle gave me a watch for my birthday.\n⑤I've lived here for two years.","circle":false},
  {"no":859,"word":"forecast","star":false,"pos":"名","meaning":"予報","example":"The weather forecast says it will rain tomorrow.","circle":true},
  {"no":860,"word":"forehead","star":false,"pos":"名","meaning":"額","example":"After running, there was a lot of sweat on my forehead.","circle":true},
  {"no":861,"word":"foreign","star":false,"pos":"形","meaning":"外国の","example":"I want to go to a foreign country.","circle":false},
  {"no":862,"word":"foreigner","star":false,"pos":"名","meaning":"外国人","example":"He tried to talk to foreigners in English.","circle":false},
  {"no":863,"word":"forest","star":false,"pos":"名","meaning":"森","example":"You can see many kinds of birds in this forest.","circle":false},
  {"no":864,"word":"forever","star":false,"pos":"副","meaning":"永久に、絶えず","example":"Good friends stay in our minds forever.","circle":false},
  {"no":865,"word":"forget","star":false,"pos":"動","meaning":"忘れる　　【活用】 forget - forgot - forgot/forgotten","example":"I'll never forget this trip.","circle":false},
  {"no":866,"word":"forgive","star":false,"pos":"動","meaning":"許す","example":"Please forgive me for my mistake.","circle":true},
  {"no":867,"word":"fork","star":false,"pos":"名","meaning":"フォーク","example":"You should learn how to use a knife and a fork.","circle":true},
  {"no":868,"word":"fortunately","star":false,"pos":"副","meaning":"幸運にも","example":"Fortunately, I met a wonderful person there.","circle":true},
  {"no":869,"word":"forty","star":true,"pos":"名・形","meaning":"４０（の）","example":"There are forty students in my class.","circle":false},
  {"no":870,"word":"forward","star":false,"pos":"副","meaning":"前へ　　　※look forward to ～　～を楽しみに待つ","example":"I am looking forward to seeing you again.","circle":false},
  {"no":871,"word":"fountain","star":false,"pos":"名","meaning":"噴水","example":"There is a big fountain in the park.","circle":true},
  {"no":872,"word":"four","star":true,"pos":"名・形","meaning":"４（の）","example":"We have four classes in the morning.","circle":false},
  {"no":873,"word":"fourteen","star":true,"pos":"名・形","meaning":"１４（の）","example":"I will be fourteen next month.","circle":false},
  {"no":874,"word":"fourteenth","star":false,"pos":"名・形","meaning":"１４番目の","example":"The room is on the fourteenth floor.","circle":false},
  {"no":875,"word":"fourth","star":false,"pos":"名・形","meaning":"４番目（の）","example":"My sister is in the fourth grade.","circle":false},
  {"no":876,"word":"fox","star":false,"pos":"名","meaning":"キツネ","example":"Foxes appear in some old stories.","circle":false},
  {"no":877,"word":"France","star":false,"pos":"名","meaning":"フランス","example":"I lived in France ten years ago.","circle":false},
  {"no":878,"word":"free","star":false,"pos":"形","meaning":"①自由な　　※be free to ～　自由に～することができる\n②ひまな　\n③無料の","example":"①You are free to come and go anytime.\n②Are you free on Saturday night? \n③You can enjoy free food and drinks.","circle":false},
  {"no":879,"word":"freedom","star":false,"pos":"名","meaning":"自由","example":"I tried to show the feeling of freedom with pictures.","circle":false},
  {"no":880,"word":"freely","star":false,"pos":"副","meaning":"自由に","example":"They couldn't go to school freely in those days.","circle":false},
  {"no":881,"word":"French","star":false,"pos":"名・形","meaning":"フランスの、フランス人（の）、フランス語（の）","example":"My sister is studying French now.","circle":false},
  {"no":882,"word":"French fries","star":true,"pos":"名","meaning":"フライドポテト","example":"I like French fries very much.","circle":false},
  {"no":883,"word":"fresh","star":false,"pos":"形","meaning":"新鮮な","example":"All the vegetables looked very fresh.","circle":false},
  {"no":884,"word":"Friday","star":true,"pos":"名","meaning":"金曜日","example":"I come to school from Monday to Friday.","circle":false},
  {"no":885,"word":"fridge","star":false,"pos":"名","meaning":"冷蔵庫（refrigeratorの略）","example":"We need a bigger fridge to keep more food.","circle":false},
  {"no":886,"word":"fried","star":false,"pos":"形","meaning":"油であげた（いためた）","example":"I sometimes cook fried rice for myself.","circle":true},
  {"no":887,"word":"friend","star":true,"pos":"名","meaning":"友人、友達　　※make friends with ～　～と友達になる","example":"The boy is talking with his friends.","circle":false},
  {"no":888,"word":"friendly","star":true,"pos":"形","meaning":"友好的な、人なつっこい","example":"She is kind and friendly.","circle":false},
  {"no":889,"word":"friendship","star":false,"pos":"名","meaning":"友情、親交","example":"Hyogo and Western Australia have a special friendship.","circle":false},
  {"no":890,"word":"frog","star":true,"pos":"名","meaning":"カエル","example":"I found two frogs by the window.","circle":false},
  {"no":891,"word":"from","star":true,"pos":"前","meaning":"①～から　      ※from ～ to ･･･  ～から･･･まで\n②～出身で","example":"①I took the train from Himeji.\n②I'm from Japan.","circle":false},
  {"no":892,"word":"front","star":false,"pos":"名・形","meaning":"前（の）、前部（の）　　※in front of ～　～の前に（の）","example":"Let's meet in front of the station at 1:30.","circle":false},
  {"no":893,"word":"fruit","star":true,"pos":"名","meaning":"果物、フルーツ","example":"What kind of fruit do you like?","circle":false},
  {"no":894,"word":"frustrated","star":false,"pos":"形","meaning":"フラストレーションを感じて、ストレスのたまった","example":"I sometimes get frustrated when I speak English.","circle":false},
  {"no":895,"word":"full","star":false,"pos":"形","meaning":"満ちた、いっぱいの 、満腹の    ※be full of ～　～で一杯の","example":"I've eaten so much.  I’m full.","circle":false},
  {"no":896,"word":"fun","star":true,"pos":"名・形","meaning":"おもしろい（こと）、楽しさ　　※have fun　楽しむ","example":"I had a lot of fun with you.","circle":false},
  {"no":897,"word":"funny","star":true,"pos":"形","meaning":"おもしろい","example":"The movie is funny.","circle":false},
  {"no":898,"word":"furniture","star":false,"pos":"名","meaning":"家具","example":"This is my favorite furniture.","circle":false},
  {"no":899,"word":"future","star":true,"pos":"名・形","meaning":"未来（の）、将来（の）　　　※in the future 　将来（は）","example":"We should think of our future.","circle":false},
  {"no":900,"word":"game","star":true,"pos":"名","meaning":"試合、（gamesで）競技大会、ゲーム","example":"I watched a soccer game on TV last night.","circle":false}
];
