const WORDS16 = [
  {"no":1501,"word":"often","star":false,"pos":"副","meaning":"しばしば、たびたび","example":"I often go skiing in winter.","circle":false},
  {"no":1502,"word":"oh","star":true,"pos":"間","meaning":"おお、まあ、おや、あら","example":"Oh, you are here!","circle":false},
  {"no":1503,"word":"oil","star":false,"pos":"名","meaning":"油、石油","example":"This machine needs oil.","circle":false},
  {"no":1504,"word":"OK","star":true,"pos":"形・間","meaning":"よろしい、オーケー（Okayのつづりもあり）  ※It's OK.  いいんですよ","example":"OK.  I will help you.","circle":false},
  {"no":1505,"word":"old","star":true,"pos":"形","meaning":"古い、～歳で","example":"There is an old tree in the garden.","circle":false},
  {"no":1506,"word":"Olympics","star":true,"pos":"名","meaning":"国際オリンピック競技会、オリンピック（Olympic Games とも言う）","example":"I want to attend the Olympics in the future.","circle":false},
  {"no":1507,"word":"omelet（omelette）","star":true,"pos":"名","meaning":"オムレツ","example":"Do you know how to cook an omelet?","circle":true},
  {"no":1508,"word":"on","star":true,"pos":"前・副","meaning":"①（時間）～に　\n②（接触）～の上に　\n③（状態）～で　\n④（手段・道具）～で　\n⑤（位置）～に面して　\n⑥（関連）～について、～に関する　\n⑦（所属）～に属して、～の一員で　\n⑧身につけて　 ※try on ～　～を試着する　\n～ and so on　～など","example":"①I was born on July 22.\n②Please put your hands on the desk.\n③I was on a bus at that time.\n④We can talk on the Internet.\n⑤You will see a big tree on your left.\n⑥I need information on animals.\n⑦I play on the soccer team.\n⑧I like this shirt.  May I try it on?","circle":false},
  {"no":1509,"word":"once","star":false,"pos":"接・副","meaning":"①（接）いったん～したからには\n②（副）１度、１回、かつて      ※at once  すぐに","example":"①Once you start playing games, you can't stop.\n②I have visited London once.","circle":false},
  {"no":1510,"word":"one","star":true,"pos":"名・代・形","meaning":"１つ（の）、人、それ、ある～    ※one by one  ひとつずつ","example":"How about this one?","circle":false},
  {"no":1511,"word":"onion","star":true,"pos":"名","meaning":"タマネギ","example":"Awaji Island is famous for onions.","circle":false},
  {"no":1512,"word":"online","star":false,"pos":"形・副","meaning":"オンラインの（で）","example":"Many people buy things online nowadays.","circle":true},
  {"no":1513,"word":"only","star":false,"pos":"形・副","meaning":"たった、～だけ","example":"He was only 14 years old.","circle":false},
  {"no":1514,"word":"onto","star":false,"pos":"前","meaning":"～の上に","example":"I was just in time, so I jumped onto the bus.","circle":true},
  {"no":1515,"word":"open","star":false,"pos":"動・形","meaning":"①（動）（ドア・窓などが）開く、あける\n②（形）開いている","example":"①I can't open the door.\n②The door is open.","circle":false},
  {"no":1516,"word":"operation","star":false,"pos":"名","meaning":"手術","example":"I must have an operation on my leg next week.","circle":true},
  {"no":1517,"word":"opinion","star":false,"pos":"名","meaning":"意見、考え　　　　　　　　　　※in my opinion  私の意見では","example":"Do you have your own opinion?","circle":false},
  {"no":1518,"word":"opportunity","star":false,"pos":"名","meaning":"機会、好機","example":"Studying abroad is a great opportunity.","circle":true},
  {"no":1519,"word":"or","star":false,"pos":"接","meaning":"または、あるいは","example":"Which do you want, beef or chicken?","circle":false},
  {"no":1520,"word":"orange","star":true,"pos":"名・形","meaning":"オレンジ（がかった色の）","example":"Can I have another glass of orange juice, please?","circle":false},
  {"no":1521,"word":"orchestra","star":false,"pos":"名","meaning":"オーケストラ","example":"I've always wanted to play in an orchestra.","circle":false},
  {"no":1522,"word":"order","star":false,"pos":"動・名","meaning":"①（動）注文する、命じる　（名）注文、命令\n②（名）順序、順番","example":"①Are you ready to order?\n②Please put these words in the right order.","circle":false},
  {"no":1523,"word":"ordinary","star":false,"pos":"形","meaning":"ふつうの","example":"Today was another ordinary day.","circle":true},
  {"no":1524,"word":"organization","star":false,"pos":"名","meaning":"組織、団体","example":"WHO is an organization for world health.","circle":true},
  {"no":1525,"word":"origin","star":false,"pos":"名","meaning":"起源、はじまり","example":"The origin of ramen is China.","circle":true},
  {"no":1526,"word":"original","star":false,"pos":"形","meaning":"独自の","example":"Each restaurant has its own original menu.","circle":false},
  {"no":1527,"word":"originally","star":false,"pos":"副","meaning":"もともとは、本来は","example":"The food originally comes from China.","circle":false},
  {"no":1528,"word":"other","star":false,"pos":"代・形","meaning":"他の（もの）","example":"I like cats better than other animals.","circle":false},
  {"no":1529,"word":"ouch","star":false,"pos":"間","meaning":"痛いっ","example":"Ouch!  My cat bit me!","circle":true},
  {"no":1530,"word":"our","star":true,"pos":"代","meaning":"私たちの、われわれの","example":"Ms. Yamada is our teacher.","circle":false},
  {"no":1531,"word":"ours","star":false,"pos":"代","meaning":"私たちのもの","example":"That house is bigger than ours.","circle":false},
  {"no":1532,"word":"ourselves","star":false,"pos":"代","meaning":"私たちを（に）","example":"We introduced ourselves to each other.","circle":false},
  {"no":1533,"word":"out","star":true,"pos":"副","meaning":"外へ（で）、外を　　※out of ～ ～から（外へ）","example":"Get out of here!","circle":false},
  {"no":1534,"word":"outdoor","star":false,"pos":"形","meaning":"野外の、屋外の","example":"Skiing is a good outdoor activity in winter.","circle":true},
  {"no":1535,"word":"outdoors","star":false,"pos":"副","meaning":"屋外で（へ）","example":"I love to play outdoors.","circle":true},
  {"no":1536,"word":"outside","star":false,"pos":"副","meaning":"外へ（で）","example":"When you go outside, take your umbrella with you.","circle":false},
  {"no":1537,"word":"oven","star":false,"pos":"名","meaning":"オーブン","example":"The cookies in the oven look delicious.","circle":true},
  {"no":1538,"word":"over","star":false,"pos":"前・副","meaning":"①（越えて）向こうへ、渡って\n②～以上で（の）\n③～の一面に\n④～の上に、～の上を\n※over there 向こうに（で）  all over the world 世界中に（で）","example":"①The book you want to read is over there.\n②Over 300 students joined club activities last year.\n③The song is sung all over the world.\n④A terrible bomb was dropped over Hiroshima.","circle":false},
  {"no":1539,"word":"overseas","star":false,"pos":"副","meaning":"海外へ（で）、外国へ（で）","example":"Japanese anime goes overseas.","circle":false},
  {"no":1540,"word":"own","star":false,"pos":"形","meaning":"自分(自身)の","example":"I saw it with my own eyes.","circle":false},
  {"no":1541,"word":"owner","star":false,"pos":"名","meaning":"持ち主、飼い主","example":"He is the owner of this building.","circle":false},
  {"no":1542,"word":"Pacific","star":false,"pos":"形","meaning":"太平洋の　　※Pacific Ocean  太平洋","example":"The Pacific Ocean is between Asia and America.","circle":true},
  {"no":1543,"word":"pack","star":false,"pos":"名","meaning":"１パック、１箱　　※a pack of ～　パック１箱（の量）の～","example":"I want two packs of tomatoes, please.","circle":false},
  {"no":1544,"word":"package","star":false,"pos":"名","meaning":"包み","example":"The package will arrive tomorrow.","circle":true},
  {"no":1545,"word":"page","star":false,"pos":"名","meaning":"（本、新聞などの）面、欄、ページ","example":"This newspaper has a page for children.","circle":false},
  {"no":1546,"word":"pain","star":false,"pos":"名","meaning":"痛み","example":"I have a pain in my leg.","circle":false},
  {"no":1547,"word":"paint","star":false,"pos":"動","meaning":"（絵の具で）かく、いろどる","example":"She can paint pictures very well.","circle":false},
  {"no":1548,"word":"painter","star":false,"pos":"名","meaning":"画家","example":"Who is your favorite painter?","circle":false},
  {"no":1549,"word":"painting","star":false,"pos":"名","meaning":"（絵の具で）かくこと、絵","example":"The book has many of paintings from Europe.","circle":false},
  {"no":1550,"word":"pair","star":false,"pos":"名","meaning":"１組、１対　　　※ a pair of ～　　１足の～、１組の～","example":"I’m looking for a pair of sneakers.","circle":false},
  {"no":1551,"word":"pajamas","star":false,"pos":"名","meaning":"パジャマ（複数形で使う）","example":"On Sunday, I wore my pajamas all day!","circle":true},
  {"no":1552,"word":"pale","star":false,"pos":"形","meaning":"顔色の悪い","example":"You look pale.  Are you OK?","circle":false},
  {"no":1553,"word":"palm","star":false,"pos":"名","meaning":"手のひら","example":"There are some lines on your palm.","circle":true},
  {"no":1554,"word":"pancake","star":false,"pos":"名","meaning":"パンケーキ","example":"This café makes delicious pancakes.","circle":true},
  {"no":1555,"word":"panda","star":true,"pos":"名","meaning":"パンダ","example":"You can see a panda in the zoo.","circle":false},
  {"no":1556,"word":"pants","star":true,"pos":"名","meaning":"ズボン（複数形で使う）","example":"Female students can wear pants in this school.","circle":true},
  {"no":1557,"word":"paper","star":false,"pos":"名","meaning":"紙","example":"I need a piece of paper to take notes.","circle":false},
  {"no":1558,"word":"parade","star":false,"pos":"名","meaning":"パレード、行列","example":"I want to see the parade at USJ.","circle":true},
  {"no":1559,"word":"paragraph","star":false,"pos":"名","meaning":"段落、パラグラフ","example":"The writer's message is written in the last paragraph.","circle":true},
  {"no":1560,"word":"Paralympics","star":false,"pos":"名","meaning":"パラリンピック（Paralympic Gamesとも言う）","example":"We will have the Paralympics in Tokyo in 2021.","circle":false},
  {"no":1561,"word":"pardon","star":false,"pos":"動・名","meaning":"※Pardon?\n（最後を上げて発音して）すみませんがもう一度言ってください","example":"Pardon?  Sorry, I couldn't hear what you said.","circle":false},
  {"no":1562,"word":"parent","star":false,"pos":"名","meaning":"親（父または母、parentsで両親）","example":"My parents are very nice.","circle":false},
  {"no":1563,"word":"Paris","star":false,"pos":"名","meaning":"パリ","example":"Paris is the capital of France.","circle":false},
  {"no":1564,"word":"park","star":true,"pos":"名","meaning":"公園、遊園地　　　　　　※national park 国立公園","example":"My brother likes playing in the park near my house.","circle":false},
  {"no":1565,"word":"parking lot","star":false,"pos":"名","meaning":"駐車場","example":"There are some parking lots around the shopping area.","circle":true},
  {"no":1566,"word":"part","star":false,"pos":"名","meaning":"①部分　\n②役割、役目\n ※ play a part 　役割を果たす　take part in ～　～に参加する","example":"①Music is a part of my life.\n②He played an important part.","circle":false},
  {"no":1567,"word":"particular","star":false,"pos":"形","meaning":"特定の","example":"I don't have any particular plans for the holidays.","circle":true},
  {"no":1568,"word":"partner","star":false,"pos":"名","meaning":"仲間、パートナー","example":"Check the answers with your partner.","circle":false},
  {"no":1569,"word":"party","star":false,"pos":"名","meaning":"パーティ、（社交の）会","example":"My friends and I had an ohanami party.","circle":false},
  {"no":1570,"word":"pass","star":false,"pos":"動","meaning":"渡す、通り過ぎる","example":"Ten years have passed since he left.","circle":false},
  {"no":1571,"word":"passage","star":false,"pos":"名","meaning":"（文章などの）一節、一部","example":"Please read the passage and answer the questions.","circle":true},
  {"no":1572,"word":"passenger","star":false,"pos":"名","meaning":"乗客","example":"There were a lot of passengers on the train.","circle":false},
  {"no":1573,"word":"passion","star":false,"pos":"名","meaning":"熱中（しているもの）、情熱","example":"He has a passion for music.","circle":false},
  {"no":1574,"word":"passport","star":false,"pos":"名","meaning":"旅券、パスポート","example":"Show me your passport, please.","circle":false},
  {"no":1575,"word":"past","star":false,"pos":"名・形","meaning":"過去（の）","example":"We can learn from past experiences.","circle":false},
  {"no":1576,"word":"patient","star":false,"pos":"名・形","meaning":"①（名）患者、病人\n②（形）我慢強い","example":"①Nurses take care of their patients every day.\n②Be patient.","circle":false},
  {"no":1577,"word":"pause","star":false,"pos":"名","meaning":"間、休止","example":"There was a long pause before he answered.","circle":true},
  {"no":1578,"word":"pay","star":false,"pos":"動","meaning":"支払う、払う      【活用】 pay - paid - paid","example":"You must pay fifteen dollars for the tour.","circle":false},
  {"no":1579,"word":"P.E. (PE)","star":true,"pos":"名","meaning":"体育（physical educationの略）","example":"She especially liked her PE class.","circle":false},
  {"no":1580,"word":"peace","star":false,"pos":"名","meaning":"平和","example":"I am going to talk about war and peace.","circle":false},
  {"no":1581,"word":"peaceful","star":false,"pos":"形","meaning":"平和な、おだやかな","example":"I hope that the world will be peaceful.","circle":true},
  {"no":1582,"word":"peach","star":true,"pos":"名","meaning":"モモ","example":"I want two lemons and three peaches.","circle":false},
  {"no":1583,"word":"pen","star":true,"pos":"名","meaning":"ペン","example":"May I use your pen?","circle":false},
  {"no":1584,"word":"pencil","star":true,"pos":"名","meaning":"鉛筆","example":"May I use your pencil?","circle":false},
  {"no":1585,"word":"penguin","star":false,"pos":"名","meaning":"ペンギン","example":"You can see some penguins at the aquarium.","circle":true},
  {"no":1586,"word":"people","star":false,"pos":"名","meaning":"人々、国民","example":"Many people visit shrines on New Year's Day.","circle":false},
  {"no":1587,"word":"pepper","star":false,"pos":"名","meaning":"コショウ","example":"I usually eat steak with salt and pepper.","circle":true},
  {"no":1588,"word":"percent","star":false,"pos":"名","meaning":"パーセント","example":"Seventy percent of the students come to school by bike.","circle":false},
  {"no":1589,"word":"perfect","star":false,"pos":"形","meaning":"完全な、申し分ない","example":"His answer was perfect.","circle":false},
  {"no":1590,"word":"perform","star":false,"pos":"動","meaning":"演じる、演奏する","example":"Our class performed very well at the school festival.","circle":false},
  {"no":1591,"word":"performance","star":false,"pos":"名","meaning":"上演、演奏、演技","example":"His rakugo performance was wonderful.","circle":false},
  {"no":1592,"word":"performer","star":false,"pos":"名","meaning":"演技者","example":"The performer was very good at singing.","circle":true},
  {"no":1593,"word":"perhaps","star":false,"pos":"副","meaning":"たぶん、おそらく","example":"Perhaps I can go with you.","circle":true},
  {"no":1594,"word":"period","star":false,"pos":"名","meaning":"期間、時代、（授業の）時間","example":"The castle was built in the Edo Period.","circle":false},
  {"no":1595,"word":"permission","star":false,"pos":"名","meaning":"許し、許可","example":"You must have permission to go into this building.","circle":true},
  {"no":1596,"word":"person","star":false,"pos":"名","meaning":"人","example":"He is a nice person.","circle":false},
  {"no":1597,"word":"personal","star":false,"pos":"形","meaning":"個人的な、個人の","example":"In Japan, we call a personal computer “pasokon”.","circle":false},
  {"no":1598,"word":"personal computer","star":false,"pos":"名","meaning":"パソコン（PCとも言う）","example":"This personal computer is very light.","circle":false},
  {"no":1599,"word":"pet","star":false,"pos":"名","meaning":"ペット","example":"Do you have any pets?","circle":false},
  {"no":1600,"word":"pharmacist","star":false,"pos":"名","meaning":"薬剤師","example":"She works as a pharmacist at a hospital.","circle":true}
];
