const WORDS23 = [
  {"no":2201,"word":"text","star":false,"pos":"名","meaning":"本文、テキスト","example":"Please read the text aloud.","circle":true},
  {"no":2202,"word":"textbook","star":true,"pos":"名","meaning":"教科書","example":"Open your textbook to page 3.","circle":false},
  {"no":2203,"word":"Thailand","star":false,"pos":"名","meaning":"タイ","example":"Many Japanese people live in Thailand.","circle":false},
  {"no":2204,"word":"than","star":false,"pos":"前・接","meaning":"～よりも","example":"I like English better than math.","circle":false},
  {"no":2205,"word":"thank","star":true,"pos":"動・名","meaning":"感謝（する）、ありがとう　　　※Thank you for ～.　～をありがとう　\nNo, thank you. いいえ、結構です    thanks to ～ ～のおかげで","example":"Thank you for your help with my homework.","circle":false},
  {"no":2206,"word":"that","star":true,"pos":"代・形・接","meaning":"①（代・形）それ（あれ）、その（あの）　　　※That's right. そのとおり\n②（代）～する（ところの）【前にある名詞を修飾する関係代名詞】\n③（接）～ということ","example":"①Who is that boy?\n②The book that I read last night was interesting.\n③I learned that we should do our best.","circle":false},
  {"no":2207,"word":"the","star":true,"pos":"冠","meaning":"その、あの","example":"The woman is always kind to me.","circle":false},
  {"no":2208,"word":"theater","star":false,"pos":"名","meaning":"劇場","example":"Let's go to a movie theater.","circle":false},
  {"no":2209,"word":"their","star":false,"pos":"代","meaning":"彼（彼女）らの、それらの","example":"Children learn many things from their parents.","circle":false},
  {"no":2210,"word":"theirs","star":false,"pos":"代","meaning":"彼（彼女）らのもの、それらのもの","example":"This soccer ball is theirs.","circle":false},
  {"no":2211,"word":"them","star":false,"pos":"代","meaning":"彼（彼女）を（に）、それらを（に）","example":"I have two dogs.  I love them.","circle":false},
  {"no":2212,"word":"themselves","star":false,"pos":"代","meaning":"彼（彼女）ら自身        ※by themselves 彼ら自身で","example":"They did it by themselves.","circle":false},
  {"no":2213,"word":"then","star":false,"pos":"副・名","meaning":"それでは、それから、その時","example":"I ate dinner, then washed my dishes.","circle":false},
  {"no":2214,"word":"there","star":false,"pos":"副","meaning":"そこに（で）　　　　　※over there  向こうに","example":"I want to go to the library.  Do you know how to get there?","circle":false},
  {"no":2215,"word":"these","star":false,"pos":"代・形","meaning":"これら（の）","example":"Can you carry these books for me?","circle":false},
  {"no":2216,"word":"they","star":false,"pos":"代","meaning":"彼（彼女）は（が）","example":"They speak four main languages in Singapore.","circle":false},
  {"no":2217,"word":"thick","star":false,"pos":"形","meaning":"厚い、太い、濃い","example":"This book has many pages, so it is very thick.","circle":true},
  {"no":2218,"word":"thin","star":false,"pos":"形","meaning":"やせた、（紙などが）薄い","example":"Our teacher is very thin.","circle":false},
  {"no":2219,"word":"thing","star":false,"pos":"名","meaning":"物、事","example":"What is the most important thing to you?","circle":false},
  {"no":2220,"word":"think","star":true,"pos":"動","meaning":"（～と）考える、（～だと）思う　  ※think of ～　～を思いつく\n　【活用】 think - thought - thought","example":"I think that he is right.","circle":false},
  {"no":2221,"word":"thinking","star":false,"pos":"名","meaning":"考え、思考","example":"I like your way of thinking.","circle":false},
  {"no":2222,"word":"third","star":true,"pos":"名・形","meaning":"３番目（の）","example":"This is my third visit to Kinosaki hot springs.","circle":false},
  {"no":2223,"word":"thirsty","star":false,"pos":"形","meaning":"のどがかわいた","example":"I'm very thirsty.  Give me something to drink.","circle":false},
  {"no":2224,"word":"thirteen","star":true,"pos":"名・形","meaning":"１３（の）","example":"There were thirteen people on the bus.","circle":false},
  {"no":2225,"word":"thirteenth","star":false,"pos":"名・形","meaning":"１３番目（の）","example":"I live on the thirteenth floor.","circle":false},
  {"no":2226,"word":"thirtieth","star":false,"pos":"名・形","meaning":"３０番目（の）","example":"My room is on the thirtieth floor.","circle":false},
  {"no":2227,"word":"thirty","star":true,"pos":"名・形","meaning":"３０（の）","example":"It takes about thirty minutes to go to school.","circle":false},
  {"no":2228,"word":"this","star":true,"pos":"代・形","meaning":"これ、この","example":"I love this book.","circle":false},
  {"no":2229,"word":"those","star":false,"pos":"代・形","meaning":"それら（の）、あれら（の）","example":"Look at those beautiful stars.","circle":false},
  {"no":2230,"word":"though","star":false,"pos":"接","meaning":"～だけれども","example":"Though it was very cold, he went out without a coat.","circle":false},
  {"no":2231,"word":"thousand","star":false,"pos":"名・形","meaning":"１，０００（の）    ※thousands of ～ 何千もの～","example":"A: How much is this?  B: It's one thousand yen.","circle":false},
  {"no":2232,"word":"three","star":true,"pos":"名・形","meaning":"３（の）","example":"There are three people in my family.","circle":false},
  {"no":2233,"word":"throat","star":false,"pos":"名","meaning":"のど","example":"I have a sore throat today.","circle":true},
  {"no":2234,"word":"through","star":false,"pos":"前","meaning":"～を通って、～を通して","example":"I made a lot of friends through soccer.","circle":false},
  {"no":2235,"word":"throw","star":true,"pos":"動","meaning":"投げる　　※throw away 捨てる　【活用】 throw - threw - thrown","example":"You shold throw the ball like this.","circle":false},
  {"no":2236,"word":"Thursday","star":true,"pos":"名","meaning":"木曜日","example":"I take piano lessons on Thursdays.","circle":false},
  {"no":2237,"word":"ticket","star":false,"pos":"名","meaning":"切符、チケット","example":"The tickets are sold over there.","circle":false},
  {"no":2238,"word":"tie","star":false,"pos":"名","meaning":"ネクタイ","example":"I bought a tie for my father.","circle":false},
  {"no":2239,"word":"tiger","star":true,"pos":"名","meaning":"トラ","example":"There are two tigers in this zoo.","circle":false},
  {"no":2240,"word":"tight","star":false,"pos":"形・副","meaning":"堅い（く）","example":"We won the game and held each other tight.","circle":true},
  {"no":2241,"word":"till","star":false,"pos":"前・接","meaning":"～まで","example":"Please wait here till I come back.","circle":true},
  {"no":2242,"word":"time","star":true,"pos":"名","meaning":"①時刻、時間　\n②回、度\n※for the first time  初めて   for a long time 長い間\nin time 遅れずに、やがて　on time 時間どおりに","example":"①Hurry up!  You don't have much time.\n②I made an English speech for the first time.","circle":false},
  {"no":2243,"word":"tiny","star":false,"pos":"形","meaning":"とても小さい","example":"The baby is so tiny and cute.","circle":true},
  {"no":2244,"word":"tired","star":true,"pos":"形","meaning":"疲れて","example":"Today I ran 5,000 meters.  I am very tired.","circle":false},
  {"no":2245,"word":"tissue","star":false,"pos":"名","meaning":"ティッシュペーパー","example":"Will you get some tissues for me, please?","circle":true},
  {"no":2246,"word":"title","star":false,"pos":"名","meaning":"タイトル、題名","example":"What is the title of your favorite book?","circle":true},
  {"no":2247,"word":"to","star":true,"pos":"前","meaning":"（行き先・到着点）～へ（に）、（相手・対象）～に","example":"I'm going to give some flowers to my mother.","circle":false},
  {"no":2248,"word":"toast","star":false,"pos":"動・名","meaning":"（動）こんがり焼く、トーストする　（名）トースト","example":"I usually eat toast for breakfast.","circle":true},
  {"no":2249,"word":"today","star":false,"pos":"副・名","meaning":"今日（は）","example":"I am fine today.","circle":false},
  {"no":2250,"word":"toe","star":true,"pos":"名","meaning":"足の指、爪先","example":"I hurt my toe when I kicked the ball.","circle":true},
  {"no":2251,"word":"together","star":true,"pos":"副","meaning":"いっしょに","example":"Let's do the homework together.","circle":false},
  {"no":2252,"word":"toilet","star":false,"pos":"名","meaning":"トイレ、化粧室","example":"Can I use the toilet?","circle":false},
  {"no":2253,"word":"tomato","star":true,"pos":"名","meaning":"トマト","example":"I like tomatoes very much.","circle":false},
  {"no":2254,"word":"tomorrow","star":false,"pos":"副・名","meaning":"明日（は）","example":"It will be rainy tomorrow.","circle":false},
  {"no":2255,"word":"ton","star":false,"pos":"名","meaning":"トン","example":"The weight of a big elephant is about six tons.","circle":true},
  {"no":2256,"word":"tongue","star":false,"pos":"名","meaning":"舌","example":"The doctor asked the boy to put his tongue out.","circle":true},
  {"no":2257,"word":"tonight","star":false,"pos":"副・名","meaning":"今夜（は）","example":"The stars are so beautiful tonight.","circle":false},
  {"no":2258,"word":"too","star":true,"pos":"副","meaning":"①（～も）また　\n②あまりに（～）すぎる　\n※Me, too. 私も 　too ～ to …　あまりにも～なので…できない","example":"①A: I like dogs.  B: Me, too. \n②I am too tired to do this homework.","circle":false},
  {"no":2259,"word":"tool","star":false,"pos":"名","meaning":"手段、道具","example":"English is a tool for communication.","circle":false},
  {"no":2260,"word":"tooth","star":true,"pos":"名","meaning":"歯　　【複数】 teeth","example":"Brush your teeth before you go to bed.","circle":false},
  {"no":2261,"word":"toothache","star":false,"pos":"名","meaning":"歯痛","example":"I have a toothache.  I need to see a dentist.","circle":false},
  {"no":2262,"word":"toothbrush","star":false,"pos":"名","meaning":"歯ブラシ","example":"You should change your toothbrush every month.","circle":true},
  {"no":2263,"word":"top","star":false,"pos":"名・形","meaning":"一番上の部分（の）、頂上（の）、てっぺん（の）","example":"Can you see the top of Mt. Maya from here?","circle":false},
  {"no":2264,"word":"topic","star":false,"pos":"名","meaning":"話題、テーマ、トピック","example":"The topic of today's lesson is recycling.","circle":true},
  {"no":2265,"word":"total","star":false,"pos":"名","meaning":"総計、合計　　　　※in total  合計で、全部で","example":"A: How much is it in total?  B: It's 3,000 yen.","circle":false},
  {"no":2266,"word":"touch","star":false,"pos":"動・名","meaning":"（動）触れる、触る　（名）接触","example":"Don't touch this.  It's still hot.","circle":false},
  {"no":2267,"word":"tough","star":false,"pos":"形","meaning":"たくましい、丈夫な、困難な、難しい","example":"Naomi Uemura was tough and climbed many high mountains.","circle":true},
  {"no":2268,"word":"tour","star":false,"pos":"名","meaning":"旅行、ツアー","example":"The tour was exciting.","circle":false},
  {"no":2269,"word":"tourist","star":false,"pos":"名","meaning":"観光客、旅行者","example":"Many tourists visit Himeji Castle in spring.","circle":true},
  {"no":2270,"word":"tournament","star":false,"pos":"名","meaning":"勝ち抜き戦、トーナメント","example":"I will join the tennis tournament.","circle":false},
  {"no":2271,"word":"toward","star":false,"pos":"前","meaning":"～の方へ、～に向かって","example":"The train is going toward Osaka.","circle":true},
  {"no":2272,"word":"towel","star":false,"pos":"名","meaning":"手拭い、タオル","example":"Whose towel is this?  I found it in the classroom.","circle":false},
  {"no":2273,"word":"tower","star":true,"pos":"名","meaning":"塔、タワー","example":"There is a tall clock tower in my town.","circle":false},
  {"no":2274,"word":"town","star":true,"pos":"名","meaning":"町","example":"There are two big parks in this town.","circle":false},
  {"no":2275,"word":"toy","star":false,"pos":"名","meaning":"おもちゃ","example":"Kendama is a Japanese toy.","circle":false},
  {"no":2276,"word":"track","star":false,"pos":"名","meaning":"線路 、走路、トラック   　※track and field　 陸上競技","example":"Take the train from Track No.1.","circle":false},
  {"no":2277,"word":"track and field","star":true,"pos":"名","meaning":"陸上競技","example":"I'm in the track and field club.","circle":false},
  {"no":2278,"word":"trade","star":false,"pos":"名","meaning":"貿易、取引","example":"Japan developed through trade with foreign countries.","circle":true},
  {"no":2279,"word":"tradition","star":false,"pos":"名","meaning":"伝統","example":"Otoshidama is one of the Japanese New Year traditions.","circle":false},
  {"no":2280,"word":"traditional","star":false,"pos":"形","meaning":"伝統的な","example":"Banshu Kabuki is a traditional custom in Hyogo.","circle":false},
  {"no":2281,"word":"traffic","star":false,"pos":"名","meaning":"交通（量）","example":"There was a lot of traffic this morning.","circle":true},
  {"no":2282,"word":"traffic light","star":false,"pos":"名","meaning":"交通信号（灯）","example":"Turn right at the next traffic light.","circle":false},
  {"no":2283,"word":"tragic","star":false,"pos":"形","meaning":"悲惨な、痛ましい","example":"There are a lot of tragic stories about the war.","circle":true},
  {"no":2284,"word":"train","star":true,"pos":"名","meaning":"電車   　 ※change trains 電車を乗り換える","example":"I go to school by train.","circle":false},
  {"no":2285,"word":"trainer","star":false,"pos":"名","meaning":"（動物の）調教師、（運動選手の）トレーナー","example":"The trainer taught the dog some tricks.","circle":true},
  {"no":2286,"word":"training","star":false,"pos":"名","meaning":"訓練　　　　※training center  訓練センター","example":"There is a training center for teachers in my town.","circle":false},
  {"no":2287,"word":"translate","star":false,"pos":"動","meaning":"翻訳する、訳す","example":"It is difficult to translate some English words.","circle":true},
  {"no":2288,"word":"translation","star":false,"pos":"名","meaning":"翻訳","example":"I read a Japanese translation of the novel.","circle":true},
  {"no":2289,"word":"translator","star":false,"pos":"名","meaning":"翻訳者、通訳者、翻訳機","example":"I want to study English hard to be a translator.","circle":true},
  {"no":2290,"word":"trash","star":false,"pos":"名","meaning":"ごみ","example":"Please don't throw trash on the ground.","circle":true},
  {"no":2291,"word":"travel","star":true,"pos":"動・名","meaning":"旅行（する）、旅（をする）","example":"He traveled around the world.","circle":false},
  {"no":2292,"word":"traveler","star":false,"pos":"名","meaning":"旅行者","example":"Many travelers visit Hyogo through the year.","circle":true},
  {"no":2293,"word":"treasure","star":false,"pos":"名","meaning":"重要なもの、宝物","example":"My family is my treasure.","circle":false},
  {"no":2294,"word":"treat","star":false,"pos":"動","meaning":"扱う","example":"Don't treat me like a child.","circle":true},
  {"no":2295,"word":"tree","star":true,"pos":"名","meaning":"木","example":"There is a very old cherry tree in my town.","circle":false},
  {"no":2296,"word":"triangle","star":true,"pos":"名","meaning":"三角形","example":"A triangle has three lines and three corners.","circle":true},
  {"no":2297,"word":"triathlon","star":false,"pos":"名","meaning":"トライアスロン","example":"In a triathlon, you swim, ride a bike, and run.","circle":true},
  {"no":2298,"word":"trick","star":false,"pos":"名","meaning":"いたずら、芸当、トリック","example":"I know some magic tricks.","circle":false},
  {"no":2299,"word":"trip","star":true,"pos":"名","meaning":"旅行　　※go on a trip  旅行に出かける　　school trip  修学旅行","example":"My family went on a trip to Awaji Island last weekend.","circle":false},
  {"no":2300,"word":"trouble","star":false,"pos":"名","meaning":"面倒、困難、悩み　※be in trouble   困っている、悩んでいる","example":"I am in trouble now.","circle":false}
];
