const WORDS15 = [
  {"no":1401,"word":"Mr.","star":true,"pos":"名","meaning":"（男性への敬称） ～さん、～先生","example":"Mr. Tanaka is my English teacher.","circle":false},
  {"no":1402,"word":"Mrs.","star":false,"pos":"名","meaning":"（結婚している女性への敬称）～婦人、～さん、～先生","example":"Mrs. Walker is our English teacher.","circle":false},
  {"no":1403,"word":"Ms.","star":true,"pos":"名","meaning":"（女性への敬称） ～さん、～先生","example":"Ms. Saito is my math teacher.","circle":false},
  {"no":1404,"word":"Mt.","star":false,"pos":"名","meaning":"～山（山の名の前につける）","example":"Mt. Hachibuse is good for skiing in winter.","circle":false},
  {"no":1405,"word":"much","star":true,"pos":"形・副\n名・代","meaning":"（形）多量の、たくさんの　（副）とても（very, soなどとともに）\n（名・代）多量、たくさん　　【活用】 much - more - most","example":"①I don't have much money.\n②I don't know much about the history of Hyogo prefecture.","circle":false},
  {"no":1406,"word":"mug","star":false,"pos":"名","meaning":"マグカップ","example":"My friend gave me this mug on my birthday.","circle":true},
  {"no":1407,"word":"museum","star":true,"pos":"名","meaning":"博物館、美術館","example":"Hyogo has many wonderful museums.","circle":false},
  {"no":1408,"word":"mushroom","star":true,"pos":"名","meaning":"キノコ、マッシュルーム","example":"You can enjoy eating many kinds of mushrooms in autumn.","circle":true},
  {"no":1409,"word":"music","star":true,"pos":"名","meaning":"音楽","example":"Listen to this music.","circle":false},
  {"no":1410,"word":"musical","star":false,"pos":"名・形","meaning":"（名）ミュージカル　（形）音楽の","example":"You can see famous musicals in Takarazuka.","circle":true},
  {"no":1411,"word":"musician","star":true,"pos":"名","meaning":"音楽家","example":"Who's your favorite musician?","circle":false},
  {"no":1412,"word":"must","star":false,"pos":"助","meaning":"①しなければならない　\n②～にちがいない","example":"①We must respect each other. \n②She must be a famous singer.","circle":false},
  {"no":1413,"word":"mustard","star":false,"pos":"名","meaning":"からし、マスタード","example":"A: Do you want some mustard?  B: No, thank you.","circle":true},
  {"no":1414,"word":"my","star":true,"pos":"代","meaning":"私の","example":"Key please.  My room number is 345.","circle":false},
  {"no":1415,"word":"myself","star":false,"pos":"代","meaning":"私自身　　　※by myself  　自分で、ひとり（ぼっち）で","example":"I want to talk about myself.","circle":false},
  {"no":1416,"word":"mysterious","star":false,"pos":"形","meaning":"神秘的な","example":"This is the most mysterious place in the world.","circle":false},
  {"no":1417,"word":"mystery","star":false,"pos":"名","meaning":"謎","example":"My hobby is reading mystery books.","circle":false},
  {"no":1418,"word":"nail","star":false,"pos":"名","meaning":"つめ","example":"You should cut your nails.","circle":false},
  {"no":1419,"word":"name","star":true,"pos":"動・名","meaning":"名前（を付ける）","example":"Do you know the name of this musician?","circle":false},
  {"no":1420,"word":"nap","star":false,"pos":"名","meaning":"昼寝、仮眠      ※take a nap 昼寝をする","example":"I will take a nap after lunch.","circle":true},
  {"no":1421,"word":"narrow","star":false,"pos":"形","meaning":"（幅が）狭い","example":"This road is narrow.","circle":false},
  {"no":1422,"word":"nation","star":false,"pos":"名","meaning":"国家","example":"There was a war between the two nations.","circle":false},
  {"no":1423,"word":"national","star":false,"pos":"形","meaning":"国家の、国立の 　　 ※national park 国立公園","example":"Hyogo has San'in Kaigan National Park.  It is beautiful.","circle":false},
  {"no":1424,"word":"national holiday","star":false,"pos":"名","meaning":"国民の祝日","example":"Children's Day is a national holiday.","circle":false},
  {"no":1425,"word":"native","star":false,"pos":"形","meaning":"その土地に生まれ育った","example":"You should ask native people about the town.","circle":false},
  {"no":1426,"word":"natural","star":false,"pos":"形","meaning":"自然の","example":"We had a big natural disaster last month.","circle":false},
  {"no":1427,"word":"nature","star":true,"pos":"名","meaning":"自然","example":"We love nature.","circle":false},
  {"no":1428,"word":"near","star":false,"pos":"前","meaning":"～の近くに（の）","example":"They walked on the beach near the hotel.","circle":false},
  {"no":1429,"word":"nearby","star":false,"pos":"形・副","meaning":"近くの（に、で）","example":"My grandparents live in a nearby town.","circle":true},
  {"no":1430,"word":"necessary","star":false,"pos":"形","meaning":"必要な","example":"Sleeping is necessary for good health.","circle":false},
  {"no":1431,"word":"neck","star":false,"pos":"名","meaning":"首","example":"What is the animal with a long neck?","circle":false},
  {"no":1432,"word":"necklace","star":false,"pos":"名","meaning":"ネックレス、首飾り","example":"I gave my mom a necklace on Mother's Day.","circle":true},
  {"no":1433,"word":"need","star":false,"pos":"動・名","meaning":"①（動）～を必要とする　　※need to ～　～する必要がある　　　\n②（名）必要、必要性 　　　　 ※in need  必要で、困って","example":"①We need water to live.\n②He felt the need to sleep.","circle":false},
  {"no":1434,"word":"needle","star":false,"pos":"名","meaning":"針","example":"This plant has many sharp needles.","circle":true},
  {"no":1435,"word":"negative","star":false,"pos":"形","meaning":"否定的な","example":"You should not be so negative about everything.","circle":true},
  {"no":1436,"word":"neighbor","star":false,"pos":"名","meaning":"近所の人、隣人","example":"Our neighbors invited us to their party.","circle":false},
  {"no":1437,"word":"neighborhood","star":false,"pos":"名","meaning":"近隣（の人々）","example":"I like living in this neighborhood.","circle":false},
  {"no":1438,"word":"neither","star":false,"pos":"副","meaning":"～もまた・・・ない    ※Me, neither. 　私も・・・ない","example":"A: I don't like carrots.  B: Me, neither.","circle":true},
  {"no":1439,"word":"nephew","star":false,"pos":"名","meaning":"おい","example":"My nephew practices karate.","circle":true},
  {"no":1440,"word":"nervous","star":false,"pos":"形","meaning":"神経質な、緊張して","example":"What made him nervous?","circle":false},
  {"no":1441,"word":"nest","star":false,"pos":"名","meaning":"巣","example":"I saw baby birds in a nest.","circle":true},
  {"no":1442,"word":"net","star":false,"pos":"名","meaning":"網、ネット","example":"They caught fish with nets.","circle":false},
  {"no":1443,"word":"never","star":true,"pos":"副","meaning":"決して～ない、まだ一度も～ない","example":"I've never felt like this before.","circle":false},
  {"no":1444,"word":"new","star":true,"pos":"形","meaning":"新しい","example":"I bought a new bike yesterday.","circle":false},
  {"no":1445,"word":"New Year","star":false,"pos":"名","meaning":"新年","example":"Rice cake (mochi) is made for the New Year.","circle":false},
  {"no":1446,"word":"New Year's Day","star":true,"pos":"名","meaning":"元日","example":"Japanese people visit shrines on New Year's Day.","circle":false},
  {"no":1447,"word":"New Year's Eve","star":true,"pos":"名","meaning":"大みそか","example":"Japanese people eat special soba on New Year's Eve.","circle":false},
  {"no":1448,"word":"New York","star":false,"pos":"名","meaning":"ニューヨーク","example":"New York is a very big city.","circle":false},
  {"no":1449,"word":"New Zealand","star":false,"pos":"名","meaning":"ニュージランド","example":"I have been to New Zealand twice.","circle":false},
  {"no":1450,"word":"news","star":false,"pos":"名","meaning":"報道、ニュース","example":"I use the Internet to read and watch English news.","circle":false},
  {"no":1451,"word":"newspaper","star":true,"pos":"名","meaning":"新聞","example":"My mother reads the newspaper every morning.","circle":false},
  {"no":1452,"word":"next","star":false,"pos":"形・副","meaning":"次の（に）、となりの（に）　※next to ～　～のとなりに","example":"We'll have an exam next week.","circle":false},
  {"no":1453,"word":"nice","star":true,"pos":"形","meaning":"すてきな、すばらしい　※Nice to meet you. はじめまして","example":"This is a nice picture.","circle":false},
  {"no":1454,"word":"niece","star":false,"pos":"名","meaning":"めい","example":"My niece loves reading books.","circle":true},
  {"no":1455,"word":"night","star":true,"pos":"名","meaning":"夜、晩　　※Good night.　おやすみなさい","example":"Are you free on Saturday night?","circle":false},
  {"no":1456,"word":"nine","star":true,"pos":"名・形","meaning":"９（の）","example":"The nine children will dance together.","circle":false},
  {"no":1457,"word":"nineteen","star":true,"pos":"名・形","meaning":"１９（の）","example":"My brother will be nineteen years old next month.","circle":false},
  {"no":1458,"word":"nineteenth","star":false,"pos":"名・形","meaning":"１９番目（の）","example":"The room is on the nineteenth floor.","circle":false},
  {"no":1459,"word":"ninety","star":true,"pos":"名・形","meaning":"９０（の）","example":"My grandmother is ninety years old.","circle":false},
  {"no":1460,"word":"ninth","star":false,"pos":"名・形","meaning":"９番目（の）","example":"I am in the ninth grade.","circle":false},
  {"no":1461,"word":"no","star":true,"pos":"形・副","meaning":"①いいえ　\n②何も～ない","example":"①A: Is this your book?  B: No, it isn't.\n②There was no water in the glass.","circle":false},
  {"no":1462,"word":"Nobel Prize","star":false,"pos":"名","meaning":"ノーベル賞","example":"Many Japanese people have received the Nobel Prize.","circle":true},
  {"no":1463,"word":"nobody","star":false,"pos":"代","meaning":"だれも～ない","example":"Nobody can answer this question.","circle":false},
  {"no":1464,"word":"nod","star":false,"pos":"動","meaning":"うなずく","example":"Nodding is helpful for better communication.","circle":true},
  {"no":1465,"word":"noise","star":false,"pos":"名","meaning":"物音、騒音","example":"Don't make too much noise while you are eating.","circle":true},
  {"no":1466,"word":"noisy","star":false,"pos":"形","meaning":"さわがしい、うるさい","example":"Don't be too noisy in the classroom.","circle":false},
  {"no":1467,"word":"noodle","star":true,"pos":"名","meaning":"麺","example":"Japanese people like noodles.","circle":false},
  {"no":1468,"word":"noon","star":false,"pos":"名","meaning":"正午、昼の１２時","example":"Lunch time starts at noon.","circle":false},
  {"no":1469,"word":"normal","star":false,"pos":"形","meaning":"普通の","example":"It's softer than a normal tennis ball.","circle":false},
  {"no":1470,"word":"north","star":false,"pos":"名・形・副","meaning":"北（の、へ）、北方","example":"North is at the top on a map.","circle":false},
  {"no":1471,"word":"northern","star":false,"pos":"形","meaning":"北の、北部地方の","example":"Tajima is the northern part of Hyogo.","circle":true},
  {"no":1472,"word":"nose","star":true,"pos":"名","meaning":"鼻","example":"An elephant has a long nose.","circle":false},
  {"no":1473,"word":"not","star":true,"pos":"副","meaning":"～でない、～しない","example":"He is not a teacher.","circle":false},
  {"no":1474,"word":"note","star":false,"pos":"名","meaning":"メモ、手帳　　※make(take) a note　メモをとる、書き留める","example":"You should take some notes when you listen.","circle":false},
  {"no":1475,"word":"notebook","star":true,"pos":"名","meaning":"ノート、手帳","example":"Don't forget to bring your notebooks.","circle":false},
  {"no":1476,"word":"nothing","star":false,"pos":"名・代","meaning":"何も～ない","example":"They could do nothing to save their forest.","circle":false},
  {"no":1477,"word":"notice","star":false,"pos":"動","meaning":"気付く","example":"I didn't notice the sign.","circle":false},
  {"no":1478,"word":"novel","star":false,"pos":"名","meaning":"小説","example":"I am interested in French novels.","circle":false},
  {"no":1479,"word":"November","star":true,"pos":"名","meaning":"１１月","example":"We have our school festival in November.","circle":false},
  {"no":1480,"word":"now","star":false,"pos":"副・名","meaning":"今（は）、現在（は）","example":"Now I am watching TV.","circle":false},
  {"no":1481,"word":"nowadays","star":false,"pos":"副","meaning":"今日では","example":"Nowadays, I take my smartphone everywhere.","circle":true},
  {"no":1482,"word":"nuclear","star":false,"pos":"形","meaning":"核の、原子力の","example":"I'm against nuclear power.","circle":true},
  {"no":1483,"word":"number","star":true,"pos":"名","meaning":"数、（電話）番号","example":"My phone number is 1234-5678.","circle":false},
  {"no":1484,"word":"nurse","star":true,"pos":"名","meaning":"看護師、保健の先生　　※go to the nurse  保健の先生の所へ行く","example":"You don't look well.  Let's go to the nurse.","circle":false},
  {"no":1485,"word":"nursery","star":false,"pos":"名","meaning":"保育園（＝nursery school)","example":"I want to be a nursery school teacher.","circle":false},
  {"no":1486,"word":"nut","star":true,"pos":"名","meaning":"木の実","example":"Eating nuts is good for our health.","circle":true},
  {"no":1487,"word":"obey","star":false,"pos":"動","meaning":"従う","example":"Students should obey school rules.","circle":true},
  {"no":1488,"word":"object","star":false,"pos":"名","meaning":"物、物体","example":"You can see many interesting objects at the museum.","circle":true},
  {"no":1489,"word":"observe","star":false,"pos":"動","meaning":"観察する","example":"You should observe how the color changes.","circle":true},
  {"no":1490,"word":"occupation","star":false,"pos":"名","meaning":"職業","example":"May I ask your occupation?","circle":false},
  {"no":1491,"word":"ocean","star":false,"pos":"名","meaning":"大洋、海","example":"Some kinds of whale live in this ocean.","circle":false},
  {"no":1492,"word":"o'clock","star":false,"pos":"副","meaning":"～時","example":"It's eight o'clock.","circle":false},
  {"no":1493,"word":"October","star":true,"pos":"名","meaning":"１０月","example":"October is the best month to enjoy sports in Japan.","circle":false},
  {"no":1494,"word":"octopus","star":false,"pos":"名","meaning":"タコ","example":"Akashi city is very famous for octopuses.","circle":false},
  {"no":1495,"word":"of","star":false,"pos":"前","meaning":"①（所有・所属）～の　\n②（部分・中身）～の　\n③（内容）～のこと、～について\n④（同格）A of B 　BというA\n⑤（中身）～の（入った）","example":"①I want to learn about the cultures of different countries.\n②Many of the students enjoyed his English class.\n③I often think of war and peace.\n④We love the city of Kobe.\n⑤My mother gave me a cup of tea.","circle":false},
  {"no":1496,"word":"off","star":false,"pos":"副","meaning":"（場所を)離れて、（物を）離して","example":"Please take off your shoes here.","circle":false},
  {"no":1497,"word":"offer","star":false,"pos":"動","meaning":"提供する、申し出る","example":"Some of my friends offered me some help.","circle":true},
  {"no":1498,"word":"office","star":false,"pos":"名","meaning":"事務所","example":"Please come to the office on the third floor.","circle":false},
  {"no":1499,"word":"officer","star":false,"pos":"名","meaning":"係員、役人　　※police officer 警察官","example":"I asked an officer the way to the station.","circle":false},
  {"no":1500,"word":"official","star":false,"pos":"名・形","meaning":"①（名）係官、職員\n②（形）公式の","example":"①I am a government official.\n②He got an official letter from his school.","circle":false}
];
