const WORDS12 = [
  {"no":1101,"word":"illegal","star":false,"pos":"形","meaning":"違法の","example":"Riding bikes is illegal here.","circle":true},
  {"no":1102,"word":"image","star":false,"pos":"名","meaning":"像、画像、イメージ","example":"Images from manga have influenced his designs.","circle":false},
  {"no":1103,"word":"imagination","star":false,"pos":"名","meaning":"想像、想像力","example":"He has a lot of imagination and creates wonderful stories.","circle":true},
  {"no":1104,"word":"imagine","star":false,"pos":"動","meaning":"想像する","example":"It's difficult for me to imagine a big earthquake.","circle":false},
  {"no":1105,"word":"immediately","star":false,"pos":"副","meaning":"すぐに、ただちに","example":"Call an ambulance immediately.","circle":true},
  {"no":1106,"word":"impact","star":false,"pos":"名","meaning":"衝撃","example":"That picture had a big impact on people.","circle":false},
  {"no":1107,"word":"importance","star":false,"pos":"名","meaning":"重要性、大切さ","example":"We realized the importance of team spirit.","circle":false},
  {"no":1108,"word":"important","star":false,"pos":"形","meaning":"重要な、重大な","example":"It's important for us to think about peace.","circle":false},
  {"no":1109,"word":"impossible","star":false,"pos":"形","meaning":"不可能な","example":"It's impossible for me to speak three languages.","circle":false},
  {"no":1110,"word":"impressed","star":false,"pos":"形","meaning":"感心して、感動して","example":"I was impressed when I heard the song.","circle":true},
  {"no":1111,"word":"improve","star":false,"pos":"動","meaning":"よりよくする、改良する","example":"How can I improve my English?","circle":false},
  {"no":1112,"word":"in","star":true,"pos":"前","meaning":"①（場所）～（の中）に（で、の）　\n②（期間）～（のうち）に\n③（範囲・対象）～の点で","example":"①He lives in America. \n②I cleaned my room in the morning. \n③I'm interested in Japanese kimonos.","circle":false},
  {"no":1113,"word":"include","star":false,"pos":"動","meaning":"含む、含める","example":"This price includes tax.","circle":true},
  {"no":1114,"word":"including","star":false,"pos":"前","meaning":"～を含めて","example":"Five people including me visited the museum.","circle":false},
  {"no":1115,"word":"increase","star":false,"pos":"動","meaning":"増える、増加する","example":"The number of visitors to Himeji Castle has increased.","circle":false},
  {"no":1116,"word":"India","star":false,"pos":"名","meaning":"インド","example":"Several languages are spoken in India.","circle":false},
  {"no":1117,"word":"Indian","star":false,"pos":"名・形","meaning":"インドの、インド人（の）","example":"I like Indian food very much.","circle":false},
  {"no":1118,"word":"Indonesia","star":false,"pos":"名","meaning":"インドネシア","example":"There are over 17,000 islands in Indonesia.","circle":true},
  {"no":1119,"word":"indoor","star":false,"pos":"形","meaning":"室内の","example":"I like indoor sports like badminton.","circle":true},
  {"no":1120,"word":"indoors","star":false,"pos":"副","meaning":"屋内で（へ）","example":"I like staying indoors in winter.","circle":true},
  {"no":1121,"word":"industry","star":false,"pos":"名","meaning":"工業","example":"About 40% of Japanese energy is used in industry.","circle":false},
  {"no":1122,"word":"influence","star":false,"pos":"動・名","meaning":"影響（を与える）","example":"Japanese movies influenced many foreign movies.","circle":false},
  {"no":1123,"word":"information","star":false,"pos":"名","meaning":"情報","example":"We need to gather information about China.","circle":false},
  {"no":1124,"word":"injure","star":false,"pos":"動","meaning":"傷つける、けがをさせる","example":"Many people were injured in the accident.","circle":false},
  {"no":1125,"word":"injured","star":false,"pos":"形","meaning":"けがをした","example":"I was injured in a basketball game.","circle":true},
  {"no":1126,"word":"ink","star":false,"pos":"名","meaning":"インク","example":"Please use red ink.","circle":false},
  {"no":1127,"word":"inside","star":false,"pos":"前・副","meaning":"～の中に（で）","example":"We put a ball inside the box.","circle":false},
  {"no":1128,"word":"instant","star":false,"pos":"形","meaning":"すぐの、即時の","example":"I sometimes have instant noodles late at night.","circle":true},
  {"no":1129,"word":"instead","star":false,"pos":"副","meaning":"代わりに　　※instead of ～　～の代わりに","example":"He went to the party instead of me.","circle":false},
  {"no":1130,"word":"instruction","star":false,"pos":"名","meaning":"指示、命令、指図","example":"Follow the instructions carefully.","circle":true},
  {"no":1131,"word":"instrument","star":false,"pos":"名","meaning":"楽器","example":"What instrument do you want to play?","circle":false},
  {"no":1132,"word":"interest","star":false,"pos":"動・名","meaning":"（動）興味をかきたてる　（名）興味","example":"I don't have any interest in computer games.","circle":true},
  {"no":1133,"word":"interested","star":false,"pos":"形","meaning":"※be interested in ～　～に興味を持っている","example":"I'm interested in Korean dramas.","circle":false},
  {"no":1134,"word":"interesting","star":true,"pos":"形","meaning":"おもしろい、興味深い","example":"This book is interesting.","circle":false},
  {"no":1135,"word":"international","star":false,"pos":"形","meaning":"国際的な","example":"Kobe is called an international city.","circle":false},
  {"no":1136,"word":"Internet","star":false,"pos":"名","meaning":"インターネット　　※on the Internet  インターネットで","example":"You can use the Internet to find the answer.","circle":false},
  {"no":1137,"word":"interpreter","star":false,"pos":"名","meaning":"通訳者","example":"You have to study hard to be an interpreter.","circle":true},
  {"no":1138,"word":"intersection","star":false,"pos":"名","meaning":"交差点","example":"Please turn right at the next intersection.","circle":true},
  {"no":1139,"word":"interview","star":false,"pos":"動・名","meaning":"インタビュー（する）、面接（する）","example":"I'm going to have an interview test tomorrow.","circle":false},
  {"no":1140,"word":"interviewer","star":false,"pos":"名","meaning":"インタビューする人、面接官、インタビュアー","example":"The interviewer will ask you some questions.","circle":true},
  {"no":1141,"word":"into","star":false,"pos":"前","meaning":"～の中へ","example":"Come into the house.","circle":false},
  {"no":1142,"word":"introduce","star":false,"pos":"動","meaning":"～を紹介する　※introduce myself to ～　～に自己紹介する","example":"I will introduce you to my family.","circle":false},
  {"no":1143,"word":"invent","star":false,"pos":"動","meaning":"発明する","example":"I want to invent something new.","circle":false},
  {"no":1144,"word":"invention","star":false,"pos":"名","meaning":"発明、発明品","example":"The smartphone is a great invention.","circle":true},
  {"no":1145,"word":"inventor","star":false,"pos":"名","meaning":"発明家","example":"Thomas Edison is the inventor of the light bulb.","circle":true},
  {"no":1146,"word":"invite","star":false,"pos":"動","meaning":"招待する","example":"I invited my friend to my house.","circle":false},
  {"no":1147,"word":"iron","star":false,"pos":"動・名","meaning":"（動）アイロンをかける　（名）アイロン","example":"My mother irons my school shirts every day.","circle":true},
  {"no":1148,"word":"is","star":true,"pos":"動","meaning":"～である、（～に）いる、ある\n※is ～ing  ～している、しようとしている　　　【活用】 is - was - been","example":"My phone number is 1234-5678.","circle":false},
  {"no":1149,"word":"island","star":true,"pos":"名","meaning":"島","example":"Awaji Island is a part of Hyogo.","circle":false},
  {"no":1150,"word":"issue","star":false,"pos":"名","meaning":"（社会的な）問題（点）、争点","example":"Global warming is a major environmental issue.","circle":true},
  {"no":1151,"word":"it","star":true,"pos":"代","meaning":"それ（は、が）、それ（を、に）","example":"A: Where is my pen?  B: It is on the desk.","circle":false},
  {"no":1152,"word":"Italian","star":false,"pos":"名・形","meaning":"イタリアの、イタリア人（の）、イタリア語（の）","example":"I went to a good Italian restaurant yesterday.","circle":false},
  {"no":1153,"word":"Italy","star":false,"pos":"名","meaning":"イタリア","example":"He went to Italy, the U.K., and Germany.","circle":false},
  {"no":1154,"word":"its","star":false,"pos":"代","meaning":"その、それの","example":"I learned a lot about the country and its culture.","circle":false},
  {"no":1155,"word":"itself","star":false,"pos":"代","meaning":"それ自身を（に）      ※by itself  それ自身で、ひとりでに","example":"The door closes by itself.","circle":true},
  {"no":1156,"word":"jacket","star":false,"pos":"名","meaning":"上着、ジャケット","example":"I got a new jacket for my birthday.","circle":false},
  {"no":1157,"word":"jail","star":false,"pos":"名","meaning":"刑務所","example":"He is in jail for stealing a car.","circle":true},
  {"no":1158,"word":"jam","star":true,"pos":"名","meaning":"ジャム","example":"Some people eat bread with jam.","circle":false},
  {"no":1159,"word":"January","star":true,"pos":"名","meaning":"１月","example":"On January 1, people eat osechi in Japan.","circle":false},
  {"no":1160,"word":"Japan","star":true,"pos":"名","meaning":"日本","example":"I come from Japan.","circle":false},
  {"no":1161,"word":"Japanese","star":true,"pos":"名・形","meaning":"日本の、日本人（の）、日本語（の）","example":"I like Japanese music.","circle":false},
  {"no":1162,"word":"jazz","star":false,"pos":"名","meaning":"ジャズ","example":"My father likes listening to jazz.","circle":true},
  {"no":1163,"word":"jeans","star":false,"pos":"名","meaning":"ジーンズ（複数形で使う）","example":"I usually wear jeans.","circle":true},
  {"no":1164,"word":"jet","star":true,"pos":"名","meaning":"ジェット機","example":"I want to fly in a jet one day.","circle":true},
  {"no":1165,"word":"jewel","star":false,"pos":"名","meaning":"宝石","example":"The jewel was very beautiful.","circle":true},
  {"no":1166,"word":"Jewish","star":false,"pos":"形","meaning":"ユダヤ人の","example":"Jewish people live in many countries around the world.","circle":true},
  {"no":1167,"word":"job","star":true,"pos":"名","meaning":"職業、仕事","example":"I want to find a job that needs English.","circle":false},
  {"no":1168,"word":"jog","star":true,"pos":"動","meaning":"ゆっくり走る、ジョギングする","example":"I jog about half an hour every morning.","circle":true},
  {"no":1169,"word":"join","star":true,"pos":"動","meaning":"～に加わる、参加する","example":"Please join us.","circle":false},
  {"no":1170,"word":"joke","star":false,"pos":"名","meaning":"冗談、しゃれ","example":"The teacher often tells jokes.","circle":false},
  {"no":1171,"word":"journalist","star":false,"pos":"名","meaning":"ジャーナリスト","example":"She's a famous journalist.","circle":false},
  {"no":1172,"word":"journey","star":false,"pos":"名","meaning":"旅行","example":"The long journey started in China.","circle":true},
  {"no":1173,"word":"joy","star":false,"pos":"名","meaning":"喜び","example":"She jumped for joy.","circle":false},
  {"no":1174,"word":"J-pop","star":false,"pos":"名・形","meaning":"ジェーポップ（の）、日本のポップス（の）","example":"He is learning Japanese with J-pop songs.","circle":true},
  {"no":1175,"word":"judge","star":false,"pos":"動","meaning":"判断する","example":"Do not judge a person by his clothes.","circle":false},
  {"no":1176,"word":"juice","star":true,"pos":"名","meaning":"（果物、肉などの）液、ジュース","example":"I usually have orange juice for breakfast.","circle":false},
  {"no":1177,"word":"July","star":true,"pos":"名","meaning":"７月","example":"Tanabata festivals are held in July.","circle":false},
  {"no":1178,"word":"jump","star":true,"pos":"動","meaning":"跳ぶ","example":"The cat jumped on the sofa.","circle":false},
  {"no":1179,"word":"June","star":true,"pos":"名","meaning":"６月","example":"The rainy season begins in June.","circle":false},
  {"no":1180,"word":"jungle","star":false,"pos":"名","meaning":"（熱帯地方の）密林、ジャングル","example":"In the jungle, you can find many birds you have never seen.","circle":false},
  {"no":1181,"word":"junior","star":false,"pos":"形","meaning":"下位の、年下の","example":"Many junior high school students joined the festival.","circle":false},
  {"no":1182,"word":"junior high school","star":false,"pos":"名","meaning":"中学校","example":"I'm a junior high school student from Hyogo.","circle":false},
  {"no":1183,"word":"just","star":false,"pos":"副","meaning":"①ちょうど、まさに\n②ただ～だけ","example":"①Just then, he entered the bank.\n②Give me just five minutes.","circle":false},
  {"no":1184,"word":"kangaroo","star":false,"pos":"名","meaning":"カンガルー","example":"I want to visit Australia to see kangaroos.","circle":true},
  {"no":1185,"word":"keep","star":false,"pos":"動","meaning":"保存する、保つ、ずっと～である 　※keep ～ing   ～し続る\n※keep in touch  連絡をとりあう　 【活用】 keep - kept - kept","example":"Please keep your room clean.","circle":false},
  {"no":1186,"word":"keeper","star":false,"pos":"名","meaning":"飼育係","example":"My dream is to be a zoo keeper.","circle":true},
  {"no":1187,"word":"Kenya","star":false,"pos":"名","meaning":"ケニア","example":"There are many national parks in Kenya.","circle":true},
  {"no":1188,"word":"ketchup","star":false,"pos":"名","meaning":"ケチャップ","example":"I like hamburgers with a lot of ketchup in them.","circle":true},
  {"no":1189,"word":"kettle","star":false,"pos":"名","meaning":"やかん","example":"Put the kettle on the fire.","circle":true},
  {"no":1190,"word":"key","star":false,"pos":"名","meaning":"かぎ、キー","example":"This is the wrong key for this door.","circle":false},
  {"no":1191,"word":"keyword","star":false,"pos":"名","meaning":"キーワード","example":"Write down some keywords in your notebook.","circle":true},
  {"no":1192,"word":"kick","star":true,"pos":"動","meaning":"蹴る","example":"Soccer players pass the ball by kicking it.","circle":false},
  {"no":1193,"word":"kid","star":false,"pos":"名","meaning":"子ども","example":"I love kids.","circle":false},
  {"no":1194,"word":"kill","star":false,"pos":"動","meaning":"殺す","example":"The tsunami killed many people in Tohoku.","circle":false},
  {"no":1195,"word":"kilogram","star":false,"pos":"名","meaning":"キログラム","example":"Our dog has got big.  It's now about ten kilograms.","circle":false},
  {"no":1196,"word":"kilometer","star":false,"pos":"名","meaning":"キロメートル","example":"A: How far is the park?  B: About five kilometers.","circle":false},
  {"no":1197,"word":"kind","star":true,"pos":"名・形","meaning":"①（形）親切な　　　※That's kind of you.　親切にどうもありがとう\n②（名）種類　　　　※～ kind(s) of  …  ～種類の…","example":"①She is very kind to me.\n②Many kinds of animals and plants live there.","circle":false},
  {"no":1198,"word":"kindergarten","star":false,"pos":"名","meaning":"幼稚園","example":"We have been friends since we were in kindergarten.","circle":true},
  {"no":1199,"word":"kindly","star":false,"pos":"副","meaning":"親切に","example":"The man kindly told us the way to the station.","circle":false},
  {"no":1200,"word":"kindness","star":false,"pos":"名","meaning":"親切、思いやり、優しさ、親切な行為","example":"You should always show kindness to others.","circle":true}
];
