const WORDS11 = [
  {"no":1001,"word":"happy","star":true,"pos":"形","meaning":"幸せな、うれしい","example":"We were tired, but very happy.","circle":false},
  {"no":1002,"word":"hard","star":true,"pos":"形・副","meaning":"①（形）難しい、困難な\n②（形）かたい\n③（副）いっしょうけんめいに、熱心に","example":"①It is hard for me to understand your idea.\n②Ice is too hard to break with your hand.\n③My father works very hard.","circle":false},
  {"no":1003,"word":"harm","star":false,"pos":"動","meaning":"害を与える","example":"Having too much salt will harm your health.","circle":true},
  {"no":1004,"word":"harmony","star":false,"pos":"名","meaning":"調和、ハーモニー","example":"In the chorus, the harmony of their voices was beautiful.","circle":true},
  {"no":1005,"word":"harvest","star":false,"pos":"名","meaning":"収穫","example":"There was a large harvest of apples last year.","circle":false},
  {"no":1006,"word":"has","star":false,"pos":"動・助","meaning":"主語が３人称単数形のときのhaveの現在形\n※has to ～　～しなければならない　　　【活用】 has - had - had","example":"She has two sisters.","circle":false},
  {"no":1007,"word":"hat","star":true,"pos":"名","meaning":"（ふちのある）帽子","example":"He always wears that big hat.","circle":false},
  {"no":1008,"word":"hate","star":false,"pos":"動","meaning":"～するのが嫌いだ、～したくはない","example":"I hate to lose games.","circle":false},
  {"no":1009,"word":"have","star":true,"pos":"動・助","meaning":"①（動）持っている、所有している　\n②（動）食べる、飲む\n※have to ～　～しなければならない\ndon't(doesn't) have to ～ ～しなくてよい\n【活用】 have - had - had\n〔have+過去分詞で〕\n③（助）（今まで）～ずっとしている\n④（助）（今までに）～したことがある　\n⑤（助）～したところである、もう～した","example":"①I don't have a bike. \n②I have breakfast everyday.\n③I have lived in Sanda for 15 years.\n④I have been to China.\n⑤I have just finished my homework.","circle":false},
  {"no":1010,"word":"Hawaii","star":false,"pos":"名","meaning":"ハワイ","example":"She is going to visit Hawaii next summer.","circle":false},
  {"no":1011,"word":"he","star":true,"pos":"代","meaning":"彼は、彼が","example":"He is a dentist.","circle":false},
  {"no":1012,"word":"head","star":true,"pos":"名","meaning":"頭（首から上の部分）","example":"This cap is too small for my head.","circle":false},
  {"no":1013,"word":"headache","star":false,"pos":"名","meaning":"頭痛","example":"I have a headache.","circle":false},
  {"no":1014,"word":"headphone","star":false,"pos":"名","meaning":"ヘッドホン","example":"I didn't notice him because I was wearing headphones.","circle":true},
  {"no":1015,"word":"health","star":false,"pos":"名","meaning":"健康、健康状態    ※be in good health  健康である","example":"Health is the most important thing to me.","circle":false},
  {"no":1016,"word":"healthy","star":false,"pos":"形","meaning":"健康によい","example":"Many people say that Japanese food is healthy.","circle":false},
  {"no":1017,"word":"hear","star":false,"pos":"動","meaning":"聞こえる、聞く    　※hear of ～ ～のことを聞く　\n【活用】 hear - heard - heard","example":"I'm glad to hear that.","circle":false},
  {"no":1018,"word":"heart","star":true,"pos":"名","meaning":"心、気持ち、心臓","example":"I want to thank you from the bottom of my heart.","circle":false},
  {"no":1019,"word":"heat","star":false,"pos":"動・名","meaning":"熱（する）","example":"Let's wait for a while until the heat goes down.","circle":false},
  {"no":1020,"word":"heater","star":false,"pos":"名","meaning":"暖房器具","example":"This heater uses electricity.","circle":false},
  {"no":1021,"word":"heaven","star":false,"pos":"名","meaning":"天国","example":"People in Kobe want to show the lights to people in heaven.","circle":false},
  {"no":1022,"word":"heavy","star":false,"pos":"形","meaning":"重い","example":"My bag is as heavy as yours.","circle":false},
  {"no":1023,"word":"hello","star":true,"pos":"間","meaning":"やあ、こんにちは","example":"Hello.  This is Habatan.","circle":false},
  {"no":1024,"word":"helmet","star":false,"pos":"名","meaning":"ヘルメット","example":"You should wear a helmet when you ride a bike.","circle":true},
  {"no":1025,"word":"help","star":true,"pos":"動・名","meaning":"（動）手伝う、助ける　　　※help ～ with … ～が…するのを手伝う\nhelp yourself to ～　　～を自分で取って食べる（飲む）\n（名）手伝い、手助け","example":"We should always help people.","circle":false},
  {"no":1026,"word":"helpful","star":false,"pos":"形","meaning":"役に立つ、助けになる","example":"My friends are always helpful to me.","circle":false},
  {"no":1027,"word":"her","star":false,"pos":"代","meaning":"彼女の、彼女を","example":"Why do you like her?","circle":false},
  {"no":1028,"word":"here","star":true,"pos":"副・名","meaning":"ここ（に、で、へ）　※Here is (are) ～.　ここに～があります\nHere you are. はい、どうぞ\nFor here or to go?  ここで食べますか、それともお持ち帰りですか","example":"Let's play soccer here.","circle":false},
  {"no":1029,"word":"heritage","star":false,"pos":"名","meaning":"（文化的な）遺産","example":"This building is a heritage from the past.","circle":true},
  {"no":1030,"word":"hero","star":true,"pos":"名","meaning":"ヒーロー、英雄","example":"He became a hero when he won the Olympics.","circle":false},
  {"no":1031,"word":"hers","star":false,"pos":"代","meaning":"彼女のもの","example":"This book is hers.","circle":false},
  {"no":1032,"word":"herself","star":false,"pos":"代","meaning":"彼女自身を（に）      ※by herself　彼女自身で","example":"She decided by herself.","circle":false},
  {"no":1033,"word":"hey","star":false,"pos":"間","meaning":"ねえ、おや、やあ","example":"Hey, what's up?","circle":false},
  {"no":1034,"word":"hi","star":true,"pos":"間","meaning":"こんにちは、やあ《helloよりもくだけた言い方》","example":"Hi, David.  I'm Yuka.","circle":false},
  {"no":1035,"word":"hide","star":false,"pos":"動","meaning":"隠す、隠れる      【活用】 hide - hid - hidden","example":"I tried to hide from my brother for fun.","circle":true},
  {"no":1036,"word":"high","star":false,"pos":"形","meaning":"（高さ、値段、程度などが）高い","example":"Mt. Fuji is the highest mountain in Japan.","circle":false},
  {"no":1037,"word":"high school","star":false,"pos":"名","meaning":"高校","example":"I'm a high school student from Hyogo.","circle":false},
  {"no":1038,"word":"hike","star":false,"pos":"動・名","meaning":"ハイキング（をする）","example":"My grandmother likes to hike in the mountains.","circle":true},
  {"no":1039,"word":"hiking","star":true,"pos":"名","meaning":"ハイキング","example":"I enjoyed hiking with my family last week.","circle":false},
  {"no":1040,"word":"hill","star":false,"pos":"名","meaning":"丘","example":"He is standing on top of the hill.","circle":false},
  {"no":1041,"word":"him","star":false,"pos":"代","meaning":"彼を、彼に","example":"Will you give him a message, please?","circle":false},
  {"no":1042,"word":"himself","star":false,"pos":"代","meaning":"彼自身を（に）　　　　※ by himself  彼自身で","example":"He is traveling by himself.","circle":false},
  {"no":1043,"word":"hint","star":false,"pos":"名","meaning":"ヒント、有益な助言、てがかり","example":"This question is difficult.  Can you give me a hint?","circle":true},
  {"no":1044,"word":"hip-hop","star":false,"pos":"名","meaning":"ヒップホップ","example":"My Australian friend likes Japanese hip-hop music.","circle":true},
  {"no":1045,"word":"his","star":false,"pos":"代","meaning":"彼の、彼のもの","example":"This is his team.  They are strong.","circle":false},
  {"no":1046,"word":"historical","star":false,"pos":"形","meaning":"歴史の、歴史的な","example":"Takeda Castle is a popular historical site for tourists.","circle":true},
  {"no":1047,"word":"history","star":false,"pos":"名","meaning":"歴史","example":"What do you know about the history of the earth?","circle":false},
  {"no":1048,"word":"hit","star":false,"pos":"動","meaning":"打つ、当たる    【活用】 hit - hit - hit","example":"Soon the tsunami will hit the beach.","circle":false},
  {"no":1049,"word":"hobby","star":false,"pos":"名","meaning":"趣味、道楽","example":"What is your hobby?","circle":false},
  {"no":1050,"word":"hockey","star":false,"pos":"名","meaning":"ホッケー、アイスホッケー(ice hockey)","example":"Ice hockey is a popular sport in Canada.","circle":true},
  {"no":1051,"word":"hold","star":false,"pos":"動","meaning":"①持つ、握る、抱く  　※hold on （電話を）切らずに待つ\n②開く、開催する　　　　 【活用】 hold - held - held","example":"①I can't hold this box.  It's too heavy.\n②The festival is held in October.","circle":false},
  {"no":1052,"word":"hole","star":false,"pos":"名","meaning":"穴","example":"She fell into a big hole.","circle":false},
  {"no":1053,"word":"holiday","star":false,"pos":"名","meaning":"祝日、祭日、休日","example":"The day is a national holiday.","circle":false},
  {"no":1054,"word":"home","star":true,"pos":"副・名","meaning":"①（名）家、家庭　　　※at home 家で（に）\n②（副）うちへ（に）、故郷へ（に）     ※come(go) home 家に帰る","example":"①I want to stay at home tonight.\n②He's not home yet.","circle":false},
  {"no":1055,"word":"home economics","star":true,"pos":"名","meaning":"家庭科","example":"I study home economics on Friday.","circle":false},
  {"no":1056,"word":"homeroom","star":false,"pos":"名","meaning":"ホームルーム","example":"There are usually forty students in a homeroom class.","circle":true},
  {"no":1057,"word":"homesick","star":false,"pos":"形","meaning":"家を恋しがる、故郷を慕う、ホームシックの","example":"I was homesick because I could not communicate well.","circle":false},
  {"no":1058,"word":"homestay","star":false,"pos":"名","meaning":"ホームステイ、家庭滞在      ※do homestay 　ホームステイする","example":"I really like doing homestays.","circle":false},
  {"no":1059,"word":"hometown","star":false,"pos":"名","meaning":"生まれ育った町（市）","example":"Himeji is my hometown.","circle":false},
  {"no":1060,"word":"homework","star":true,"pos":"名","meaning":"宿題　　　　※do one's homework  宿題をする","example":"I have to do my homework.","circle":false},
  {"no":1061,"word":"honest","star":false,"pos":"形","meaning":"正直な","example":"It's important to be honest.","circle":false},
  {"no":1062,"word":"honesty","star":false,"pos":"名","meaning":"正直、誠実さ","example":"I respect your honesty.","circle":true},
  {"no":1063,"word":"honey","star":false,"pos":"名","meaning":"はちみつ","example":"Some people put honey on bread.","circle":false},
  {"no":1064,"word":"Hong Kong","star":false,"pos":"名","meaning":"香港","example":"Hong Kong is small, but it has a large population.","circle":true},
  {"no":1065,"word":"hope","star":false,"pos":"動・名","meaning":"希望（する）、望む","example":"I hope you'll enjoy the party.","circle":false},
  {"no":1066,"word":"hopeless","star":false,"pos":"形","meaning":"絶望した","example":"He felt hopeless about his job.","circle":false},
  {"no":1067,"word":"horizon","star":false,"pos":"名","meaning":"地平線","example":"The sun is just rising over the horizon.","circle":true},
  {"no":1068,"word":"horror","star":false,"pos":"名","meaning":"恐怖、恐ろしさ","example":"I don't like horror movies because they are scary.","circle":true},
  {"no":1069,"word":"horse","star":true,"pos":"名","meaning":"ウマ","example":"Horses have worked for people in many ways.","circle":false},
  {"no":1070,"word":"hospital","star":true,"pos":"名","meaning":"病院","example":"My mother works at this hospital.","circle":false},
  {"no":1071,"word":"host","star":false,"pos":"名","meaning":"主催者、（客をもてなす）主人","example":"You can learn about local food from your host student.","circle":false},
  {"no":1072,"word":"host family","star":false,"pos":"名","meaning":"ホストファミリー","example":"I will not forget my host family.","circle":false},
  {"no":1073,"word":"hot","star":true,"pos":"形","meaning":"暑い、熱い","example":"It's hot today.","circle":false},
  {"no":1074,"word":"hot spring","star":false,"pos":"名","meaning":"温泉","example":"Arima onsen is the oldest hot spring in Japan.","circle":false},
  {"no":1075,"word":"hotel","star":false,"pos":"名","meaning":"ホテル","example":"I’m not going to stay at a hotel.","circle":false},
  {"no":1076,"word":"hour","star":false,"pos":"名","meaning":"１時間、６０分","example":"Rest here for an hour.","circle":false},
  {"no":1077,"word":"house","star":true,"pos":"名","meaning":"家、住宅","example":"Today I went to Kumi's house.","circle":false},
  {"no":1078,"word":"housework","star":false,"pos":"名","meaning":"家事","example":"My father does some housework every day.","circle":false},
  {"no":1079,"word":"how","star":true,"pos":"副","meaning":"①（程度）どれぐらい\n②（健康・天候・状態）どんな具合で、いかがで\n③（方法・手段）どうやって、どんな方法で\n④（感嘆）なんと、どんなに\n※How about ～?  ～はどうですか　How far ～? （距離が）どれくらい遠いですか  How long ～? （期間が）どれくらい～ですか\nHow much ～? （金額が）どれくらい～ですか  How many ～? （数が）どれくらい～ですか  How often ～? （頻度が）どれくらい～ですか \nHow old ～?  何歳ですか  how to ～　～の仕方","example":"①How far is the park from here?\n②How are you?\n③How can we go to Hanshin Koshien Stadium? \n④A: I bought this bag.  B: How nice!","circle":false},
  {"no":1080,"word":"however","star":false,"pos":"接・副","meaning":"しかしながら、だが","example":"He agreed with my plan.  However, he changed his mind.","circle":false},
  {"no":1081,"word":"hug","star":false,"pos":"動・名","meaning":"（動）抱きしめる  （名）抱擁、ハグ","example":"My mother gave me a hug when I got home.","circle":true},
  {"no":1082,"word":"huge","star":false,"pos":"形","meaning":"巨大な","example":"Meals in America are huge!","circle":true},
  {"no":1083,"word":"human","star":false,"pos":"名・形","meaning":"人間（の）","example":"Humans use languages to communicate.","circle":false},
  {"no":1084,"word":"human being","star":false,"pos":"名","meaning":"人間（全体）、人類","example":"Human beings have lived on the earth for a long time.","circle":true},
  {"no":1085,"word":"humid","star":false,"pos":"形","meaning":"湿気の多い、じめじめした","example":"In Japan, it is very humid in June.","circle":true},
  {"no":1086,"word":"humor","star":false,"pos":"名","meaning":"おかしさ、ユーモア","example":"I want to share Japanese humor with people all over the world.","circle":false},
  {"no":1087,"word":"hundred","star":true,"pos":"名・形","meaning":"１００（の）　　　※hundreds of ～ 何百という～","example":"I got one hundred score on the test.","circle":false},
  {"no":1088,"word":"hungry","star":true,"pos":"形","meaning":"空腹の、飢えた","example":"I'm hungry.  Let's eat curry and rice at that shop.","circle":false},
  {"no":1089,"word":"hunt","star":false,"pos":"動","meaning":"捜す、狩る、狩りをする","example":"People kept dogs for hunting.","circle":true},
  {"no":1090,"word":"hunting","star":false,"pos":"名","meaning":"狩り","example":"Hunting was very important for our life a long time ago.","circle":false},
  {"no":1091,"word":"hurry","star":false,"pos":"動","meaning":"急ぐ、急いで行く","example":"We hurried to the station because it started to rain.","circle":false},
  {"no":1092,"word":"hurt","star":false,"pos":"動","meaning":"傷つける　【活用】 hurt - hurt - hurt","example":"Many people were hurt by that accident.","circle":false},
  {"no":1093,"word":"husband","star":false,"pos":"名","meaning":"夫","example":"My husband is at work now.","circle":false},
  {"no":1094,"word":"I","star":true,"pos":"代","meaning":"私は、私が（文の主語に使う）","example":"I like English very much.","circle":false},
  {"no":1095,"word":"ice","star":false,"pos":"名","meaning":"氷","example":"I put some ice into my glass.","circle":false},
  {"no":1096,"word":"ice cream","star":true,"pos":"名","meaning":"アイスクリーム","example":"The child ate two ice creams.","circle":false},
  {"no":1097,"word":"idea","star":false,"pos":"名","meaning":"考え、アイデア","example":"I have an idea.","circle":false},
  {"no":1098,"word":"ideal","star":false,"pos":"形","meaning":"理想的な","example":"What is your ideal lifestyle?","circle":true},
  {"no":1099,"word":"if","star":false,"pos":"接","meaning":"もし（～する）ならば","example":"If it rains, we'll play table tennis.","circle":false},
  {"no":1100,"word":"ill","star":false,"pos":"形","meaning":"病気の","example":"When she was a baby, she became very ill.","circle":false}
];
