const WORDS20 = [
  {"no":1901,"word":"serious","star":false,"pos":"形","meaning":"重大な、（病状などが）重い","example":"Global warming is a serious problem.","circle":false},
  {"no":1902,"word":"serve","star":false,"pos":"動","meaning":"（食事・飲み物）を出す","example":"Dinner will be served in this room.","circle":false},
  {"no":1903,"word":"service","star":false,"pos":"名","meaning":"サービス、公共事業","example":"The service at this restaurant is wonderful.","circle":true},
  {"no":1904,"word":"sesame","star":false,"pos":"名","meaning":"ゴマ","example":"We can make oil from sesame seeds.","circle":true},
  {"no":1905,"word":"set","star":false,"pos":"動・名","meaning":"①（名）一式、（テニスなどの）セット\n②（動）～を置く、設置する    【活用】 set - set - set","example":"①I bought a set of furniture.\n②I set the dishes on the table.","circle":false},
  {"no":1906,"word":"seven","star":true,"pos":"名・形","meaning":"７(の)","example":"It is seven o'clock.","circle":false},
  {"no":1907,"word":"seventeen","star":true,"pos":"名・形","meaning":"１７(の)","example":"When he came to Japan, he was only seventeen.","circle":false},
  {"no":1908,"word":"seventeenth","star":false,"pos":"名・形","meaning":"１７番目（の）","example":"The room is on the seventeenth floor.","circle":false},
  {"no":1909,"word":"seventh","star":false,"pos":"名・形","meaning":"７番目(の)","example":"I am in the seventh grade.","circle":false},
  {"no":1910,"word":"seventy","star":true,"pos":"名・形","meaning":"７０(の)","example":"My grandmother is seventy years old.","circle":false},
  {"no":1911,"word":"several","star":false,"pos":"形","meaning":"いくつかの、いく人かの","example":"There are several sushi restaurants in this town.","circle":false},
  {"no":1912,"word":"shade","star":false,"pos":"名","meaning":"ブラインド","example":"The man closed the shade on the train.","circle":true},
  {"no":1913,"word":"shadow","star":false,"pos":"名","meaning":"影","example":"The tall tree's shadow was very long.","circle":true},
  {"no":1914,"word":"shake","star":false,"pos":"動","meaning":"振る、ゆさぶる 　 ※shake hands　握手する\n【活用】 shake - shook - shaken","example":"We usually shake hands when we meet.","circle":false},
  {"no":1915,"word":"shall","star":false,"pos":"助","meaning":"（私（たち）は）～するでしょう 　※Shall I (we) ～?　～しましょうか","example":"Shall I take your bags?","circle":false},
  {"no":1916,"word":"shampoo","star":false,"pos":"名","meaning":"シャンプー","example":"I like this shampoo because it smells good.","circle":true},
  {"no":1917,"word":"shape","star":true,"pos":"名","meaning":"形、姿","example":"I like the shape, but I don't like the color.","circle":false},
  {"no":1918,"word":"share","star":false,"pos":"動","meaning":"いっしょに使う、共有する","example":"Please share your ideas with your partner.","circle":false},
  {"no":1919,"word":"sharp","star":false,"pos":"形・副","meaning":"（形）（刃物などが）鋭い、よく切れる　（副）ちょうど","example":"Be careful.  The knife is very sharp.","circle":true},
  {"no":1920,"word":"shaved ice","star":true,"pos":"名","meaning":"かき氷","example":"At summer festivals, I often eat shaved ice.","circle":true},
  {"no":1921,"word":"she","star":true,"pos":"代","meaning":"彼女は、彼女が","example":"She was so hungry.","circle":false},
  {"no":1922,"word":"sheep","star":true,"pos":"名","meaning":"ヒツジ（複数形も sheep）","example":"There are many sheep in New Zealand.","circle":true},
  {"no":1923,"word":"sheet","star":false,"pos":"名","meaning":"用紙","example":"May I have a sheet of paper?","circle":true},
  {"no":1924,"word":"shelf","star":false,"pos":"名","meaning":"棚　　【複数】shelves","example":"Please put the book back to the shelf after reading it.","circle":true},
  {"no":1925,"word":"shelter","star":false,"pos":"名","meaning":"避難所、（雨、危険、攻撃からの）避難、保護","example":"Our school becomes a shelter in an emergency.","circle":true},
  {"no":1926,"word":"shine","star":false,"pos":"動","meaning":"光る、輝く","example":"The moon was shining in the night sky.","circle":false},
  {"no":1927,"word":"ship","star":true,"pos":"名","meaning":"船","example":"Large ships can pass under the Akashi Kaikyo Bridge.","circle":false},
  {"no":1928,"word":"shirt","star":true,"pos":"名","meaning":"ワイシャツ、シャツ","example":"I bought this shirt in Hawaii.","circle":false},
  {"no":1929,"word":"shock","star":false,"pos":"動・名","meaning":"（動）衝撃を与える　　　（名）（精神的な）ショック","example":"The news shocked people.","circle":false},
  {"no":1930,"word":"shocked","star":false,"pos":"形","meaning":"ショックを受けた","example":"I was shocked when I heard the news.","circle":true},
  {"no":1931,"word":"shocking","star":false,"pos":"形","meaning":"衝撃的な、ぞっとする","example":"The news was shocking to me.","circle":true},
  {"no":1932,"word":"shoe","star":false,"pos":"名","meaning":"くつ","example":"Please take off your shoes here.","circle":false},
  {"no":1933,"word":"shoot","star":false,"pos":"動","meaning":"撃つ、射る、シュートする    【活用】 shoot - shot - shot","example":"He tried to shoot the bird, but it flew away.","circle":true},
  {"no":1934,"word":"shop","star":true,"pos":"名","meaning":"小売店、店","example":"Let's buy something to drink at that shop.","circle":false},
  {"no":1935,"word":"shopping","star":true,"pos":"名","meaning":"買い物　　※go shopping     買い物に行く","example":"I'll go shopping with my friends.","circle":false},
  {"no":1936,"word":"shopping mall","star":false,"pos":"名","meaning":"ショッピングモール","example":"I go to the shopping mall every weekend.","circle":true},
  {"no":1937,"word":"short","star":true,"pos":"形","meaning":"短い、背が低い","example":"He is shorter than I.","circle":false},
  {"no":1938,"word":"should","star":false,"pos":"助","meaning":"～すべきである、～したほうがいい","example":"What should I do?","circle":false},
  {"no":1939,"word":"shoulder","star":true,"pos":"名","meaning":"肩","example":"I have a pain in my shoulder.","circle":false},
  {"no":1940,"word":"shout","star":false,"pos":"動","meaning":"叫ぶ、大声で言う","example":"People shouted the name of the player.","circle":false},
  {"no":1941,"word":"show","star":false,"pos":"動・名","meaning":"①（動）見せる、示す   【活用】 show - showed - shown\n②（名）（演芸などの）ショー、劇","example":"①He showed me his family's photo.\n②The Kobe fireworks show was wonderful.","circle":false},
  {"no":1942,"word":"shower","star":false,"pos":"名","meaning":"シャワー    ※take a shower  シャワーを浴びる","example":"You should take a shower.","circle":false},
  {"no":1943,"word":"shrine","star":true,"pos":"名","meaning":"神社、神宮、聖堂","example":"On New Year's Eve, we visited a shrine.","circle":false},
  {"no":1944,"word":"shut","star":false,"pos":"動","meaning":"閉める　※shut up ～ ～を閉鎖する　【活用】 shut- shut - shut","example":"She shut her book and stood up.","circle":false},
  {"no":1945,"word":"shy","star":false,"pos":"形","meaning":"恥ずかしがり屋の、内気な","example":"He is very shy.","circle":false},
  {"no":1946,"word":"sick","star":false,"pos":"形","meaning":"病気の、病気で","example":"I am sick.","circle":false},
  {"no":1947,"word":"side","star":false,"pos":"名","meaning":"横、わき、側面","example":"Please stand on the right side.","circle":false},
  {"no":1948,"word":"sightseeing","star":false,"pos":"名","meaning":"観光","example":"Many foreigners visit Kobe for sightseeing.","circle":false},
  {"no":1949,"word":"sign","star":false,"pos":"名","meaning":"標識、看板","example":"You can find many signs written in English in Kinosaki.","circle":false},
  {"no":1950,"word":"sign language","star":false,"pos":"名","meaning":"手話","example":"People who can't hear use sign language to communicate.","circle":true},
  {"no":1951,"word":"silence","star":false,"pos":"名","meaning":"静けさ、沈黙","example":"We had the ceremony in silence.","circle":true},
  {"no":1952,"word":"silent","star":false,"pos":"形","meaning":"静かな、沈黙の","example":"You should be silent in libraries.","circle":false},
  {"no":1953,"word":"silly","star":false,"pos":"形","meaning":"ばかばかしい、ばかな","example":"You should not ask a silly question like that.","circle":true},
  {"no":1954,"word":"silver","star":false,"pos":"名・形","meaning":"銀（の）","example":"He won a silver medal at the Olympics.","circle":true},
  {"no":1955,"word":"similar","star":false,"pos":"形","meaning":"似た　　　　※be similar to ～　～に似ている","example":"Your opinion is similar to mine.","circle":false},
  {"no":1956,"word":"simple","star":false,"pos":"形","meaning":"簡単な、わかりやすい","example":"The stories are simple and clear.","circle":false},
  {"no":1957,"word":"since","star":false,"pos":"前・接","meaning":"～から（ずっと）、～以来（ずっと）","example":"I have played the guitar since I was eight.","circle":false},
  {"no":1958,"word":"sincerely","star":false,"pos":"副","meaning":"心から、（手紙の結び文句として）敬具","example":"I sincerely thank you for your kindness.","circle":true},
  {"no":1959,"word":"sing","star":true,"pos":"動","meaning":"歌う　　【活用】 sing - sang - sung","example":"She began to sing again.","circle":false},
  {"no":1960,"word":"Singapore","star":false,"pos":"名","meaning":"シンガポール","example":"Singapore is a very small country.","circle":false},
  {"no":1961,"word":"singer","star":true,"pos":"名","meaning":"歌う人、歌手","example":"She is a famous singer in Japan.","circle":false},
  {"no":1962,"word":"single","star":false,"pos":"形","meaning":"たった１つの","example":"Her English was good.  There wasn't a single mistake.","circle":false},
  {"no":1963,"word":"sink","star":false,"pos":"動・名","meaning":"①（動）（水中に）沈む　     【活用】 sink - sank - sunk\n②（名）洗面台、（台所などの）流し","example":"①Luckily, our boat did not sink.\n②Please put your dishes in the sink.","circle":true},
  {"no":1964,"word":"sir","star":false,"pos":"名","meaning":"（男性に対する改まった呼びかけのことば）","example":"Can I help you, sir?","circle":false},
  {"no":1965,"word":"sister","star":true,"pos":"名","meaning":"姉妹、姉、妹","example":"My older sister's name is Miki.","circle":false},
  {"no":1966,"word":"sit","star":true,"pos":"動","meaning":"座る、座っている　　※sit down 座る　　【活用】 sit - sat - sat","example":"Please sit down.","circle":false},
  {"no":1967,"word":"site","star":false,"pos":"名","meaning":"場所、遺跡","example":"This is the site for the new school.","circle":false},
  {"no":1968,"word":"situation","star":false,"pos":"名","meaning":"状況、状態","example":"I can understand your situation.","circle":false},
  {"no":1969,"word":"six","star":true,"pos":"名・形","meaning":"６（の）","example":"We have six classes each day.","circle":false},
  {"no":1970,"word":"sixteen","star":true,"pos":"名・形","meaning":"１６（の）","example":"When I am sixteen years old, I will go to Australia.","circle":false},
  {"no":1971,"word":"sixteenth","star":false,"pos":"名・形","meaning":"１６番目（の）","example":"She lives on the sixteenth floor.","circle":false},
  {"no":1972,"word":"sixth","star":false,"pos":"名・形","meaning":"６番目（の）","example":"My sister is in the sixth grade.","circle":false},
  {"no":1973,"word":"sixty","star":true,"pos":"名・形","meaning":"６０（の）","example":"She is sixty years old.","circle":false},
  {"no":1974,"word":"size","star":false,"pos":"名","meaning":"大きさ、サイズ","example":"What's your size?","circle":false},
  {"no":1975,"word":"skate","star":true,"pos":"動","meaning":"スケートですべる、スケートをする","example":"I like to skate.","circle":false},
  {"no":1976,"word":"ski","star":true,"pos":"動","meaning":"スキーをする","example":"I go skiing every weekend in winter.","circle":false},
  {"no":1977,"word":"skiing","star":false,"pos":"名","meaning":"スキー","example":"Skiing is one of the most popular winter sports.","circle":false},
  {"no":1978,"word":"skill","star":false,"pos":"名","meaning":"技術、技能","example":"Try to improve your skills.","circle":false},
  {"no":1979,"word":"skin","star":false,"pos":"名","meaning":"皮膚、肌","example":"I have dry skin.","circle":false},
  {"no":1980,"word":"skirt","star":false,"pos":"名","meaning":"スカート","example":"You are wearing a pretty skirt.","circle":true},
  {"no":1981,"word":"sky","star":false,"pos":"名","meaning":"空","example":"A bird is flying in the sky.","circle":false},
  {"no":1982,"word":"sleep","star":false,"pos":"動・名","meaning":"（動）眠る、睡眠をとる　　【活用】 sleep - slept - slept　\n（名）眠り、睡眠","example":"Did you sleep well last night?","circle":false},
  {"no":1983,"word":"sleepy","star":true,"pos":"形","meaning":"眠い、眠そうな","example":"I’m sleepy.","circle":false},
  {"no":1984,"word":"sleeve","star":false,"pos":"名","meaning":"そで","example":"The boy wears short sleeves even in winter.","circle":true},
  {"no":1985,"word":"slipper","star":false,"pos":"名","meaning":"スリッパ、部屋履き","example":"In Japan, students wear slippers in school.","circle":true},
  {"no":1986,"word":"slow","star":true,"pos":"形","meaning":"遅い、ゆっくりした","example":"Please drive at a slow speed around here.","circle":false},
  {"no":1987,"word":"slowly","star":false,"pos":"副","meaning":"ゆっくりと","example":"Please speak more slowly.","circle":false},
  {"no":1988,"word":"small","star":true,"pos":"形","meaning":"小さい","example":"My room is very small.","circle":false},
  {"no":1989,"word":"smart","star":false,"pos":"形","meaning":"利口な、かしこい","example":"Dogs are very smart.","circle":false},
  {"no":1990,"word":"smartphone","star":false,"pos":"名","meaning":"スマートフォン","example":"I often take photos with my smartphone.","circle":true},
  {"no":1991,"word":"smell","star":false,"pos":"動・名","meaning":"におい（がする）","example":"This flower smells nice.","circle":false},
  {"no":1992,"word":"smile","star":false,"pos":"動・名","meaning":"（動）ほほえむ、にっこり笑う　（名）ほほえみ、笑顔","example":"We smile when we are happy.","circle":false},
  {"no":1993,"word":"smoke","star":false,"pos":"名","meaning":"煙","example":"There is no smoke without fire.","circle":false},
  {"no":1994,"word":"snack","star":true,"pos":"名","meaning":"軽食、おやつ","example":"Don't eat snacks before dinner.","circle":false},
  {"no":1995,"word":"snake","star":true,"pos":"名","meaning":"ヘビ","example":"I don't like snakes.","circle":false},
  {"no":1996,"word":"sneaker","star":false,"pos":"名","meaning":"スニーカー","example":"I'm looking for a nice pair of sneakers.","circle":false},
  {"no":1997,"word":"snow","star":false,"pos":"動・名","meaning":"雪（がふる）","example":"Last year we had a lot of snow in the Tajima area.","circle":false},
  {"no":1998,"word":"snowboarding","star":false,"pos":"名","meaning":"スノーボード","example":"Snowboarding is popular among young people.","circle":true},
  {"no":1999,"word":"snowman","star":false,"pos":"名","meaning":"雪だるま","example":"It's snowing.  Let's make a snowman outside.","circle":true},
  {"no":2000,"word":"snowy","star":true,"pos":"形","meaning":"雪の降る、雪の多い","example":"It will be snowy this evening.","circle":false}
];
