const WORDS22 = [
  {"no":2101,"word":"straw","star":false,"pos":"名","meaning":"（飲み物用の）ストロー","example":"May I have a straw for this drink?","circle":true},
  {"no":2102,"word":"strawberry","star":true,"pos":"名","meaning":"イチゴ","example":"Strawberries are my favorite fruit.","circle":true},
  {"no":2103,"word":"stream","star":false,"pos":"動・名","meaning":"（動）流す　（名）小川","example":"There is a stream near the mountain.","circle":true},
  {"no":2104,"word":"street","star":true,"pos":"名","meaning":"通り、道","example":"The post office is on the next street.","circle":false},
  {"no":2105,"word":"stress","star":false,"pos":"名","meaning":"（精神的）ストレス","example":"We should try to reduce stress.","circle":true},
  {"no":2106,"word":"stretch","star":false,"pos":"動","meaning":"（手足などを）伸ばす","example":"You should stretch your legs before running.","circle":true},
  {"no":2107,"word":"strict","star":false,"pos":"形","meaning":"厳しい、厳格な","example":"The rules are very strict in Singapore.","circle":true},
  {"no":2108,"word":"strong","star":true,"pos":"形","meaning":"強い","example":"He is stronger than his brother.","circle":false},
  {"no":2109,"word":"strongly","star":false,"pos":"副","meaning":"強く","example":"I am strongly against your idea.","circle":false},
  {"no":2110,"word":"student","star":false,"pos":"名","meaning":"生徒","example":"There are about 1,000 students in this school.","circle":false},
  {"no":2111,"word":"student council","star":false,"pos":"名","meaning":"生徒会","example":"I am a member of the student council.","circle":true},
  {"no":2112,"word":"study","star":true,"pos":"動・名","meaning":"勉強（する）、研究（する）","example":"I want to study abroad in the future.","circle":false},
  {"no":2113,"word":"stupid","star":false,"pos":"形","meaning":"ばかな、愚かな","example":"I am sorry for making such a stupid mistake.","circle":true},
  {"no":2114,"word":"style","star":false,"pos":"名","meaning":"スタイル、型","example":"There are different styles of dance.","circle":false},
  {"no":2115,"word":"stylist","star":false,"pos":"名","meaning":"スタイリスト、美容師","example":"That stylist has excellent skills.","circle":true},
  {"no":2116,"word":"subject","star":true,"pos":"名","meaning":"教科、科目、（メールなどの）話題","example":"English is my favorite subject.","circle":false},
  {"no":2117,"word":"subway","star":true,"pos":"名","meaning":"（アメリカの）地下鉄（イギリスでは、underground）","example":"I take the subway to go to school every day.","circle":false},
  {"no":2118,"word":"succeed","star":false,"pos":"動","meaning":"成功する","example":"I think you will succeed as an actor.","circle":true},
  {"no":2119,"word":"success","star":false,"pos":"名","meaning":"成功","example":"Working hard is the best way to success.","circle":false},
  {"no":2120,"word":"successful","star":false,"pos":"形","meaning":"成功した","example":"Ichiro is a successful baseball player in America.","circle":false},
  {"no":2121,"word":"such","star":false,"pos":"形","meaning":"このような、そのような    ※such as ～ 例えば～のような","example":"Thank you for such a wonderful present.","circle":false},
  {"no":2122,"word":"suddenly","star":false,"pos":"副","meaning":"急に、突然","example":"Suddenly, it started to rain.","circle":false},
  {"no":2123,"word":"suffer","star":false,"pos":"動","meaning":"苦しむ","example":"Many people suffered from the cold weather.","circle":false},
  {"no":2124,"word":"sugar","star":false,"pos":"名","meaning":"砂糖","example":"We need sugar and salt.","circle":false},
  {"no":2125,"word":"suggest","star":false,"pos":"動","meaning":"提案する","example":"They suggested that I should go alone.","circle":false},
  {"no":2126,"word":"suit","star":false,"pos":"名","meaning":"（ある目的のための）服、スーツ","example":"My father wears a business suit for his job.","circle":true},
  {"no":2127,"word":"suitcase","star":false,"pos":"名","meaning":"スーツケース","example":"This suitcase is too small to travel for a week.","circle":true},
  {"no":2128,"word":"summary","star":false,"pos":"名","meaning":"要約、まとめ","example":"Please write a summary of the story.","circle":true},
  {"no":2129,"word":"summer","star":true,"pos":"名","meaning":"夏","example":"I want to try something new this summer.","circle":false},
  {"no":2130,"word":"sumo wrestler","star":false,"pos":"名","meaning":"力士","example":"There are a lot of sumo wrestlers from abroad.","circle":false},
  {"no":2131,"word":"sun","star":false,"pos":"名","meaning":"太陽","example":"The earth goes around the sun.","circle":false},
  {"no":2132,"word":"Sunday","star":true,"pos":"名","meaning":"日曜日","example":"On Sundays I cook lunch for my family.","circle":false},
  {"no":2133,"word":"sunflower","star":false,"pos":"名","meaning":"ひまわり","example":"In summer, you can see many sunflowers in the garden.","circle":false},
  {"no":2134,"word":"sunglasses","star":false,"pos":"名","meaning":"サングラス","example":"You should wear sunglasses to protect your eyes.","circle":true},
  {"no":2135,"word":"sunny","star":true,"pos":"形","meaning":"晴れた","example":"It is raining now, but it will be sunny in the afternoon.","circle":false},
  {"no":2136,"word":"sunrise","star":false,"pos":"名","meaning":"日の出、朝焼け","example":"On January 1st, I watched the sunrise with my family.","circle":true},
  {"no":2137,"word":"sunset","star":false,"pos":"名","meaning":"日の入り","example":"I like to watch beautiful sunsets.","circle":false},
  {"no":2138,"word":"sunshine","star":false,"pos":"名","meaning":"日光","example":"You need a hat because the sunshine is strong.","circle":true},
  {"no":2139,"word":"supermarket","star":true,"pos":"名","meaning":"スーパー（マーケット）","example":"A supermarket is near my house.","circle":false},
  {"no":2140,"word":"support","star":false,"pos":"動・名","meaning":"支持（する）、支援（する）","example":"Some dogs support blind people.","circle":false},
  {"no":2141,"word":"sure","star":false,"pos":"形・副","meaning":"①（副）もちろん\n②（形）確信して  ※I'm sure (that) ～  きっと～だと思う","example":"①A: Could you help me?  B: Sure.\n②I'm sure you can do it.","circle":false},
  {"no":2142,"word":"surf","star":true,"pos":"動","meaning":"波乗りする、（インターネット、テレビのチャンネルなどを）見て回る","example":"You can enjoy surfing at the beach.","circle":true},
  {"no":2143,"word":"surprise","star":false,"pos":"動・名","meaning":"（動）驚かす、びっくりさせる　　（名）驚くべきこと","example":"What a surprise!","circle":false},
  {"no":2144,"word":"surprised","star":false,"pos":"形","meaning":"驚いて  　※be surprised at ～　～に驚く","example":"I was surprised when I heard the news.","circle":false},
  {"no":2145,"word":"surprising","star":false,"pos":"形","meaning":"驚くべき、すばらしい","example":"That news is surprising.","circle":false},
  {"no":2146,"word":"surprisingly","star":false,"pos":"副","meaning":"驚いたことに、意外にも","example":"Surprisingly, my ALT likes natto.","circle":true},
  {"no":2147,"word":"surround","star":false,"pos":"動","meaning":"囲む、取り巻く","example":"Japan is surrounded by the sea.","circle":false},
  {"no":2148,"word":"survey","star":false,"pos":"名","meaning":"調査","example":"This is a survey about dream jobs for boys and girls.","circle":false},
  {"no":2149,"word":"survive","star":false,"pos":"動","meaning":"生き残る","example":"They survived two wars.","circle":false},
  {"no":2150,"word":"survivor","star":false,"pos":"名","meaning":"生存者","example":"I hope there are more survivors of the accident.","circle":true},
  {"no":2151,"word":"sweat","star":false,"pos":"動・名","meaning":"（動）汗をかく　（名）汗","example":"I sweat a lot during our kendo practice.","circle":true},
  {"no":2152,"word":"sweater","star":true,"pos":"名","meaning":"セーター","example":"I like this sweater very much.","circle":false},
  {"no":2153,"word":"sweet","star":true,"pos":"名・形","meaning":"①（名）甘いもの、お菓子\n②（形）甘い、（音・香りなどが）美しい、心地よい","example":"①Kobe is famous for Western sweets.\n②The cake is not too sweet.","circle":false},
  {"no":2154,"word":"sweet potato","star":false,"pos":"名","meaning":"サツマイモ","example":"We grew sweet potatoes at our elementary school.","circle":true},
  {"no":2155,"word":"swim","star":true,"pos":"動","meaning":"泳ぐ　　　　　　　　　【活用】 swim - swam - swum","example":"I always swim at Suma beach in summer.","circle":false},
  {"no":2156,"word":"swimmer","star":false,"pos":"名","meaning":"水泳選手","example":"He is the fastest swimmer in the world.","circle":true},
  {"no":2157,"word":"swimming","star":true,"pos":"名","meaning":"水泳、泳ぐこと","example":"Do you like swimming?","circle":false},
  {"no":2158,"word":"switch","star":false,"pos":"動・名","meaning":"（動）スイッチを入れる　（名）スイッチ","example":"The switch for the light is just behind you.","circle":true},
  {"no":2159,"word":"Sydney","star":false,"pos":"名","meaning":"シドニー","example":"I visited Sydney with my aunt.","circle":false},
  {"no":2160,"word":"symbol","star":false,"pos":"名","meaning":"シンボル（マーク）、しるし","example":"This bird is a symbol of Hyogo.","circle":false},
  {"no":2161,"word":"system","star":false,"pos":"名","meaning":"方式、体系的方法","example":"That system isn't used now.","circle":false},
  {"no":2162,"word":"table","star":true,"pos":"名","meaning":"テーブル","example":"Could you move this table with me?","circle":false},
  {"no":2163,"word":"table tennis","star":true,"pos":"名","meaning":"卓球","example":"She is a good table tennis player.","circle":false},
  {"no":2164,"word":"tablet","star":false,"pos":"名","meaning":"タブレット","example":"Every student will have a tablet in school.","circle":true},
  {"no":2165,"word":"tag","star":false,"pos":"名","meaning":"札　　※name tag  名札","example":"You should wear your name tag in school.","circle":true},
  {"no":2166,"word":"tail","star":false,"pos":"名","meaning":"しっぽ","example":"The dog was happy and moved his tail quickly.","circle":true},
  {"no":2167,"word":"Taiwan","star":false,"pos":"名","meaning":"台湾","example":"There are a lot of delicious foods in Taiwan.","circle":false},
  {"no":2168,"word":"take","star":true,"pos":"動","meaning":"①（手に）取る、持っていく、連れて行く　※take off ～　～を脱ぐ　\n②乗る　\n③（写真を）撮る\n④（時間が）かかる　\n⑤（～を）買う　　　※I'll take it. それをいただきます　\n【活用】take - took - taken","example":"①Please take an umbrella with you. \n②I will take a train. \n③We took a picture on the beach.\n④It will take ten minutes from here to the station.\n⑤I'll take this shirt.","circle":false},
  {"no":2169,"word":"tale","star":false,"pos":"名","meaning":"物語    ※fairy tale  おとぎ話","example":"Everyone knows this tale in Japan.","circle":true},
  {"no":2170,"word":"talent","star":false,"pos":"名","meaning":"才能","example":"He has a talent for drawing pictures.","circle":false},
  {"no":2171,"word":"talk","star":true,"pos":"動","meaning":"話す　　　　※talk to(with) ～  ～と話す","example":"A: May I talk to you now?  B: Sure.","circle":false},
  {"no":2172,"word":"tall","star":false,"pos":"形","meaning":"背が高い","example":"I am the tallest in my family.","circle":false},
  {"no":2173,"word":"tank","star":false,"pos":"名","meaning":"タンク、水槽","example":"The tank is full of water now.","circle":true},
  {"no":2174,"word":"tape","star":false,"pos":"名","meaning":"粘着テープ","example":"Use this tape to put the paper on the wall.","circle":true},
  {"no":2175,"word":"task","star":false,"pos":"名","meaning":"仕事、任務、課題","example":"Robots can help old people with many everyday tasks.","circle":false},
  {"no":2176,"word":"taste","star":false,"pos":"動・名","meaning":"①（動）～な味がする\n②（名）味、味覚","example":"①The cake tastes delicious.\n②This orange has a bitter taste.","circle":false},
  {"no":2177,"word":"tasty","star":false,"pos":"形","meaning":"おいしい、風味のきいた、味加減のよい","example":"The pizza at this restaurant is very tasty.","circle":true},
  {"no":2178,"word":"tax","star":false,"pos":"名","meaning":"税、税金","example":"Everyone needs to pay tax.","circle":true},
  {"no":2179,"word":"taxi","star":true,"pos":"名","meaning":"タクシー","example":"I took a taxi to the airport.","circle":false},
  {"no":2180,"word":"tea","star":true,"pos":"名","meaning":"茶、紅茶","example":"I like tea better than coffee.","circle":false},
  {"no":2181,"word":"tea ceremony","star":false,"pos":"名","meaning":"茶道","example":"This school has a special room for tea ceremonies.","circle":true},
  {"no":2182,"word":"teach","star":true,"pos":"動","meaning":"教える　　　　【活用】 teach - taught - taught","example":"Ms. Saito teaches us math.","circle":false},
  {"no":2183,"word":"teacher","star":true,"pos":"名","meaning":"先生、教師","example":"I want to be a teacher in the future.","circle":false},
  {"no":2184,"word":"team","star":true,"pos":"名","meaning":"チーム","example":"I will try hard for our baseball team.","circle":false},
  {"no":2185,"word":"teammate","star":false,"pos":"名","meaning":"チームメイト","example":"He is my teammate.","circle":false},
  {"no":2186,"word":"teamwork","star":false,"pos":"名","meaning":"チームワーク","example":"I think teamwork is important.","circle":false},
  {"no":2187,"word":"tear","star":false,"pos":"名","meaning":"涙","example":"I have never seen her tears.","circle":false},
  {"no":2188,"word":"technology","star":false,"pos":"名","meaning":"科学技術","example":"The new technology will change our lifestyle.","circle":false},
  {"no":2189,"word":"teenager","star":false,"pos":"名","meaning":"10代の少年・少女、ティーンエイジャー","example":"The band is popular among teenagers.","circle":true},
  {"no":2190,"word":"telephone","star":true,"pos":"名","meaning":"電話","example":"I talked with my grandmother on the telephone.","circle":true},
  {"no":2191,"word":"tell","star":false,"pos":"動","meaning":"言う､教える　　　　　【活用】 tell - told - told","example":"Please tell us about Hyogo.","circle":false},
  {"no":2192,"word":"temperature","star":false,"pos":"名","meaning":"温度、気温","example":"What is the temperature here?","circle":false},
  {"no":2193,"word":"temple","star":true,"pos":"名","meaning":"寺","example":"There are many temples in Kyoto.","circle":false},
  {"no":2194,"word":"ten","star":true,"pos":"名・形","meaning":"１０（の）","example":"I have ten pencils.","circle":false},
  {"no":2195,"word":"tennis","star":true,"pos":"名","meaning":"テニス","example":"Kei Nishikori is a famous tennis player.","circle":false},
  {"no":2196,"word":"tent","star":false,"pos":"名","meaning":"テント","example":"I am going to buy a tent for camping.","circle":true},
  {"no":2197,"word":"tenth","star":false,"pos":"名・形","meaning":"１０番目（の）","example":"The room is on the tenth floor.","circle":false},
  {"no":2198,"word":"term","star":false,"pos":"名","meaning":"学期","example":"Australian schools have four terms in a year.","circle":true},
  {"no":2199,"word":"terrible","star":false,"pos":"形","meaning":"恐ろしい、ひどい","example":"Everyone was shocked to hear the terrible news.","circle":false},
  {"no":2200,"word":"test","star":false,"pos":"名","meaning":"試験、テスト","example":"We will have a test tomorrow.","circle":false}
];
