const WORDS17 = [
  {"no":1601,"word":"Philippines","star":false,"pos":"名","meaning":"(the ～）フィリピン","example":"Our ALT is from the Philippines.","circle":true},
  {"no":1602,"word":"phone","star":false,"pos":"名","meaning":"電話（機）（telephoneを短くした形）","example":"My mother is talking on the phone.","circle":false},
  {"no":1603,"word":"phone call","star":false,"pos":"名","meaning":"電話（をかけること）","example":"I received a phone call from my homeroom teacher.","circle":false},
  {"no":1604,"word":"phone number","star":false,"pos":"名","meaning":"電話番号","example":"Do you know his phone number?","circle":false},
  {"no":1605,"word":"photo","star":false,"pos":"名","meaning":"写真（photographを短くした形）","example":"This is a photo of my family.","circle":false},
  {"no":1606,"word":"photograph","star":false,"pos":"動・名","meaning":"写真（を撮る）","example":"A photograph in the book caught his attention.","circle":false},
  {"no":1607,"word":"photographer","star":false,"pos":"名","meaning":"写真家、カメラマン","example":"My father is a good photographer.","circle":false},
  {"no":1608,"word":"phrase","star":false,"pos":"名","meaning":"言葉遣い、表現","example":"“Excuse me” is the phrase we use in this case.","circle":false},
  {"no":1609,"word":"physical","star":false,"pos":"形","meaning":"身体の","example":"PE means physical education.","circle":true},
  {"no":1610,"word":"pianist","star":false,"pos":"名","meaning":"ピアニスト","example":"He is a good pianist.","circle":false},
  {"no":1611,"word":"piano","star":true,"pos":"名","meaning":"ピアノ","example":"She plays the piano very well.","circle":false},
  {"no":1612,"word":"pick","star":false,"pos":"動","meaning":"取り上げる、拾い上げる　　※pick up　拾い上げる","example":"We picked up a lot of cans as volunteer work.","circle":false},
  {"no":1613,"word":"picnic","star":false,"pos":"名","meaning":"ピクニック、行楽","example":"I often eat onigiri on picnics.","circle":false},
  {"no":1614,"word":"picture","star":true,"pos":"名","meaning":"写真、絵　　※take a picture 写真を撮る","example":"This is a nice picture.","circle":false},
  {"no":1615,"word":"pie","star":true,"pos":"名","meaning":"パイ","example":"In America, apple pie is a popular dessert.","circle":true},
  {"no":1616,"word":"piece","star":false,"pos":"名","meaning":"断片、破片      ※a piece of ～　１枚（片、個の）～","example":"He collected pieces of wood.","circle":false},
  {"no":1617,"word":"pig","star":true,"pos":"名","meaning":"ブタ","example":"I saw some little pigs on the farm.","circle":true},
  {"no":1618,"word":"pillow","star":false,"pos":"名","meaning":"枕","example":"My pillow is soft and comfortable.","circle":true},
  {"no":1619,"word":"pilot","star":true,"pos":"名","meaning":"（飛行機の）操縦士、パイロット","example":"I want to be a pilot in the future.","circle":false},
  {"no":1620,"word":"pin","star":false,"pos":"名","meaning":"ピン、留め針","example":"Please use these pins to put the picture on the wall.","circle":true},
  {"no":1621,"word":"pineapple","star":true,"pos":"名","meaning":"パイナップル","example":"Most pineapples come from the Philippines.","circle":true},
  {"no":1622,"word":"pink","star":true,"pos":"名・形","meaning":"ピンク色（の）","example":"Pink is my favorite color.","circle":false},
  {"no":1623,"word":"pizza","star":true,"pos":"名","meaning":"ピザ","example":"Pizza is one of my favorite foods.","circle":false},
  {"no":1624,"word":"place","star":true,"pos":"名","meaning":"場所、所","example":"Takeda Castle is a good place to visit.","circle":false},
  {"no":1625,"word":"plan","star":false,"pos":"動・名","meaning":"（動）計画する、～するつもりである　　（名）計画、案、考え","example":"What's your plan for this weekend?","circle":false},
  {"no":1626,"word":"plane","star":false,"pos":"名","meaning":"飛行機","example":"It took fourteen hours by plane.","circle":false},
  {"no":1627,"word":"planet","star":false,"pos":"名","meaning":"惑星","example":"We have to think what we can do to save our planet.","circle":false},
  {"no":1628,"word":"plant","star":false,"pos":"動・名","meaning":"①（名）植物、草木\n②（動）～を植える","example":"①There are many kinds of plants in the forest.\n②We planted a cherry tree in our garden.","circle":false},
  {"no":1629,"word":"plastic","star":false,"pos":"名・形","meaning":"プラスチック（の)、ビニール（の）","example":"This chair is made of plastic.","circle":false},
  {"no":1630,"word":"plastic bag","star":false,"pos":"名","meaning":"ビニール袋","example":"Let's recycle our plastic bags!","circle":true},
  {"no":1631,"word":"plate","star":false,"pos":"名","meaning":"皿、取り皿","example":"He ate twenty plates of sushi at the sushi restaurant.","circle":false},
  {"no":1632,"word":"platform","star":false,"pos":"名","meaning":"プラットフォーム","example":"I waited for the train on the platform.","circle":true},
  {"no":1633,"word":"play","star":true,"pos":"動","meaning":"①（スポーツ・ゲームなどを）する　\n②（楽器を）演奏する　\n③遊ぶ　\n④（役を）演じる、果たす","example":"①Let's play tennis.\n②My teacher can play the guitar very well.\n③Children learn a lot from playing.\n④I played the part of a doctor in the drama.","circle":false},
  {"no":1634,"word":"player","star":true,"pos":"名","meaning":"（運動）選手、（楽器の）演奏者","example":"He is a very good baseball player.","circle":false},
  {"no":1635,"word":"playground","star":true,"pos":"名","meaning":"運動場","example":"At lunch time, many students play in the playground.","circle":true},
  {"no":1636,"word":"pleasant","star":false,"pos":"形","meaning":"楽しい、心地よい","example":"The weather in spring is very pleasant.","circle":true},
  {"no":1637,"word":"please","star":true,"pos":"副・間","meaning":"どうぞ、すみませんが","example":"Please come in.","circle":false},
  {"no":1638,"word":"pleased","star":false,"pos":"形","meaning":"喜んで","example":"I am pleased to meet you.","circle":true},
  {"no":1639,"word":"pleasure","star":false,"pos":"名","meaning":"楽しみ、喜び","example":"It is a pleasure to meet you.","circle":true},
  {"no":1640,"word":"p.m.","star":false,"pos":"副","meaning":"午後","example":"I will meet her at 2:00 p.m.","circle":false},
  {"no":1641,"word":"pocket","star":false,"pos":"名","meaning":"ポケット","example":"I put candies in my pocket.","circle":false},
  {"no":1642,"word":"poem","star":false,"pos":"名","meaning":"（一編の）詩","example":"The poem was written in English.","circle":false},
  {"no":1643,"word":"poet","star":false,"pos":"名","meaning":"詩人","example":"He is known as a great poet.","circle":true},
  {"no":1644,"word":"poetry","star":false,"pos":"名","meaning":"（集合的に）詩","example":"She started writing poetry at a young age.","circle":true},
  {"no":1645,"word":"point","star":false,"pos":"動・名","meaning":"①（名）点、大切な点\n②（動）指し示す","example":"①That is a good point.\n②The teacher pointed to a picture on the wall.","circle":false},
  {"no":1646,"word":"poison","star":false,"pos":"名","meaning":"毒","example":"This snake's poison is very dangerous.","circle":true},
  {"no":1647,"word":"pole","star":false,"pos":"名","meaning":"棒、さお","example":"A pole was used to rescue the boy from the river.","circle":true},
  {"no":1648,"word":"police","star":true,"pos":"名","meaning":"警察、警察官たち","example":"I will call the police.","circle":false},
  {"no":1649,"word":"police station","star":true,"pos":"名","meaning":"警察署","example":"The police station is next to the bank.","circle":false},
  {"no":1650,"word":"polite","star":false,"pos":"形","meaning":"ていねいな、礼儀正しい","example":"You should be polite to other people.","circle":false},
  {"no":1651,"word":"politician","star":false,"pos":"名","meaning":"政治家","example":"The politician is good at making speeches.","circle":true},
  {"no":1652,"word":"pollute","star":false,"pos":"動","meaning":"汚染する","example":"We must not pollute the environment.","circle":true},
  {"no":1653,"word":"pollution","star":false,"pos":"名","meaning":"汚染","example":"Air pollution is one of the problems.","circle":false},
  {"no":1654,"word":"pond","star":false,"pos":"名","meaning":"池","example":"There are many ponds between Akashi and Kakogawa.","circle":true},
  {"no":1655,"word":"pool","star":false,"pos":"名","meaning":"プール","example":"There is a big swimming pool at our school.","circle":false},
  {"no":1656,"word":"poor","star":false,"pos":"形","meaning":"貧しい、へたな","example":"There are many poor children in the world.","circle":false},
  {"no":1657,"word":"pop","star":false,"pos":"名・形","meaning":"（名）ポップス　（形）ポップスの、大衆向きの","example":"I like Japanese pop music.","circle":true},
  {"no":1658,"word":"popcorn","star":true,"pos":"名","meaning":"ポップコーン","example":"When I see a movie at a theater, I always eat popcorn.","circle":true},
  {"no":1659,"word":"popular","star":false,"pos":"形","meaning":"人気のある、流行の","example":"Who is a popular singer in America?","circle":false},
  {"no":1660,"word":"population","star":false,"pos":"名","meaning":"人口","example":"The population of Hyogo is over five million.","circle":false},
  {"no":1661,"word":"pork","star":false,"pos":"名","meaning":"豚肉","example":"Which do you like better, pork or beef?","circle":true},
  {"no":1662,"word":"port","star":false,"pos":"名","meaning":"港","example":"The ship left the port to sail around the world.","circle":true},
  {"no":1663,"word":"positive","star":false,"pos":"形","meaning":"積極的な、肯定的な、前向きな","example":"I like your positive way of thinking.","circle":false},
  {"no":1664,"word":"possible","star":false,"pos":"形","meaning":"可能な、実行できる","example":"It is possible to get there by 11 o'clock.","circle":false},
  {"no":1665,"word":"post","star":true,"pos":"名","meaning":"郵便","example":"My uncle sent me a book by post.","circle":false},
  {"no":1666,"word":"post office","star":true,"pos":"名","meaning":"郵便局","example":"You will find the post office on your left.","circle":false},
  {"no":1667,"word":"postbox","star":false,"pos":"名","meaning":"郵便ポスト","example":"I found a letter in my postbox.","circle":true},
  {"no":1668,"word":"postcard","star":false,"pos":"名","meaning":"郵便はがき、絵はがき","example":"I need to get a postcard to send to my grandmother.","circle":false},
  {"no":1669,"word":"poster","star":false,"pos":"名","meaning":"ポスター","example":"We made a big poster for the event.","circle":false},
  {"no":1670,"word":"pot","star":false,"pos":"名","meaning":"つぼ、なべ","example":"First, put some water into the pot.","circle":false},
  {"no":1671,"word":"potato","star":true,"pos":"名","meaning":"ジャガイモ","example":"How many potatoes do you want?","circle":false},
  {"no":1672,"word":"power","star":false,"pos":"名","meaning":"力、エネルギー","example":"Wind power and solar power are clean energy.","circle":false},
  {"no":1673,"word":"powerful","star":false,"pos":"形","meaning":"力強い、迫力のある","example":"His words are very powerful.","circle":false},
  {"no":1674,"word":"practice","star":true,"pos":"動・名","meaning":"練習（する）","example":"He practiced very hard.","circle":false},
  {"no":1675,"word":"pray","star":false,"pos":"動","meaning":"祈る、祈願する","example":"On January 1st, I visit a shrine and pray for good luck.","circle":true},
  {"no":1676,"word":"precious","star":false,"pos":"形","meaning":"貴重な、大切な","example":"Health is the most precious thing in life.","circle":true},
  {"no":1677,"word":"prefecture","star":false,"pos":"名","meaning":"県","example":"Hyogo prefecture is in the center of Japan.","circle":false},
  {"no":1678,"word":"prefer","star":false,"pos":"動","meaning":"（～のほうを）好む","example":"E-mails are more popular than letters.  But I prefer letters.","circle":false},
  {"no":1679,"word":"prepare","star":false,"pos":"動","meaning":"準備をする  　　※prepare for ～　～に備えて準備する","example":"I have to prepare for the school trip.","circle":false},
  {"no":1680,"word":"present","star":true,"pos":"名","meaning":"贈り物、プレゼント","example":"My sister gave me a birthday present.","circle":false},
  {"no":1681,"word":"presentation","star":false,"pos":"名","meaning":"発表、プレゼンテーション","example":"I made a presentation about my town in English.","circle":true},
  {"no":1682,"word":"president","star":false,"pos":"名","meaning":"会長、大統領","example":"Do you know who is the president of the country?","circle":true},
  {"no":1683,"word":"pressure","star":false,"pos":"名","meaning":"圧力","example":"Water pressure can make electricity.","circle":true},
  {"no":1684,"word":"pretty","star":false,"pos":"形・副","meaning":"①（形）（小さくて）かわいい、きれいな\n②（副）かなり","example":"①I gave her a pretty flower.\n②Pretty good!","circle":false},
  {"no":1685,"word":"price","star":false,"pos":"名","meaning":"価格、値段　　※at low price　低価格で","example":"Coffee is sold at a low price.","circle":false},
  {"no":1686,"word":"pride","star":false,"pos":"名","meaning":"誇り","example":"The daughter was her father's pride and joy.","circle":true},
  {"no":1687,"word":"prince","star":false,"pos":"名","meaning":"王子","example":"I have read \"The Little Prince\" many times.","circle":true},
  {"no":1688,"word":"princess","star":false,"pos":"名","meaning":"王女、皇太子妃","example":"The princess is going to study abroad next year.","circle":true},
  {"no":1689,"word":"principal","star":true,"pos":"名","meaning":"校長","example":"Our principal is friendly and talks to us a lot.","circle":true},
  {"no":1690,"word":"print","star":false,"pos":"動・名","meaning":"印刷（する）","example":"Do you use a printed dictionary?","circle":false},
  {"no":1691,"word":"prize","star":false,"pos":"名","meaning":"賞、ほうび、賞品","example":"Our team won the first prize at the tournament.","circle":false},
  {"no":1692,"word":"probably","star":false,"pos":"副","meaning":"おそらく、たぶん","example":"We will probably win the game.","circle":true},
  {"no":1693,"word":"problem","star":false,"pos":"名","meaning":"問題、課題　　　※No problem. 大丈夫です","example":"I'm going to share the problem with you.","circle":false},
  {"no":1694,"word":"process","star":false,"pos":"名","meaning":"過程、プロセス","example":"The process is more important than the results.","circle":true},
  {"no":1695,"word":"produce","star":false,"pos":"動","meaning":"～を生ずる、生産する","example":"Toyooka produces good bags.","circle":false},
  {"no":1696,"word":"product","star":false,"pos":"名","meaning":"製品、生産物","example":"I want to buy this new product.","circle":false},
  {"no":1697,"word":"professional","star":false,"pos":"形","meaning":"専門（職）の、プロの","example":"Playing in a professional baseball team was his dream.","circle":false},
  {"no":1698,"word":"professor","star":false,"pos":"名","meaning":"教授","example":"The professor gives students a lot of homework.","circle":true},
  {"no":1699,"word":"program","star":false,"pos":"名","meaning":"番組（表）、計画、プログラム","example":"What is your favorite TV program?","circle":false},
  {"no":1700,"word":"programmer","star":false,"pos":"名","meaning":"プログラマー","example":"I want to be a programmer.","circle":false}
];
