const WORDS19 = [
  {"no":1801,"word":"reuse","star":false,"pos":"動","meaning":"再利用する","example":"We should reuse these bottles.","circle":false},
  {"no":1802,"word":"review","star":false,"pos":"動","meaning":"復習する","example":"Let's review the last lesson.","circle":true},
  {"no":1803,"word":"rhythm","star":false,"pos":"名","meaning":"リズム","example":"He has a good sense of rhythm.","circle":true},
  {"no":1804,"word":"rice","star":true,"pos":"名","meaning":"米、ごはん","example":"I have rice and miso soup every day for breakfast.","circle":false},
  {"no":1805,"word":"rice ball","star":true,"pos":"名","meaning":"おにぎり","example":"There are three rice balls in my lunch box.","circle":false},
  {"no":1806,"word":"rice cake","star":false,"pos":"名","meaning":"もち","example":"We eat rice cake during the New Year’s holidays.","circle":false},
  {"no":1807,"word":"rich","star":false,"pos":"形","meaning":"豊かな、金持ちの","example":"He is a rich man.","circle":false},
  {"no":1808,"word":"ride","star":true,"pos":"動","meaning":"乗る、乗って行く　　【活用】 ride - rode - ridden","example":"Can you ride a bike?","circle":false},
  {"no":1809,"word":"right","star":true,"pos":"名・形・副","meaning":"①右（の、に）、右側\n②正しい（こと）\n③権利 \n※all right 大丈夫な　All right. わかりました\nThat's right. そのとおり　right now / right away 今すぐ","example":"①The boy on your right is Tom.\n②You are right.\n③Everyone has a right to learn.","circle":false},
  {"no":1810,"word":"ring","star":false,"pos":"動・名","meaning":"①（動）鳴る、響く      【活用】 ring - rang - rung\n②（名）指輪","example":"①The phone is ringing again.\n②I bought a new ring.","circle":false},
  {"no":1811,"word":"rise","star":false,"pos":"動・名","meaning":"（動）上がる　　      【活用】 rise - rose - risen\n（名）上昇、増加","example":"Look!  Smoke is rising over there.","circle":false},
  {"no":1812,"word":"risk","star":false,"pos":"名","meaning":"危険、恐れ","example":"Don't be afraid of taking risks.","circle":false},
  {"no":1813,"word":"river","star":true,"pos":"名","meaning":"川","example":"Let's go fishing in the river.","circle":false},
  {"no":1814,"word":"road","star":false,"pos":"名","meaning":"道路、道","example":"This is the main road of this town.","circle":false},
  {"no":1815,"word":"roast","star":false,"pos":"動","meaning":"（肉を）焼く、あぶる","example":"At the camp, we roasted some meat over a fire.","circle":true},
  {"no":1816,"word":"robot","star":false,"pos":"名","meaning":"ロボット","example":"My brother designs robots on computers.","circle":false},
  {"no":1817,"word":"rock","star":false,"pos":"名","meaning":"①（音楽の）ロック\n②岩、岩石","example":"①I like rock music.\n②We tried to move the rock, but it didn't move.","circle":false},
  {"no":1818,"word":"rocket","star":false,"pos":"名","meaning":"ロケット","example":"Many people worked together to make the rocket.","circle":true},
  {"no":1819,"word":"role","star":false,"pos":"名","meaning":"役、役割","example":"My role in the drama was a father.","circle":true},
  {"no":1820,"word":"roll","star":false,"pos":"名","meaning":"巻いたもの","example":"This is the last roll of toilet paper.","circle":true},
  {"no":1821,"word":"roller coaster","star":false,"pos":"名","meaning":"ジェットコースター","example":"I love to ride on roller coasters.","circle":true},
  {"no":1822,"word":"romantic","star":false,"pos":"形","meaning":"ロマンチックな","example":"I love romantic stories.","circle":true},
  {"no":1823,"word":"Rome","star":false,"pos":"名","meaning":"ローマ","example":"My parents went to Rome last summer.","circle":true},
  {"no":1824,"word":"roof","star":false,"pos":"名","meaning":"屋根","example":"The house with the black roof is my house.","circle":false},
  {"no":1825,"word":"room","star":true,"pos":"名","meaning":"部屋、室","example":"I have a bed in my room.","circle":false},
  {"no":1826,"word":"root","star":false,"pos":"名","meaning":"根、根源","example":"Plants get water through their roots.","circle":true},
  {"no":1827,"word":"rope","star":false,"pos":"名","meaning":"綱、ロープ","example":"Catch the rope.","circle":false},
  {"no":1828,"word":"rose","star":false,"pos":"名","meaning":"バラ","example":"The roses in the garden are very beautiful.","circle":true},
  {"no":1829,"word":"rough","star":false,"pos":"形","meaning":"荒れた、（表面が）ざらざらした","example":"My hands get rough in winter.","circle":true},
  {"no":1830,"word":"round","star":false,"pos":"名・形","meaning":"丸い（もの）、円形（の）","example":"We are looking for a round table.","circle":false},
  {"no":1831,"word":"route","star":false,"pos":"名","meaning":"道、ルート","example":"I usually take this route to school.","circle":true},
  {"no":1832,"word":"row","star":false,"pos":"名","meaning":"列、（劇場などの）座席の列","example":"I always sit in the front row of the classroom.","circle":true},
  {"no":1833,"word":"rude","star":false,"pos":"形","meaning":"無礼な、失礼な","example":"It is rude to ask such personal questions.","circle":true},
  {"no":1834,"word":"rug","star":false,"pos":"名","meaning":"敷物、ラグ","example":"The rug on the floor is very old.","circle":true},
  {"no":1835,"word":"rugby","star":true,"pos":"名","meaning":"ラグビー","example":"I like rugby the best.","circle":false},
  {"no":1836,"word":"rule","star":false,"pos":"名","meaning":"規則、ルール","example":"You should follow the rules.","circle":false},
  {"no":1837,"word":"ruler","star":true,"pos":"名","meaning":"ものさし、定規","example":"I have three pens, five pencils and a ruler.","circle":false},
  {"no":1838,"word":"run","star":true,"pos":"動","meaning":"走る、走って行く　※run away  逃げる　【活用】 run - ran - run","example":"He can run fast.","circle":false},
  {"no":1839,"word":"runner","star":false,"pos":"名","meaning":"走る人、（野球・競走などの）走者、ランナー","example":"Many runners took part in the Kobe Marathon.","circle":true},
  {"no":1840,"word":"Russia","star":false,"pos":"名","meaning":"ロシア（連邦）","example":"Russia is the largest country in the world.","circle":false},
  {"no":1841,"word":"sacred","star":false,"pos":"形","meaning":"神聖な","example":"Temples are sacred places.","circle":true},
  {"no":1842,"word":"sad","star":true,"pos":"形","meaning":"悲しい","example":"Her story makes us sad.","circle":false},
  {"no":1843,"word":"sadness","star":false,"pos":"名","meaning":"悲しさ","example":"I was filled with sadness because I lost my favorite toy.","circle":true},
  {"no":1844,"word":"safe","star":false,"pos":"形","meaning":"安全な","example":"You must escape to a safe place.","circle":false},
  {"no":1845,"word":"safely","star":false,"pos":"副","meaning":"安全に","example":"I hope you will go back home safely.","circle":false},
  {"no":1846,"word":"safety","star":false,"pos":"名","meaning":"安全","example":"Stay here for your own safety.","circle":false},
  {"no":1847,"word":"sail","star":false,"pos":"動","meaning":"（船が）航行する、船旅をする","example":"The man sailed to America on a boat alone.","circle":true},
  {"no":1848,"word":"salad","star":true,"pos":"名","meaning":"サラダ","example":"I eat salad and bread for breakfast.","circle":false},
  {"no":1849,"word":"sale","star":false,"pos":"名","meaning":"安売り、バーゲンセール","example":"Many shops have sales in January.","circle":false},
  {"no":1850,"word":"sales clerk","star":false,"pos":"名","meaning":"店員","example":"The sales clerk wrapped the gift beautifully.","circle":true},
  {"no":1851,"word":"salt","star":false,"pos":"名","meaning":"塩、食塩","example":"Please pass me the salt.","circle":false},
  {"no":1852,"word":"salty","star":true,"pos":"形","meaning":"塩辛い","example":"This soup is too salty.","circle":false},
  {"no":1853,"word":"same","star":true,"pos":"代・形","meaning":"同じ（もの）、同一の　　※at the same time 同時に","example":"My brother and I have the same T-shirt.","circle":false},
  {"no":1854,"word":"sandwich","star":true,"pos":"名","meaning":"サンドイッチ","example":"I have two sandwiches and an orange.","circle":false},
  {"no":1855,"word":"satisfied","star":false,"pos":"形","meaning":"満足した","example":"I am satisfied because I did my best.","circle":true},
  {"no":1856,"word":"satisfy","star":false,"pos":"動","meaning":"満たす、充足させる、満足させる","example":"My test results did not satisfy my parents.","circle":true},
  {"no":1857,"word":"Saturday","star":true,"pos":"名","meaning":"土曜日","example":"What's the plan for Saturday?","circle":false},
  {"no":1858,"word":"sauce","star":false,"pos":"名","meaning":"（料理の）ソース","example":"I love spaghetti with tomato sauce.","circle":true},
  {"no":1859,"word":"sausage","star":true,"pos":"名","meaning":"ソーセージ","example":"I ate sausages for breakfast yesterday.","circle":true},
  {"no":1860,"word":"save","star":false,"pos":"動","meaning":"①救う、助ける　\n②節約する","example":"①The doctor saved the lives of many people.\n②I'm saving money for the concert.","circle":false},
  {"no":1861,"word":"say","star":false,"pos":"動","meaning":"①言う\n②～と書いてある　　【活用】 say - said - said","example":"①My teacher said that we should work harder.\n②This dictionary says that the word has two meanings.","circle":false},
  {"no":1862,"word":"scared","star":false,"pos":"形","meaning":"おびえた、こわがって","example":"I was scared when the bee came near me.","circle":true},
  {"no":1863,"word":"scarf","star":false,"pos":"名","meaning":"スカーフ、マフラー","example":"It's cold outside, so you should wear a scarf.","circle":true},
  {"no":1864,"word":"scary","star":false,"pos":"形","meaning":"恐ろしい、こわい","example":"That movie was very scary.","circle":true},
  {"no":1865,"word":"scene","star":false,"pos":"名","meaning":"場面、舞台","example":"I like this scene of the movie.","circle":false},
  {"no":1866,"word":"schedule","star":false,"pos":"名","meaning":"予定（表）","example":"I'll check my schedule for this weekend.","circle":false},
  {"no":1867,"word":"school","star":true,"pos":"名","meaning":"学校","example":"Some students buy lunch at school.","circle":false},
  {"no":1868,"word":"school festival","star":false,"pos":"名","meaning":"文化祭","example":"Our school festival is in November.","circle":false},
  {"no":1869,"word":"school lunch","star":false,"pos":"名","meaning":"給食","example":"Many students like school lunch.","circle":false},
  {"no":1870,"word":"school trip","star":true,"pos":"名","meaning":"修学旅行","example":"We visited Kyoto on our school trip.","circle":false},
  {"no":1871,"word":"science","star":true,"pos":"名","meaning":"理科、自然科学","example":"Mr. Yoshida is our science teacher.","circle":false},
  {"no":1872,"word":"scientific","star":false,"pos":"形","meaning":"科学の、科学的な","example":"He studied the topic in a scientific way.","circle":true},
  {"no":1873,"word":"scientist","star":true,"pos":"名","meaning":"科学者","example":"Do you want to be a scientist?","circle":false},
  {"no":1874,"word":"scissors","star":true,"pos":"名","meaning":"はさみ（複数形で使う）","example":"Please be careful when you use scissors.","circle":true},
  {"no":1875,"word":"scold","star":false,"pos":"動","meaning":"しかる","example":"I was scolded by my mother.","circle":false},
  {"no":1876,"word":"score","star":false,"pos":"動・名","meaning":"得点（する）","example":"I got a high score on the English test.","circle":false},
  {"no":1877,"word":"screen","star":false,"pos":"名","meaning":"画面、スクリーン","example":"Please look at the photos on this screen.","circle":false},
  {"no":1878,"word":"scuba diving","star":false,"pos":"名","meaning":"スキューバダイビング","example":"Scuba diving is popular in Okinawa.","circle":true},
  {"no":1879,"word":"sea","star":true,"pos":"名","meaning":"海","example":"I often go to the sea.","circle":false},
  {"no":1880,"word":"seafood","star":false,"pos":"名","meaning":"シーフード、海産物","example":"I want to eat the seafood in Awaji Island.","circle":false},
  {"no":1881,"word":"search","star":false,"pos":"動・名","meaning":"（動）さがす、調べる　（名）探索","example":"I often search for funny videos on the Internet.","circle":true},
  {"no":1882,"word":"season","star":true,"pos":"名","meaning":"季節","example":"What season do you like?","circle":false},
  {"no":1883,"word":"seat","star":false,"pos":"名","meaning":"席、すわる物（所）","example":"There are many seats for the students.","circle":false},
  {"no":1884,"word":"seaweed","star":false,"pos":"名","meaning":"海藻、のり","example":"Japanese people like to eat seaweed.","circle":true},
  {"no":1885,"word":"second","star":true,"pos":"名・形・副","meaning":"①２番目（の）、第２に\n②秒","example":"①My classroom is on the second floor.\n②There are 60 seconds in a minute.","circle":false},
  {"no":1886,"word":"secret","star":false,"pos":"名","meaning":"秘密","example":"Let's keep no secrets between us.","circle":false},
  {"no":1887,"word":"section","star":false,"pos":"名","meaning":"（切ってわけられた）部分、区域","example":"There are three sections in this story.","circle":false},
  {"no":1888,"word":"see","star":true,"pos":"動","meaning":"見る、見える、会う、わかる   　 ※I see. なるほど\nLet's see　え～と　See you (soon). またね\n【活用】 see - saw - seen","example":"What do you see in this picture?","circle":false},
  {"no":1889,"word":"seed","star":false,"pos":"名","meaning":"（植物の）種","example":"These are tomato seeds.","circle":true},
  {"no":1890,"word":"seem","star":false,"pos":"動","meaning":"～のように見える、思われる","example":"I don't know her, but she seems kind.","circle":true},
  {"no":1891,"word":"select","star":false,"pos":"動","meaning":"選ぶ、選択する","example":"Please select your favorite one from the list.","circle":true},
  {"no":1892,"word":"selection","star":false,"pos":"名","meaning":"選ぶこと、選択","example":"This cake was a good selection.","circle":true},
  {"no":1893,"word":"selfish","star":false,"pos":"形","meaning":"わがままな","example":"Don't be so selfish.","circle":true},
  {"no":1894,"word":"sell","star":false,"pos":"動","meaning":"売る、売っている　           　【活用】 sell - sold - sold","example":"The bookstore sells some DVDs.","circle":false},
  {"no":1895,"word":"send","star":false,"pos":"動","meaning":"送る、（手紙などを）出す　　【活用】 send - sent - sent","example":"Please send more pictures to me.","circle":false},
  {"no":1896,"word":"senior","star":false,"pos":"形","meaning":"年上の、上級の　　※senior high school　高校","example":"I finished senior high school last spring.","circle":false},
  {"no":1897,"word":"sense","star":false,"pos":"名","meaning":"感覚、センス","example":"My father has a good sense of humor.","circle":false},
  {"no":1898,"word":"sentence","star":false,"pos":"名","meaning":"文","example":"Please make a sentence with this word.","circle":true},
  {"no":1899,"word":"separate","star":false,"pos":"動","meaning":"引き離す、分ける","example":"We have to separate the garbage.","circle":false},
  {"no":1900,"word":"September","star":true,"pos":"名","meaning":"９月","example":"In America, school starts in September.","circle":false}
];
