const WORDS03 = [
  {"no":201,"word":"before","star":false,"pos":"前・接・副","meaning":"①（前・接）～の（～が～する）前に\n②（副）今まで、以前に","example":"①I will finish my homework before dinner.\n②I have never visited that place before.","circle":false},
  {"no":202,"word":"begin","star":false,"pos":"動","meaning":"始まる、始める　　    　【活用】 begin - began - begun","example":"English class begins at 9 a.m.","circle":false},
  {"no":203,"word":"beginner","star":false,"pos":"名","meaning":"初心者","example":"I have just started playing soccer, so I am a beginner.","circle":false},
  {"no":204,"word":"beginning","star":false,"pos":"名","meaning":"始まり","example":"We sing English songs at the beginning of each class.","circle":false},
  {"no":205,"word":"behave","star":false,"pos":"動","meaning":"振る舞う","example":"You should not behave like a little child.","circle":true},
  {"no":206,"word":"behavior","star":false,"pos":"名","meaning":"ふるまい","example":"We cannot accept his bad behavior.","circle":true},
  {"no":207,"word":"behind","star":false,"pos":"前","meaning":"～の後ろに（の）","example":"Do you know the woman behind him?","circle":false},
  {"no":208,"word":"Beijing","star":false,"pos":"名","meaning":"北京","example":"Beijing is the capital of China.","circle":true},
  {"no":209,"word":"believe","star":false,"pos":"動","meaning":"信じる、～と思う","example":"I believe I can do it.","circle":false},
  {"no":210,"word":"bell","star":false,"pos":"名","meaning":"鈴、鐘","example":"I heard the bell and went to the door.","circle":false},
  {"no":211,"word":"belong","star":false,"pos":"動","meaning":"所属する　　※belong to ～　～の一員である","example":"I belong to the music club.","circle":false},
  {"no":212,"word":"below","star":false,"pos":"前・副","meaning":"下の（に、を）","example":"The temperature is below zero.","circle":false},
  {"no":213,"word":"belt","star":false,"pos":"名","meaning":"ベルト","example":"Your belt is longer than mine.","circle":false},
  {"no":214,"word":"bench","star":false,"pos":"名","meaning":"ベンチ、長いす","example":"We sat on the bench.","circle":false},
  {"no":215,"word":"Berlin","star":false,"pos":"名","meaning":"ベルリン","example":"The Berlin Wall fell in 1989.","circle":true},
  {"no":216,"word":"beside","star":false,"pos":"前","meaning":"～のそばに","example":"The dog likes to sit beside me.","circle":false},
  {"no":217,"word":"besides","star":false,"pos":"副","meaning":"さらに、そのうえ","example":"I'm not feeling well.  Besides, I have a fever.","circle":true},
  {"no":218,"word":"best","star":true,"pos":"名・形・副","meaning":"①（形・副）最もよく（い）（good, wellの最上級）\n 【活用】 good (well) - better - best\n②（名）一番よいもの、最善の努力\n※do (try) one's best  全力を尽くす","example":"①She can sing the best in her class.\n②I will do my best.","circle":false},
  {"no":219,"word":"better","star":false,"pos":"形・副","meaning":"もっとよい（く）、もっと上手い（く）（well, goodの比較級）　\n 【活用】 well (good) - better - best","example":"Which do you like better, chicken or beef?","circle":false},
  {"no":220,"word":"between","star":false,"pos":"前","meaning":"（２つの）間に（で）","example":"Hyogo is between Osaka and Okayama.","circle":false},
  {"no":221,"word":"beyond","star":false,"pos":"前","meaning":"～の向こうに（へ・で・の）","example":"My house is just beyond that hill.","circle":true},
  {"no":222,"word":"bicycle","star":true,"pos":"名","meaning":"自転車（bikeとも言う）","example":"I go to school by bicycle.","circle":false},
  {"no":223,"word":"big","star":true,"pos":"形","meaning":"大きな、大きい","example":"I live in a big city.","circle":false},
  {"no":224,"word":"bike","star":true,"pos":"名","meaning":"自転車（bicycleの略）","example":"I go to school by bike.","circle":false},
  {"no":225,"word":"bill","star":false,"pos":"名","meaning":"請求書","example":"This is the bill for the water I used last month.","circle":true},
  {"no":226,"word":"billion","star":false,"pos":"名・形","meaning":"（名）10億　（形）10億の","example":"There are over 7 billion people in the world.","circle":true},
  {"no":227,"word":"bird","star":true,"pos":"名","meaning":"鳥","example":"The White Stork (konotori ) is a large white bird.","circle":false},
  {"no":228,"word":"birthday","star":true,"pos":"名","meaning":"誕生日","example":"My birthday is April 22.","circle":false},
  {"no":229,"word":"bit","star":false,"pos":"名","meaning":"少し、少量、ちょっと","example":"This bag is a bit too small.","circle":true},
  {"no":230,"word":"bite","star":false,"pos":"動","meaning":"かむ　　　【活用】 bite - bit - bitten","example":"Biting your nails is a bad habit.","circle":true},
  {"no":231,"word":"bitter","star":true,"pos":"形","meaning":"苦い","example":"Coffee without sugar is too bitter for me.","circle":false},
  {"no":232,"word":"black","star":true,"pos":"名・形","meaning":"黒（の）","example":"Please put your books into that black box.","circle":false},
  {"no":233,"word":"blackboard","star":false,"pos":"名","meaning":"黒板","example":"Look at the blackboard everyone.","circle":false},
  {"no":234,"word":"blank","star":false,"pos":"名・形","meaning":"（名）空白、空所　（形）何も書かれていない","example":"Please write your name in the blank.","circle":true},
  {"no":235,"word":"blanket","star":false,"pos":"名","meaning":"毛布","example":"I put a blanket on my daughter.","circle":true},
  {"no":236,"word":"bleed","star":false,"pos":"動","meaning":"出血する","example":"Oh, your nose is bleeding!","circle":true},
  {"no":237,"word":"blind","star":false,"pos":"形","meaning":"目の不自由な","example":"The blind musician created a lot of great songs.","circle":false},
  {"no":238,"word":"block","star":true,"pos":"名","meaning":"かたまり、ブロック、区画","example":"We need a block of ice to keep this food cool.","circle":false},
  {"no":239,"word":"blog","star":false,"pos":"名","meaning":"ブログ","example":"I like to read the blog of my favorite singer.","circle":false},
  {"no":240,"word":"blond","star":false,"pos":"形","meaning":"ブロンドの、金髪の","example":"My sister has blond hair.","circle":true},
  {"no":241,"word":"bloom","star":false,"pos":"動","meaning":"（花が）咲く","example":"Japanese schools start when the cherry blossoms bloom.","circle":true},
  {"no":242,"word":"blossom","star":false,"pos":"名","meaning":"（特に果樹の）花","example":"The blossoms of this tree are beautiful in spring.","circle":true},
  {"no":243,"word":"blow","star":false,"pos":"動","meaning":"（風が）吹く　　　　　【活用】 blow - blew - blown","example":"The wind is blowing from the west.","circle":false},
  {"no":244,"word":"blue","star":true,"pos":"名・形","meaning":"青（の）","example":"Look at the clear blue sky.","circle":false},
  {"no":245,"word":"board","star":false,"pos":"動・名","meaning":"①（動）（船・飛行機・列車・バスなどに）乗り込む　\n②（名）板、台","example":"①We must board our plane now. \n②We can use this board to make a table.","circle":true},
  {"no":246,"word":"boarding","star":false,"pos":"名","meaning":"搭乗　　※boarding pass  搭乗券","example":"The flight is now ready for boarding.","circle":true},
  {"no":247,"word":"boat","star":true,"pos":"名","meaning":"ボート、小舟","example":"Can you see a boat over there?","circle":false},
  {"no":248,"word":"body","star":true,"pos":"名","meaning":"体、肉体","example":"Playing sports makes your body strong.","circle":false},
  {"no":249,"word":"boil","star":false,"pos":"動","meaning":"ゆでる、沸騰させる","example":"Boil the egg for five minutes.","circle":false},
  {"no":250,"word":"bomb","star":false,"pos":"名","meaning":"爆弾","example":"Many bombs were dropped on that town.","circle":false},
  {"no":251,"word":"bone","star":false,"pos":"名","meaning":"骨","example":"Take out the bones when you eat fish.","circle":true},
  {"no":252,"word":"book","star":true,"pos":"名","meaning":"本、書物","example":"I like reading books.","circle":false},
  {"no":253,"word":"bookcase","star":false,"pos":"名","meaning":"本棚、本箱","example":"Please return the book to the bookcase after reading.","circle":true},
  {"no":254,"word":"bookstore","star":true,"pos":"名","meaning":"書店","example":"I saw him at the bookstore.","circle":false},
  {"no":255,"word":"boot","star":true,"pos":"名","meaning":"長ぐつ、ブーツ","example":"You will need a pair of boots if it rains.","circle":true},
  {"no":256,"word":"border","star":false,"pos":"名","meaning":"国境","example":"This line is the border between America and Canada.","circle":false},
  {"no":257,"word":"bored","star":false,"pos":"形","meaning":"退屈した","example":"I was bored because I had nothing to do.","circle":false},
  {"no":258,"word":"boring","star":false,"pos":"形","meaning":"退屈な","example":"The movie was boring.","circle":false},
  {"no":259,"word":"born","star":false,"pos":"動","meaning":"（bearの過去分詞） 生まれる　   ※be born in ～　～に生まれる","example":"I was born in Takarazuka.","circle":false},
  {"no":260,"word":"borrow","star":false,"pos":"動","meaning":"借りる","example":"You can borrow some books from the library.","circle":false},
  {"no":261,"word":"both","star":false,"pos":"代・形・副","meaning":"両方、両方とも　　※both A and B   AもBも両方","example":"Both he and his brother are my friends.","circle":false},
  {"no":262,"word":"bottle","star":false,"pos":"名","meaning":"ボトル、びん","example":"They found a big bottle on the table.","circle":false},
  {"no":263,"word":"bottom","star":false,"pos":"名","meaning":"底、最下部","example":"Look at the picture at the bottom of the page.","circle":false},
  {"no":264,"word":"bowl","star":false,"pos":"名","meaning":"どんぶり、ボウル","example":"I usually eat a bowl of rice for breakfast.","circle":true},
  {"no":265,"word":"box","star":true,"pos":"名","meaning":"箱","example":"A: Where is my camera?  B: It's in the box.","circle":false},
  {"no":266,"word":"boxing","star":true,"pos":"名","meaning":"ボクシング","example":"I like watching boxing matches.","circle":true},
  {"no":267,"word":"boy","star":true,"pos":"名","meaning":"男の子、少年","example":"The boy standing there is my brother.","circle":false},
  {"no":268,"word":"boyfriend","star":false,"pos":"名","meaning":"ボーイフレンド","example":"My sister has a boyfriend.","circle":true},
  {"no":269,"word":"brain","star":false,"pos":"名","meaning":"脳、頭脳","example":"Our brains work even when we sleep.","circle":true},
  {"no":270,"word":"brass band","star":false,"pos":"名","meaning":"ブラスバンド、吹奏楽","example":"I am a member of the brass band club.","circle":false},
  {"no":271,"word":"brave","star":true,"pos":"形","meaning":"勇敢な","example":"She was brave because she tried to save the children.","circle":false},
  {"no":272,"word":"Brazil","star":false,"pos":"名","meaning":"ブラジル","example":"The Olympics were held in Brazil in 2016.","circle":false},
  {"no":273,"word":"bread","star":true,"pos":"名","meaning":"パン","example":"I always eat bread for breakfast.","circle":false},
  {"no":274,"word":"break","star":false,"pos":"動・名","meaning":"①（動）壊す   【活用】 break - broke - broken\n②（名）休憩、中断","example":"①I broke my arm, but I am fine now.\n②We have a short break now.","circle":false},
  {"no":275,"word":"breakfast","star":true,"pos":"名","meaning":"朝食","example":"What did you have for breakfast?","circle":false},
  {"no":276,"word":"breath","star":false,"pos":"名","meaning":"息、呼吸","example":"I take a deep breath when I feel nervous.","circle":true},
  {"no":277,"word":"breathe","star":false,"pos":"動","meaning":"呼吸する、息をする","example":"We cannot breathe without air.","circle":true},
  {"no":278,"word":"bridge","star":true,"pos":"名","meaning":"橋","example":"You can see the Akashi Kaikyo Bridge from here.","circle":false},
  {"no":279,"word":"bright","star":false,"pos":"形","meaning":"（光が）明るい、ぴかぴか（きらきら）光る","example":"The city was bright even at night.","circle":false},
  {"no":280,"word":"bring","star":false,"pos":"動","meaning":"（物を）持ってくる   　【活用】 bring - brought - brought","example":"I will bring my camera to the party.","circle":false},
  {"no":281,"word":"British","star":false,"pos":"名・形","meaning":"イギリスの、イギリス人（の）","example":"The British love tea.","circle":false},
  {"no":282,"word":"broadcasting","star":false,"pos":"名","meaning":"放送","example":"NHK is the public broadcasting company of Japan.","circle":true},
  {"no":283,"word":"broaden","star":false,"pos":"動","meaning":"広げる","example":"Reading books broadens our mind.","circle":true},
  {"no":284,"word":"broccoli","star":true,"pos":"名","meaning":"ブロッコリー","example":"I did not like broccoli when I was a child.","circle":true},
  {"no":285,"word":"bronze","star":false,"pos":"名・形","meaning":"ブロンズ（の）、銅（の）","example":"I got a bronze medal at the speech contest.","circle":true},
  {"no":286,"word":"brother","star":true,"pos":"名","meaning":"（男の）兄弟、兄、弟","example":"I have two brothers.","circle":false},
  {"no":287,"word":"brown","star":true,"pos":"名・形","meaning":"茶色（の）","example":"Look at the girl with brown hair.","circle":false},
  {"no":288,"word":"brush","star":true,"pos":"動・名","meaning":"（動）（ブラシで）みがく　（名）ブラシ、筆","example":"You must brush your teeth before sleeping.","circle":false},
  {"no":289,"word":"bucket","star":false,"pos":"名","meaning":"バケツ","example":"Can you fill this bucket with water?","circle":true},
  {"no":290,"word":"build","star":false,"pos":"動","meaning":"～を建てる、造る　　【活用】 build - built - built","example":"The Akashi Kaikyo Bridge was built in 1998.","circle":false},
  {"no":291,"word":"building","star":false,"pos":"名","meaning":"建物","example":"Tokyo has more buildings than Kobe.","circle":false},
  {"no":292,"word":"burn","star":false,"pos":"動","meaning":"燃える、燃やす　　【活用】 burn - burned/burnt - burned/burnt","example":"Paper burns easily.","circle":false},
  {"no":293,"word":"bury","star":false,"pos":"動","meaning":"埋める、埋葬する","example":"We believe some treasure is buried around here.","circle":true},
  {"no":294,"word":"bus","star":true,"pos":"名","meaning":"バス","example":"I will take a bus from here.","circle":false},
  {"no":295,"word":"bus stop","star":false,"pos":"名","meaning":"バス停","example":"You can get on the bus for Kobe at that bus stop.","circle":false},
  {"no":296,"word":"bush","star":false,"pos":"名","meaning":"低木、茂み","example":"The cat stayed in the bush until the dog went away.","circle":true},
  {"no":297,"word":"business","star":false,"pos":"名","meaning":"商売、事業","example":"My father enjoys doing business with his friends.","circle":false},
  {"no":298,"word":"busy","star":true,"pos":"形","meaning":"忙しい      ※be busy with ～　～に忙しい","example":"I am very busy now.","circle":false},
  {"no":299,"word":"but","star":false,"pos":"接","meaning":"しかし、でも　　　　※not A but B  　AでなくてB","example":"I like dogs, but my sister likes cats.","circle":false},
  {"no":300,"word":"butter","star":false,"pos":"名","meaning":"バター","example":"He put butter on his bread.","circle":false}
];