const WORDS06 = [
{"no":501,"word":"count","star":false,"pos":"動","meaning":"数える","example":"I counted the money.","circle":false},
{"no":502,"word":"country","star":true,"pos":"名","meaning":"国","example":"I want to go to a foreign country.","circle":false},
{"no":503,"word":"countryside","star":false,"pos":"名","meaning":"田舎","example":"I love living in the countryside.","circle":true},
{"no":504,"word":"couple","star":false,"pos":"名","meaning":"一組、夫婦、カップル","example":"That place is popular among young couples.","circle":true},
{"no":505,"word":"courage","star":false,"pos":"名","meaning":"勇気","example":"This man had the courage to fight.","circle":false},
{"no":506,"word":"course","star":false,"pos":"名","meaning":"進路　　    ※of course もちろん","example":"A: Can you teach me?  B: Of course.","circle":false},
{"no":507,"word":"court","star":false,"pos":"名","meaning":"（テニスなどの）コート","example":"Do you have tennis courts in your school?","circle":false},
{"no":508,"word":"cousin","star":false,"pos":"名","meaning":"いとこ","example":"One of my cousins is studying in America.","circle":false},
{"no":509,"word":"cover","star":false,"pos":"動","meaning":"～を覆う","example":"Snow covers the top of Mt. Fuji in winter.","circle":false},
{"no":510,"word":"cow","star":true,"pos":"名","meaning":"雌牛（特に乳牛）","example":"My host family in Australia have many cows.","circle":false},
{"no":511,"word":"craft","star":true,"pos":"名","meaning":"工作　　※arts and crafts　図画工作","example":"My sister likes making paper crafts.","circle":true},
{"no":512,"word":"crane","star":false,"pos":"名","meaning":"ツル","example":"We made a thousand paper cranes for her.","circle":false},
{"no":513,"word":"crash","star":false,"pos":"動","meaning":"衝突する","example":"The car crashed into another car.","circle":false},
{"no":514,"word":"crayon","star":true,"pos":"名","meaning":"クレヨン","example":"I still keep the crayons I used at kindergarten.","circle":true},
{"no":515,"word":"cream","star":false,"pos":"名","meaning":"クリーム","example":"I put some cream on my hands every morning.","circle":true},
{"no":516,"word":"create","star":false,"pos":"動","meaning":"創作する、作り出す","example":"The writer created many great stories.","circle":false},
{"no":517,"word":"creative","star":false,"pos":"形","meaning":"創造力のある","example":"He is very creative.","circle":false},
{"no":518,"word":"creature","star":false,"pos":"名","meaning":"生き物","example":"They believe that some creatures live on that planet.","circle":true},
{"no":519,"word":"cricket","star":false,"pos":"名","meaning":"クリケット","example":"Cricket is one of the most popular sports in the UK.","circle":true},
{"no":520,"word":"cross","star":false,"pos":"動","meaning":"（～を）渡る","example":"We can cross the Akashi Kaikyo Bridge by car.","circle":false},
{"no":521,"word":"crossing","star":false,"pos":"名","meaning":"交差点、横断歩道","example":"You should drive slowly near crossings.","circle":true},
{"no":522,"word":"crowd","star":false,"pos":"名","meaning":"群衆、人ごみ","example":"There was a big crowd in front of the shop.","circle":true},
{"no":523,"word":"crowded","star":false,"pos":"形","meaning":"混雑した、満員の","example":"This train is very crowded today.","circle":false},
{"no":524,"word":"cry","star":false,"pos":"動","meaning":"叫ぶ、泣く","example":"Please stop crying.","circle":false},
{"no":525,"word":"cucumber","star":false,"pos":"名","meaning":"キュウリ","example":"Some students don't like cucumbers.","circle":false},
{"no":526,"word":"cultural","star":true,"pos":"形","meaning":"文化の、文化的な","example":"I saw many cultural differences in the country.","circle":true},
{"no":527,"word":"culture","star":false,"pos":"名","meaning":"習慣、文化","example":"I'm interested in Australian culture.","circle":false},
{"no":528,"word":"cup","star":true,"pos":"名","meaning":"茶わん、カップ   ※a cup of ～　カップ一杯の","example":"May I have a cup of coffee ?","circle":false},
{"no":529,"word":"curious","star":false,"pos":"形","meaning":"好奇心の強い","example":"I am curious about foreign cultures.","circle":true},
{"no":530,"word":"curry","star":true,"pos":"名","meaning":"カレー料理　　　※curry and rice  カレーライス","example":"Let's eat curry and rice at that shop.","circle":false},
{"no":531,"word":"curtain","star":false,"pos":"名","meaning":"カーテン","example":"I like this color for the curtains in my room.","circle":true},
{"no":532,"word":"cushion","star":false,"pos":"名","meaning":"クッション","example":"The cushions look good with the sofa.","circle":true},
{"no":533,"word":"custom","star":false,"pos":"名","meaning":"風習、習慣","example":"Every culture has its own customs.","circle":false},
{"no":534,"word":"customer","star":false,"pos":"名","meaning":"客、顧客","example":"The clerks stood at the door to welcome customers.","circle":false},
{"no":535,"word":"cut","star":false,"pos":"動","meaning":"切る　　※cut off  切り取る　　【活用】 cut - cut - cut","example":"I cut my finger when I was cooking.","circle":false},
{"no":536,"word":"cute","star":true,"pos":"形","meaning":"かわいらしい、かわいい","example":"Your dog is very cute!","circle":false},
{"no":537,"word":"cycling","star":true,"pos":"名","meaning":"サイクリング","example":"My hobby is cycling.","circle":false},
{"no":538,"word":"dad","star":false,"pos":"名","meaning":"パパ、お父さん","example":"Come on, Dad!","circle":false},
{"no":539,"word":"daily","star":false,"pos":"形","meaning":"毎日の、日常の","example":"Nature has always been a part of our daily lives.","circle":false},
{"no":540,"word":"dam","star":false,"pos":"名","meaning":"ダム","example":"I enjoyed cycling around the dam with my father.","circle":true},
{"no":541,"word":"damage","star":false,"pos":"動","meaning":"～に損害を与える","example":"Many houses were damaged by the typhoon.","circle":false},
{"no":542,"word":"dance","star":true,"pos":"動・名","meaning":"（動）踊る　（名）踊り","example":"Shall we dance?","circle":false},
{"no":543,"word":"dancer","star":false,"pos":"名","meaning":"踊る人、ダンサー","example":"I want to be a dancer in the future.","circle":false},
{"no":544,"word":"dancing","star":false,"pos":"名","meaning":"踊ること","example":"My brother is good at dancing.","circle":false},
{"no":545,"word":"danger","star":false,"pos":"名","meaning":"危険","example":"He told us the dangers of climbing.","circle":false},
{"no":546,"word":"dangerous","star":false,"pos":"形","meaning":"危険な","example":"Making fireworks is hard and dangerous.","circle":false},
{"no":547,"word":"dark","star":false,"pos":"形","meaning":"（光がなくて）暗い","example":"The two men began to walk along the dark street.","circle":false},
{"no":548,"word":"darkness","star":false,"pos":"名","meaning":"暗さ、暗やみ","example":"The cat disappeared into the darkness.","circle":true},
{"no":549,"word":"data","star":false,"pos":"名","meaning":"データ、資料","example":"We need some new data to write our report.","circle":true},
{"no":550,"word":"date","star":true,"pos":"名","meaning":"日付、月日","example":"What date is it today?","circle":false},
{"no":551,"word":"daughter","star":false,"pos":"名","meaning":"娘","example":"I saw your daughter at the station last night.","circle":false},
{"no":552,"word":"day","star":true,"pos":"名","meaning":"①１日、（ある特定の）日\n②昼間、日中\n ※one day  ある日　all day (long)  １日中\n the day after tomorrow  あさって　 these days  最近、このごろは\n in those days  当時","example":"①I play with kendama every day.  \n②Some people work at night and sleep during the day.","circle":false},
{"no":553,"word":"dead","star":false,"pos":"形","meaning":"死んだ","example":"The animal doesn't move.  It looks dead.","circle":false},
{"no":554,"word":"deal","star":false,"pos":"動","meaning":"扱う　　※deal with ～  ～を扱う","example":"This book deals with the new technology.","circle":true},
{"no":555,"word":"dear","star":false,"pos":"形・間","meaning":"①（形）親愛なる～（手紙の書きだしに使う） \n②（間）おや、まあ","example":"①Dear Mr. Brown\n②Oh, dear!  I dropped my ice cream.","circle":false},
{"no":556,"word":"death","star":false,"pos":"名","meaning":"死、死亡","example":"It was difficult for me to accept my pet's death.","circle":false},
{"no":557,"word":"debate","star":false,"pos":"動・名","meaning":"討論（する）、ディベート（をする）","example":"We debated about the future of our town.","circle":true},
{"no":558,"word":"December","star":true,"pos":"名","meaning":"１２月","example":"It begins to snow in December in the Tajima area.","circle":false},
{"no":559,"word":"decide","star":false,"pos":"動","meaning":"決心する","example":"They decided to build a bridge.","circle":false},
{"no":560,"word":"decision","star":false,"pos":"名","meaning":"決断","example":"What do you think of his decision?","circle":false},
{"no":561,"word":"decorate","star":false,"pos":"動","meaning":"（場所などを）飾る、装飾する","example":"I decorated my room with some flowers and pictures.","circle":true},
{"no":562,"word":"decoration","star":false,"pos":"名","meaning":"装飾、デコレーション","example":"The Christmas decorations looked beautiful.","circle":true},
{"no":563,"word":"decrease","star":false,"pos":"動","meaning":"減る、減少する","example":"The number of children is decreasing in Japan.","circle":true},
{"no":564,"word":"deep","star":false,"pos":"形","meaning":"深い、奥の","example":"This lake is about 50 meters deep.","circle":false},
{"no":565,"word":"deeply","star":false,"pos":"副","meaning":"深く","example":"We should think about the problem deeply.","circle":false},
{"no":566,"word":"deer","star":false,"pos":"名","meaning":"シカ（複数形も deer）","example":"Nara is famous for its deer.","circle":true},
{"no":567,"word":"degree","star":false,"pos":"名","meaning":"（温度・角などの）度","example":"Water boils at 100 degrees.","circle":true},
{"no":568,"word":"degree Celsius","star":false,"pos":"名","meaning":"摂氏","example":"It will be around nine degrees Celsius tonight.","circle":false},
{"no":569,"word":"delicious","star":true,"pos":"形","meaning":"おいしい","example":"Kobe beef is delicious.","circle":false},
{"no":570,"word":"deliver","star":false,"pos":"動","meaning":"配達する","example":"On her birthday, I will deliver flowers to her house.","circle":true},
{"no":571,"word":"delivery","star":false,"pos":"名","meaning":"配達","example":"We were busy yesterday, so we ordered a pizza delivery.","circle":true},
{"no":572,"word":"demonstration","star":false,"pos":"名","meaning":"デモ","example":"They joined demonstrations against war.","circle":false},
{"no":573,"word":"dentist","star":true,"pos":"名","meaning":"歯医者","example":"I went to the dentist because I had a bad toothache.","circle":false},
{"no":574,"word":"department store","star":true,"pos":"名","meaning":"デパート","example":"There are two big department stores in Kobe.","circle":false},
{"no":575,"word":"departure","star":false,"pos":"名","meaning":"出発","example":"The departure of the flight will be late.","circle":false},
{"no":576,"word":"depend","star":false,"pos":"動","meaning":"～による、～次第である　 ※depend on ～　～次第だ、～による","example":"Our plan depends on the weather.","circle":false},
{"no":577,"word":"depressed","star":false,"pos":"形","meaning":"落胆した、元気がない","example":"I was depressed because I didn't win the game.","circle":false},
{"no":578,"word":"describe","star":false,"pos":"動","meaning":"描写する、特徴を述べる","example":"Please describe the picture in English.","circle":true},
{"no":579,"word":"desert","star":false,"pos":"名","meaning":"砂漠","example":"It is difficult to live in a desert.","circle":true},
{"no":580,"word":"design","star":false,"pos":"動・名","meaning":"デザイン（する）、図案（を作る）、（～を）設計（する）","example":"A famous architect, Tadao Ando, designed this museum.","circle":false},
{"no":581,"word":"designer","star":false,"pos":"名","meaning":"デザイナー、設計者","example":"She is a famous designer in Japan.","circle":false},
{"no":582,"word":"desk","star":true,"pos":"名","meaning":"机","example":"There is a pencil on the desk.","circle":false},
{"no":583,"word":"dessert","star":true,"pos":"名","meaning":"デザート","example":"Today's dessert is strawberry ice cream.","circle":true},
{"no":584,"word":"destroy","star":false,"pos":"動","meaning":"破壊する、こわす","example":"This building was destroyed in August 1945.","circle":false},
{"no":585,"word":"detail","star":false,"pos":"名","meaning":"細部、詳細","example":"I will tell you the details about it later.","circle":true},
{"no":586,"word":"develop","star":false,"pos":"動","meaning":"発展させる、発展する","example":"Many foreigners helped to develop Kobe.","circle":false},
{"no":587,"word":"developed","star":false,"pos":"形","meaning":"発達した　　　　※developed countries 先進国","example":"Developed countries talked about how to stop pollution.","circle":false},
{"no":588,"word":"developing","star":false,"pos":"形","meaning":"発展途上の　　※developing countries 発展途上国","example":"In developing countries, some children cannot go to school.","circle":false},
{"no":589,"word":"device","star":false,"pos":"名","meaning":"装置、機器","example":"There are many useful devices to help our communication.","circle":true},
{"no":590,"word":"diamond","star":true,"pos":"名","meaning":"ダイヤモンド","example":"Diamond is one of the hardest stones.","circle":true},
{"no":591,"word":"diary","star":false,"pos":"名","meaning":"日記       ※keep a diary  日記をつける","example":"I keep a diary to remember what happened.","circle":false},
{"no":592,"word":"dictionary","star":true,"pos":"名","meaning":"辞書、事典","example":"I use some dictionaries at school.","circle":false},
{"no":593,"word":"did","star":false,"pos":"動・助","meaning":"doの過去形","example":"Did you eat breakfast?","circle":false},
{"no":594,"word":"die","star":false,"pos":"動","meaning":"死ぬ","example":"My grandfather died five years ago.","circle":false},
{"no":595,"word":"difference","star":false,"pos":"名","meaning":"違い、違うこと","example":"Can you find any differences between these two pictures?","circle":false},
{"no":596,"word":"different","star":true,"pos":"形","meaning":"違った、いろいろな　　※be different from ～　～と違っている","example":"My plan is very different from yours.","circle":false},
{"no":597,"word":"differently","star":false,"pos":"副","meaning":"（～と）異なって","example":"People from different countries speak English differently.","circle":false},
{"no":598,"word":"difficult","star":true,"pos":"形","meaning":"難しい、困難な","example":"At first, English was difficult for me.  Now I love it.","circle":false},
{"no":599,"word":"difficulty","star":false,"pos":"名","meaning":"難しさ、困難、苦労","example":"They faced many difficulties.","circle":false},
{"no":600,"word":"dining room","star":false,"pos":"名","meaning":"食堂、ダイニングルーム","example":"We eat dinner in the dining room together.","circle":false}
];
